[MWPW-133250] CTA-Carousel: Gen AI followup Elements
adobecom/express pull request #101
Opened 2023-07-20 21:24 UTC by qiyundai

Resolves: [MWPW-133250](https://jira.corp.adobe.com/browse/MWPW-133250)

This follow up feature allows Gen AI frictionless experience to be added to the cta carousel.
The quick-action variant combined with the gen-ai variant will shoe-horn a gen-ai input field into the first card
A gen-ai alone variant will generate the carousel with variable width cards and prepend a stand-alone gen-ai input at the beginning.

Both gen AI inputs will redirect people to the product with a prompt param value replaced with what's in the input, joined by '+'

3 new placeholders are added for this feature: 
![Screen Shot 2023-07-20 at 4 21 56 PM](https://github.com/adobecom/express/assets/57737624/439e679b-50dc-421e-b8d6-1a2ed5f9d3ab)
However, in the quick-action + gen-ai variant, since the input is appended to the first card, the generate link and the generate text will first be attempted to be fetched from the first card's first link, and then fall back to the placeholders mentioned in the screenshot above.

Test URLs:
- Before: https://main--express--adobecom.hlx.page/drafts/qiyundai/homepage-v3/sandbox?lighthouse=on
- After: https://mwpw-133250-branch--express--adobecom.hlx.page/drafts/qiyundai/homepage-v3/sandbox?lighthouse=on

2023-07-20 21:34 UTC, JingleH commented on express/blocks/cta-carousel/cta-carousel.js
> +        if (genAILink !== '') window.location.assign(genAILink);
We are taking in users input here so we better be cautious against getting XSS attacked

2023-07-20 21:36 UTC, JingleH commented on express/blocks/cta-carousel/cta-carousel.js
> +        const genAIForm = createTag('form', { class: 'gen-ai-input-form' });
I think these are a little repetitious with the below ones. Maybe we can extract into a function that creates these tags

2023-07-20 21:37 UTC, JingleH commented on express/blocks/cta-carousel/cta-carousel.js
> +          if (genAILink !== '') window.location.assign(genAILink);
same as below

2023-07-20 21:42 UTC, JingleH requested changes
left a few comments plus this review

2023-07-20 21:42 UTC, JingleH commented on express/blocks/cta-carousel/cta-carousel.js
> +            genAISubmit.disabled = genAIInput.value === '';
I think we are enabling the **"Generate"** button only when user input. But in the case when people click Generate and then Back, they would see the button being disabled although texts are there (browser caches form input, but that won't trigger this eventListener). One approach for this is to extract this handler and trigger it during decorate(), and add it to the listener

2023-07-21 09:54 UTC, vhargrave requested changes
Several inputs for this: 
1. If authors are already inputting a specific URL which converts to that gen text field, then we do not need another variant for this block. 
2. I'd like to see a unit test covering this new gen ai feature
3. while testing the second gen ai input didn't work for me. Can you take a look?
![image](https://github.com/adobecom/express/assets/115231412/4f2aaba9-edb2-4a85-a85e-9f158140fb90)

2023-07-21 16:01 UTC, qiyundai commented
> Several inputs for this:
> 
> 1. If authors are already inputting a specific URL which converts to that gen text field, then we do not need another variant for this block.
> 2. I'd like to see a unit test covering this new gen ai feature
> 3. while testing the second gen ai input didn't work for me. Can you take a look?
>    ![image](https://user-images.githubusercontent.com/115231412/255141301-4f2aaba9-edb2-4a85-a85e-9f158140fb90.png)

1. there are 2 reasons we could benefit from doing it as a variant: **a)** I'm not sure the link format will be reliable as it's product side beta feature; **b)** the non-combo gen-ai variant actually has a different styling on block level.
2. I'm actually missing unit test for the entire block and once again this is a crunch...
3. I broke it last night with a WIP commit 😅. Should be good now, though.

2023-07-21 22:03 UTC, JingleH approved these changes
I know this is a crunch and it looks like all of the critical things are addressed, so I am giving an approval

2023-07-21 23:53 UTC, apganapa approved these changes

2023-07-24 09:35 UTC, vhargrave commented
> > Several inputs for this:
> > 
> > 1. If authors are already inputting a specific URL which converts to that gen text field, then we do not need another variant for this block.
> > 2. I'd like to see a unit test covering this new gen ai feature
> > 3. while testing the second gen ai input didn't work for me. Can you take a look?
> >    ![image](https://user-images.githubusercontent.com/115231412/255141301-4f2aaba9-edb2-4a85-a85e-9f158140fb90.png)
> 
> 1. there are 2 reasons we could benefit from doing it as a variant: **a)** I'm not sure the link format will be reliable as it's product side beta feature; **b)** the non-combo gen-ai variant actually has a different styling on block level.
> 2. I'm actually missing unit test for the entire block and once again this is a crunch...
> 3. I broke it last night with a WIP commit 😅. Should be good now, though.

1. fair enough, I can see you're also not relying on the link having that format in your code. 
2. this obviously makes me sad, but alright
3. alright, good!

2023-07-24 09:35 UTC, vhargrave approved these changes

2023-07-24 09:35 UTC, merged