Multiple CTAs + Hyperlinks for Fullscreen Marquee
adobecom/express pull request #1014
Opened 2024-07-16 19:47 UTC by echen-adobe

Describe your specific features or fixes

Changes the fullscreen marquee so that it detects multiple CTAs and if the CTAs are italicized transforms them into hyperlinks.

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://fullscreen-marquee-cta--express--adobecom.hlx.page/drafts/echen/flyer-copy

<img width="1194" alt="Screenshot 2024-07-16 at 12 46 00 PM" src="https://github.com/user-attachments/assets/ee17b5d8-7f35-4cb5-9e90-accdc8f46c20">

2024-07-16 21:13 UTC, fullcolorcoder requested changes
Small formatting things mostly. 

Is this to supplement the original ask in the ticket? I saw this screenshot in there. 
![image](https://github.com/user-attachments/assets/6324b703-3f4a-436f-a9d3-e0c39ed5a3fb)

Also, is it expected that the CTAs disappear on mobile?

2024-07-16 21:13 UTC, fullcolorcoder commented on express/blocks/fullscreen-marquee/fullscreen-marquee.js
> +  links
Could this be on one line?

2024-07-16 21:13 UTC, fullcolorcoder commented on express/blocks/fullscreen-marquee/fullscreen-marquee.js
> +        link.classList.remove('button')
semicolon;

2024-07-16 21:13 UTC, fullcolorcoder commented on express/blocks/fullscreen-marquee/fullscreen-marquee.js
> +        link.classList.add('hyperlink')
No test coverage for these lines.

2024-07-17 18:53 UTC, echen-adobe commented
> Small formatting things mostly.
> 
> Is this to supplement the original ask in the ticket? I saw this screenshot in there. ![image](https://private-user-images.githubusercontent.com/7562106/349275523-6324b703-3f4a-436f-a9d3-e0c39ed5a3fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNDI1NzgsIm5iZiI6MTcyMTI0MjI3OCwicGF0aCI6Ii83NTYyMTA2LzM0OTI3NTUyMy02MzI0YjcwMy0zZjRhLTQzNmYtYTlkMy1lMGMzOWVkNWEzZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTdUMTg1MTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzllZmJhYzE1OTkwNGUyMWE5YjlkMDgzZDJmOTgxNzcyMmY3M2NiMzI3NzY4MWI0NTkwMzQwNWE4MTRjYWY0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mLJqpyTW8M-9Ytsw8OxTYV-JDWwYhVa4HbUGzNvB0MU)
> 
> Also, is it expected that the CTAs disappear on mobile?

Hey Brad it is expected for the buttons to disappear on mobile because the block is designed to have an entirely different design based on the screen resolution. 

The screenshot you provided is from a different ticket.

2024-07-17 18:55 UTC, echen-adobe commented on express/blocks/fullscreen-marquee/fullscreen-marquee.js
> +  links
Line 144 is already its own thing. if you are talking about lines 144 - 156 then no, it cannot be done in a single line.

2024-07-18 15:57 UTC, fullcolorcoder approved these changes

2024-07-18 21:05 UTC, merged