ensure words do not break with hyphens on mobile
adobecom/express pull request #1029
Opened 2024-07-22 19:10 UTC by jsandland

Mobile Only - Ensure long words never wrap to an additional line split with hyphens.

Resolves: [MWPW-154516](https://jira.corp.adobe.com/browse/MWPW-154516)

Test URLs:

Before: https://main--express--adobecom.hlx.page/in/express/
After: https://mobile-line-breaks--express--adobecom.hlx.page/in/express/

2024-07-22 21:19 UTC, JingleH requested changes

2024-07-22 21:19 UTC, JingleH commented on express/scripts/scripts.js
> +(function replaceHyphensInTextNodes() {
This solution seems a bit too involved for me and I think it will miss out for dynamically fetched content. Can you look around and see if Milo already has solutions for similar challenges? I hope there exists a simpler approach

2024-07-22 21:19 UTC, JingleH commented on express/scripts/scripts.js
> +(function replaceHyphensInTextNodes() {
@vhargrave @fullcolorcoder  do you know of anything special Milo has done to keep words intact? 
![SC 2024-07-22 at 4 19 17 PM](https://github.com/user-attachments/assets/d11fbc4a-b95c-4d9e-b53e-14c3e7ec340e)

2024-07-22 22:08 UTC, jsandland commented on express/scripts/scripts.js
> +(function replaceHyphensInTextNodes() {
@JingleH The CSS will automatically handle dynamic and non-dynamic strings, ensuring that words are wrapped correctly without adding hyphens, **except for strings that actually contain a regular hyphen ("-")**. String that already contain hyphens will still cause word breaks and line wrapping because they are built into the string. However, if you want to prevent line breaks at hyphens, you need to replace them with the Unicode non-breaking hyphen (\u2011). There is an additional requirement that words like "all-in-one" should not be wrapped. This is the reason for the additional JS function.

2024-07-23 15:31 UTC, vhargrave commented on express/scripts/scripts.js
> +(function replaceHyphensInTextNodes() {
@JingleH I'm not aware of a solution for this in milo tbh, but I agree that this could probably be simplified

@jsandland could you maybe 

1. move this code to right after the decorateButtons(area) call in the utils.js
2. simplify it to something like 
```
[...area.querySelectorAll('h1, h2, h3, h4, h5, h6')]
    .filter((header) => header.textContent.includes('-'))
    .forEach((header) => header.textContent = header.textContent.replace(/-/g, '\u2011'));
```
I think that should cover the need that Orla has, but probably worth double checking.

2024-07-23 18:17 UTC, vhargrave commented on express/scripts/utils.js
> +  document.addEventListener('DOMContentLoaded', () => {
I don't think you need this mate. 
For two reasons : 
1. This event fires super fast, so by the time you're listening for it, the event is over. You can test it yourself by setting a console log or breakpoint within your event. It's never executed :)
2. The event fires once. You want this code to always be executed for fragments.

2024-07-23 21:14 UTC, jsandland commented on express/scripts/utils.js
> +  document.addEventListener('DOMContentLoaded', () => {
Thanks Victor! I tested without the eventListener and it appears to be working.

2024-07-24 08:01 UTC, vhargrave commented on express/scripts/utils.js
> +  document.addEventListener('DOMContentLoaded', () => {
sweet! 🚀

2024-07-24 08:08 UTC, vhargrave approved these changes

2024-07-24 08:08 UTC, vhargrave commented on express/styles/styles.css
> +  h1, h2 {
not sure if you want to target all header types to be on the safe side?

2024-07-24 19:51 UTC, JingleH approved these changes

2024-07-25 00:31 UTC, merged