Adds A.com georouter modal to express - DO NOT MERGE
adobecom/express pull request #1035
Opened 2024-07-25 00:30 UTC by jsandland

Adds the A.com georouter block / modal to express

Resolves: [MWPW-154379](https://jira.corp.adobe.com/browse/MWPW-154379)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://<branch>--express--adobecom.hlx.page/express/

2024-07-29 09:48 UTC, vhargrave requested changes
I like how clean the copy paste is . I'd recommend checking out the test urls you linked with something like ?akamaiLocale=CH in your URL or ?akamaiLocale=DE
For countries that have more than one locale, the georouting looks broken and things like the flags are missing. 
In addition, I don't even think that we want the georouting to even appear for countries like Switzerland, because we don't have an experience prepared for CH, but maybe we want to take users to the German experience. This is technically an authoring decision, but since georouting is so new to the authors I think they'll need dev support to get this configured right.

2024-07-29 09:48 UTC, vhargrave commented on express/scripts/scripts.js
> +  id_en: { ietf: 'en', tk: 'hah7vzn.css' },
i don't think this locale id_en needs to be added, because there's no content being created under that url.

2024-07-29 09:48 UTC, vhargrave commented on .eslintrc.js
> +    'no-return-assign': 'off',
could you make this the same as milo actually , so we're aligned ? - `'no-return-assign': ['error', 'except-parens'].`
I'd find it personally a bit confusing to see an assignment on the same line as a return statement

2024-08-05 20:38 UTC, jsandland commented
@vhargrave Regading the missing flags: 
I see a reference to the flags like this in milo:
```const flagFile = locale.globeGrid?.toLowerCase().trim() === 'on' ? 'globe-grid.png' : `flag-${locale.geo.replace('_', '-')}.svg`;```
Do those svg files live in the cloud?

2024-08-05 20:43 UTC, jsandland commented
> For countries that have more than one locale, the georouting looks broken...
I tested every `locale` in `scripts.js` and observed georouting working for every entry. I have removed `Id_en` as requested so did not test that one. However, I also tested every locale with the akamaiLocale query param and for every one of those cases the `georouter` failed to appear. Is this what you mean by broken? What is the expected behavior when the `akamaiLocale` is included? Doesn't that force akamai to serve a country specific cached page?

2024-08-08 10:25 UTC, vhargrave reviewed
Regarding what we've discussed yesterday, I've thought about it more and I think the best approach for now is to only offer georouting for the locales that we have. 
This means offering a georouting modal for German , French, US, Indian, UK, users etc. 
But not offering a modal to take the user to the German experience if we detect they're in Switzerland. 
You'll probably want to double check if this is ok, but if we do want to start offering support so Georouting appears for Switzerland , then we'll need to have a proper discussion with the georouting PdMs on requirements. 

So in summary as long as we only have entries for the locales we have in the georoutingv2.xlsx file we should be good. 

Asides from that I found two things that need to be changed, and then we should slowly be good.

2024-08-08 10:25 UTC, vhargrave commented on express/scripts/scripts.js
> -  gb: { ietf: 'en-GB', tk: 'pps7abe.css' },
why remove the gb locale?

2024-08-13 22:13 UTC, closed without merging