Interactive marquee
adobecom/express pull request #1037
Opened 2024-07-25 20:54 UTC by echen-adobe

Describe your specific features or fixes

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://<branch>--express--adobecom.hlx.page/express/

2024-08-07 19:34 UTC, fullcolorcoder approved these changes

2024-08-07 21:45 UTC, kennethlum commented on express/blocks/interactive-marquee/interactive-marquee.js
> +// [headingSize, bodySize, detailSize, titlesize]
delete this line?

2024-08-07 23:20 UTC, echen-adobe commented on express/blocks/interactive-marquee/interactive-marquee.js
> +// [headingSize, bodySize, detailSize, titlesize]
That is a comment from the original block that provides a clearer explanation of what 

`typeSizes`

in the following line means.

2024-08-12 17:18 UTC, kennethlum approved these changes

2024-08-20 21:21 UTC, JingleH requested changes
Hi @echen-adobe can you fix the unit tests? Then we can merge it to stage

2024-08-20 22:16 UTC, JingleH approved these changes

2024-08-20 22:16 UTC, merged