preserve hyphen replacement without affecting pricing cards gradient
adobecom/express pull request #1038
Opened 2024-07-25 22:02 UTC by jsandland

These changes aim to resolve the side effect seen in pricing-cards where the gradient is broken when hyphens in header elements are replaced.

Resolves: [MWPW-154516](https://jira.corp.adobe.com/browse/MWPW-154516)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://pricing-cards-hyphen--express--adobecom.hlx.page/express/

2024-07-29 23:32 UTC, fullcolorcoder commented on express/scripts/utils.js
> +}
Nit: xss security 
 ```suggestion
export function replaceHyphensInText(area) {
  [...area.querySelectorAll('h1, h2, h3, h4, h5, h6')]
    .filter((header) => header.textContent.includes('-'))
    .forEach((header) => {
      header.textContent = header.textContent.replace(/-/g, '\u2011');
    });
}
```

2024-07-29 23:38 UTC, fullcolorcoder commented
Looks pretty good. 

Side nit, not earth shattering: 
Since we're here and [this](https://github.com/adobecom/express/pull/1038/files#diff-447696fef2f9a1ad1bf8ebc06cb48b5c3c0aefa45cceea614a5b5c1c056f8dd3R2403) is popping up, you could add this to make the warning go away.
```
// eslint-disable-next-line no-console
console.log(`failed to load module for ${name}`, err);
```

2024-08-05 19:27 UTC, JingleH requested changes

2024-08-05 19:27 UTC, JingleH commented on express/blocks/columns/columns.js
> +  document.body.dataset.device === 'mobile' && replaceHyphensInText(document);
i would suggest just modifying the block's own content rather than the whole document

2024-08-06 18:20 UTC, JingleH approved these changes

2024-08-06 18:40 UTC, fullcolorcoder approved these changes

2024-08-06 19:05 UTC, merged