[MWPW-154906] Pricing Cards Credits For AI Pages
adobecom/express pull request #1047
Opened 2024-07-30 21:58 UTC by echen-adobe

Describe your specific features or fixes

Implements a new pricing cards block for AI pages. This card is a stripped down version of our pricing-cards that shows the number of free AI tokens a user can expect

Resolves:  https://jira.corp.adobe.com/browse/MWPW-154906

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://ai-page-pricing--express--adobecom.hlx.page/drafts/echen/pricing-cards-credits

2024-08-07 19:34 UTC, fullcolorcoder approved these changes

2024-08-07 21:52 UTC, kennethlum commented on test/unit/blocks/pricing-cards-credits/pricing-cards-credits.test.js
> +    expect(compareAllButtons.length === 2).to.be.true;
would this also be possible be in the form like line 47 above?

2024-08-07 21:52 UTC, kennethlum commented on express/blocks/pricing-cards-credits/pricing-cards-credits.css
> +  padding: 0px;
can be `0`?

2024-08-07 21:52 UTC, kennethlum commented on express/blocks/pricing-cards-credits/pricing-cards-credits.css
> +  margin-bottom: 0px;
can be `0`?

2024-08-07 21:52 UTC, kennethlum commented on express/blocks/pricing-cards-credits/pricing-cards-credits.css
> +    min-height: 0px;
can be `0`?

2024-08-08 21:57 UTC, JingleH requested changes

2024-08-08 21:57 UTC, JingleH commented on express/blocks/pricing-cards-credits/pricing-cards-credits.css
> +    min-width: none;
i think unset might get you what you want here?

2024-08-09 20:01 UTC, JingleH approved these changes

2024-08-20 21:20 UTC, merged