MWPW-133847 | Pricing Page Look Enhancement
adobecom/express pull request #105
Opened 2023-07-23 03:01 UTC by apganapa

Pricing Page Look Enhancement

Resolves: Visual changes needed based on https://xd.adobe.com/view/7a3503ec-976b-461f-be7a-3169a456bde1-2f66/screen/8594b075-70db-466a-907c-3bf2b57611f3/specs/

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/express/pricing
- After: https://mwpw-133847-main--express--adobecom.hlx.page/express/pricing

2023-07-24 13:21 UTC, toka1300 commented
I noticed that we are still getting the fragment error in the console even when it is rendering correctly. It seems as though square brackets are actually used to designate a fragment, which I did not know. So I guess we would have to go with another authoring designation for the text highlighting, italics?

![image](https://github.com/adobecom/express/assets/105597527/c0098f25-19c6-487c-8787-c4148f1efc11)

2023-07-24 13:59 UTC, toka1300 commented
@redvelvet511 looks like we might want to add a space after the superscript.
![image](https://github.com/adobecom/express/assets/105597527/74ca0d21-48a6-41ea-9da6-c1cb92f85ff6)

2023-07-24 14:29 UTC, toka1300 submitted a review, later dismissed

2023-07-25 14:56 UTC, redvelvet511 commented on express/blocks/puf/puf.js
> +  const $listItems = $block.querySelectorAll('.puf-list-item');
I believe so. But I would add the same code snippet on it, so maybe it's better in a separate function for readability?

2023-07-25 14:57 UTC, redvelvet511 commented
> @redvelvet511 looks like we might want to add a space after the superscript. ![image](https://user-images.githubusercontent.com/105597527/255612729-74ca0d21-48a6-41ea-9da6-c1cb92f85ff6.png)

done thanks!

2023-07-25 14:57 UTC, redvelvet511 commented
> I noticed that we are still getting the fragment error in the console even when it is rendering correctly. It seems as though square brackets are actually used to designate a fragment, which I did not know. So I guess we would have to go with another authoring designation for the text highlighting, italics?
> 
> ![image](https://user-images.githubusercontent.com/105597527/255601355-c0098f25-19c6-487c-8787-c4148f1efc11.png)

also fixed this by using parenthesis (( )) instead of [[ ]]

2023-07-25 14:58 UTC, redvelvet511 commented
> done thanks!

done thanks!

> 

done thanks!

2023-07-25 14:58 UTC, redvelvet511 commented
> I noticed that we are still getting the fragment error in the console even when it is rendering correctly. It seems as though square brackets are actually used to designate a fragment, which I did not know. So I guess we would have to go with another authoring designation for the text highlighting, italics?
> 
> ![image](https://user-images.githubusercontent.com/105597527/255601355-c0098f25-19c6-487c-8787-c4148f1efc11.png)

also fixed this by using parenthesis (( )) instead of [[ ]]

2023-07-25 19:24 UTC, redvelvet511 requested changes
Hi, I think we should add some kind of padding here so it doesn't looked to cramped

<img width="389" alt="image" src="https://github.com/adobecom/express/assets/113856982/0b5fd820-da54-43d8-9e58-703dc8b42f1f">

<img width="389" alt="image" src="https://github.com/adobecom/express/assets/113856982/d62e6e31-2b65-4047-82a2-932ac6619b5a">

2023-07-25 19:35 UTC, toka1300 commented
> Hi, I think we should add some kind of padding here so it doesn't looked to cramped
> 
> <img alt="image" width="389" src="https://user-images.githubusercontent.com/113856982/256014407-0b5fd820-da54-43d8-9e58-703dc8b42f1f.png"> <img alt="image" width="389" src="https://user-images.githubusercontent.com/113856982/256014514-d62e6e31-2b65-4047-82a2-932ac6619b5a.png">

Fixed it at the exact same time you commented haha

2023-07-25 20:08 UTC, toka1300 commented on express/blocks/puf/puf.js
> +  const $listItems = $block.querySelectorAll('.puf-list-item');
Just instead of looping through them all again, I guess I'm not entirely sure why you have to create this separate 'filteredChildren' array - aren't you wrapping all list items in that wrapper regardless?

2023-07-25 20:23 UTC, qiyundai approved these changes
approved with a small nit comment

2023-07-25 20:23 UTC, qiyundai commented on express/blocks/puf/puf.js
> +  $block.append($footer);
nit: I personally would like to group appends together.

2023-07-25 20:39 UTC, toka1300 commented on express/blocks/puf/puf.js
> +  $block.append($footer);
Done

2023-07-25 20:40 UTC, toka1300 approved these changes

2023-07-25 20:55 UTC, JingleH approved these changes

2023-07-25 20:56 UTC, merged