[Enhancement] Update Pricing Blocks Billing Toggle
adobecom/express pull request #1070
Opened 2024-08-12 20:42 UTC by echen-adobe

Describe your specific features or fixes

For Teams plans, the user is locked in for a year but the plan is paid for in monthly installments. This must be made clear when the user is looking through the pricing cards billing toggle. This change detects whether a plan is a Teams plan by looking at whether a multiple headcount parenthesis is included or not. 

Resolves: https://jira.corp.adobe.com/projects/MWPW/issues/MWPW-156088

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://additional-billing-toggle--express--adobecom.hlx.page/express/pricing

2024-08-12 22:01 UTC, JingleH requested changes
there're some lint complaints. Otherwise, can you confirm with authors and PdM that whatever has headcounts will happen to be a Teams card and whether this logic can apply in the long run?

2024-08-13 17:25 UTC, echen-adobe commented
> there're some lint complaints. Otherwise, can you confirm with authors and PdM that whatever has headcounts will happen to be a Teams card and whether this logic can apply in the long run?

I've talked with Jeanette and she said that we can assume the third card will require the special billing toggle for now. 
She also said that all Teams plans will require the new billing label.

She also said that in the long run, we may want to switch to a Milo modal system.

I've updated the PR to reflect this.

2024-08-13 21:16 UTC, JingleH approved these changes

2024-08-19 16:27 UTC, fullcolorcoder approved these changes
![image](https://github.com/user-attachments/assets/3da751ec-44de-4e36-8d87-f1c69fb229f6)
 
LGTM - Are they authoring changes before prod so there aren't a lot of gaps?

2024-08-19 16:55 UTC, merged