Sitemap action
adobecom/express pull request #1102
Opened 2024-08-27 19:59 UTC by echen-adobe

Describe your specific features or fixes

Implements a github actions workflow for rebuilding the staging sitemap when a PR is made. This action should help detect issues related to sitemap configs in the future.

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://sitemap-action--express--adobecom.hlx.page/express/

2024-09-03 21:13 UTC, fullcolorcoder commented on test/helpers/sitemap.js
> +        console.error(`Error: ${url}`, response.statusText);
Can you /* eslint-disable these console.log() lines

2024-09-03 21:25 UTC, fullcolorcoder requested changes
- Is there a ticket for this 
- What are your testing instructions?

2024-09-05 21:05 UTC, JingleH requested changes

2024-09-05 21:05 UTC, JingleH commented on test/helpers/sitemap.js
> +  for await (const url of urls) {
once we have added the other urls, maybe do promise.all/allSettled to have them run in parallel and save us some Action time?

2024-09-05 21:05 UTC, JingleH commented on test/helpers/sitemap.js
> +makeRequests();
sometimes this way can generate some UnhandledPromiseRejection warning. Using main().catch(console.error()) might be safer

2024-09-05 22:35 UTC, echen-adobe commented on test/helpers/sitemap.js
> +  const baseURL = 'https://admin.hlx.page/sitemap/adobecom/express/stage/';
I think it should support it in theory, but in practice the main sitemaps are always the ones updated.

2024-09-10 17:55 UTC, fullcolorcoder approved these changes

2024-09-25 17:28 UTC, JingleH approved these changes
also uploaded the secrets for now

2024-09-26 17:32 UTC, merged