[Intl. Express] JP | New Table of Contents SEO Page Block
adobecom/express pull request #1106
Opened 2024-08-28 23:30 UTC by jsandland

Adds a sticky desktop table of contents (TOC) that auto-populates from authored document links for easy navigation between page headers. On mobile, the TOC is positioned above each linked header and is not sticky.
Feel free to copy the word doc in my sharepoint drafts folder to see how this is currently set up.

Resolves: [MWPW-153766](https://jira.corp.adobe.com/browse/MWPW-153766)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://updated-toc-jp--express--adobecom.hlx.page/drafts/jsandlan/flyer

2024-08-29 14:58 UTC, fullcolorcoder requested changes

2024-08-30 17:13 UTC, JingleH commented on express/blocks/table-of-contents-seo/table-of-contents-seo.js
> +function setBoldStyle(element, isBold) {
nit and super controversial take: using boolean as functions' parameters can be controversial according to Uncle Bob (https://youtu.be/2Q9GRPxqCAk). We can either pass the string or split the function into setBoldStyle and setNormalStyle or not extracting it to reduce 1 level of function call. But it's fine to leave as it is so up to you

2024-08-30 17:14 UTC, JingleH commented on express/blocks/table-of-contents-seo/table-of-contents-seo.js
> +  let deviceType = window.innerWidth >= MOBILE_SIZE ? 'DESKTOP' : 'MOBILE';
nit: resize listeners can fire very frequently. So either debounce it or use window.matchMedia to capture the desktop/mobile switch

2024-08-30 17:15 UTC, JingleH commented on express/blocks/table-of-contents-seo/table-of-contents-seo.js
> +  checkIcon.style.width = '18px';
nit: i think these 2 lines can be combined into 1 like style = 'width:18px;height:18px' to save some bytes(?) but it might be less readable(?)

2024-08-30 17:16 UTC, JingleH commented on express/blocks/table-of-contents-seo/table-of-contents-seo.js
> +  tocTitle.appendChild(document.createTextNode(title));
maybe using append() we can combine these 2 into 1 line again!

2024-08-30 17:19 UTC, JingleH commented on express/blocks/table-of-contents-seo/table-of-contents-seo.js
> +  return Array.from(doc.querySelectorAll('main h2, main h3, main h4'))
i wonder if `'main :is(h2, h3, h4)'` can work too and if so again we get some bytes back

2024-08-30 17:20 UTC, JingleH commented on express/blocks/table-of-contents-seo/table-of-contents-seo.js
> +function handleTOCCloningForMobile(toc, tocEntries) {
i think this semantic encourages us to think "Desktop first" and handle mobile as edge cases, while we should really think about things from the opposite way. Maybe by default do things for mobile, and handle desktop as a special case

2024-08-30 17:22 UTC, JingleH commented on express/blocks/table-of-contents-seo/table-of-contents-seo.js
> +    tocContainer.style.display = 'none';
again, maybe think mobile first, so its hidden by default, but shown on desktop

2024-09-03 14:12 UTC, fullcolorcoder commented
Since this is a new block, can you include the link to documentation before we ship?

2024-09-03 17:37 UTC, JingleH approved these changes

2024-09-03 21:39 UTC, fullcolorcoder requested changes
- Small best practice nit
- I don't see usage docs

2024-09-03 21:39 UTC, fullcolorcoder commented on express/features/table-of-contents-seo/table-of-contents-seo.js
> +  element.querySelector('.toc-number').style.fontWeight = 'bold';
Adding a utility class is best practice here.

2024-09-03 23:33 UTC, echen-adobe approved these changes

2024-09-03 23:49 UTC, merged