fix scroll bug
adobecom/express pull request #1117
Opened 2024-09-04 17:55 UTC by jsandland

There is a bug that prevents the table of contents link from scrolling the user to some included links. This resolves that issue.

No ticket.

If fixing a bug, steps to reproduce the bug:
When you click the first link in table of contents on desktop the browser fails to navigate the user to the correct header.

Test URLs:

- Before: https://updated-toc-jp--express--adobecom.hlx.page/drafts/jsandlan/long-form-flyer (changes currently on stage)
- After: https://fix-scroll-bug-toc--express--adobecom.hlx.page/drafts/jsandlan/long-form-flyer

2024-09-04 19:20 UTC, fullcolorcoder requested changes

2024-09-04 19:20 UTC, fullcolorcoder commented on express/features/table-of-contents-seo/table-of-contents-seo.css
> +  background-color: #f4f4f4 !important;
!important isn't needed.

2024-09-04 19:22 UTC, JingleH requested changes

2024-09-04 19:22 UTC, JingleH commented on express/features/table-of-contents-seo/table-of-contents-seo.css
> +  background-color: #f4f4f4 !important;
i think we are trying to avoid using !important, so see if you can make the rule more specific to win over other contenders of background color

2024-09-04 19:22 UTC, JingleH commented on express/features/table-of-contents-seo/table-of-contents-seo.js
> +      window.scrollTo({ top: offsetPosition, behavior: 'smooth' });
I think using header.scrollTo() could be more intuitive than window.scrollTo(). You can also pass offset more easily that way

2024-09-04 19:23 UTC, JingleH commented on express/features/table-of-contents-seo/table-of-contents-seo.css
> +  background-color: #f4f4f4 !important;
looks like we posted the same time lol

2024-09-05 15:31 UTC, jsandland commented on express/features/table-of-contents-seo/table-of-contents-seo.css
> +  background-color: #f4f4f4 !important;
Left this in by mistake :)

2024-09-05 15:32 UTC, jsandland commented on express/features/table-of-contents-seo/table-of-contents-seo.css
> +  background-color: #f4f4f4 !important;
Yeah, I'd never let !important get to production. It's too hacky.

2024-09-05 15:32 UTC, jsandland commented on express/features/table-of-contents-seo/table-of-contents-seo.js
> +      window.scrollTo({ top: offsetPosition, behavior: 'smooth' });
Taking a look.

2024-09-05 15:56 UTC, jsandland commented on express/features/table-of-contents-seo/table-of-contents-seo.js
> +      window.scrollTo({ top: offsetPosition, behavior: 'smooth' });
header.scrollTo() won't work in the way you might expect because the scrollTo method is intended for scrolling the content of a scrollable element (like a div with overflow: scroll), not for scrolling the entire page to a specific element's position, which is the case here. There is header.scrollIntoView but that does not accept an offset, which is required to account for the height of the header when the user gets scrolled to the clicked table of content link.

2024-09-05 16:30 UTC, fullcolorcoder approved these changes

2024-09-05 16:54 UTC, JingleH approved these changes

2024-09-05 18:25 UTC, merged