JP Express Long Form
adobecom/express pull request #1124
Opened 2024-09-05 20:08 UTC by jsandland

2024-09-10 17:10 UTC, JingleH requested changes

2024-09-10 17:10 UTC, JingleH commented on express/blocks/columns/columns.js
> +  const container = document.querySelector('div.columns.block');
similar to the one above, these query selectors will only pick the first block. Is this intentional?

2024-09-10 17:10 UTC, JingleH commented on express/blocks/columns/columns.js
> +  const narrowWidth = getMetadata('narrow-width') === 'on';
i am thinking that instead of using a page-level metadata and ask individual blocks to decorate itself with a new class, would it be more natural to author individual blocks with a narrow-width variant?

2024-09-10 17:10 UTC, JingleH commented on express/blocks/columns/columns.js
> +        const headers = ele.querySelectorAll('h2');
these 2 lines can be combined to avoid an innerHTML scan. you can use the querySelector first and check if the result is empty

2024-09-10 17:10 UTC, JingleH commented on express/scripts/utils.js
> +        const headers = container.querySelectorAll('h1'); // Select all header elements
i'm wondering if this can be done via creating a new section-metadata?

2024-09-10 17:37 UTC, jsandland commented on express/blocks/columns/columns.js
> +  const container = document.querySelector('div.columns.block');
Yes

2024-09-10 22:13 UTC, fullcolorcoder requested changes

2024-09-10 22:13 UTC, fullcolorcoder commented on express/blocks/how-to-steps/how-to-steps.css
> +main .how-to-steps.inline-tip.narrow-mobile-width .tip .tip-number {
Since this is identical, can you combine it with the above definition

2024-09-10 22:13 UTC, fullcolorcoder commented on express/blocks/how-to-steps/how-to-steps.css
> +  max-width: 'none';
`none` not `'none'`

2024-09-11 15:38 UTC, JingleH requested changes

2024-09-11 15:38 UTC, JingleH commented on express/blocks/columns/columns.js
> +  if (container?.classList.contains('narrow')) {
if we only want the first columns block to run this logic, it would be better to ask the current columns block to check if it is the first columns block, rather than every columns block on the page run this logic repeatedly for the first columns block

2024-09-11 15:38 UTC, JingleH commented on express/scripts/utils.js
> +
can you remove this line so that it won't be modified? People usually are more nervous when utils.js gets touched

2024-09-11 15:38 UTC, JingleH commented on express/blocks/how-to-steps/how-to-steps.js
> +    $number.innerHTML = `<span>${i + numberStepStart - 1}</span>`;
nit: i think this line can be combined with its earlier line using createTag()'s third parameter

2024-09-11 22:11 UTC, jsandland commented on express/blocks/columns/columns.js
> +  if (container?.classList.contains('narrow')) {
I checked this by adding another columns block to the page and any new instance starts over being numbered at 1 - n. I think this is the expected behavior. Does that change this ask?

2024-09-18 15:44 UTC, JingleH requested changes
except the container one, i think this one is almost ready!

2024-09-18 15:44 UTC, JingleH commented on express/blocks/how-to-steps/how-to-steps.css
> +main .how-to-steps-inline-tip-narrow-container .how-to-steps.narrow {
sorry i just recognized this. Is it possible to style things without using the container? Reasons being that those "container" is not in Milo, and they tend to be very fragile if you look at decorateBlock of utils and notice how the order and adding/removing of  variants can break styles like this

2024-09-18 22:15 UTC, JingleH approved these changes
a lot of new variants for a lot of blocks! It'll be best if they are all documented in the block documentations

2024-09-19 17:34 UTC, fullcolorcoder approved these changes

2024-09-19 17:40 UTC, merged