Fix Template-X Toolbar Sticky behavior
adobecom/express pull request #1133
Opened 2024-09-12 22:47 UTC by JingleH

**Fixes following issues|Adds following features:**
- Fix Sticky Toolbar covered by Nav
- Minor update for search tracking for search-marquee block

**Resolves:** https://jira.corp.adobe.com/browse/MWPW-158373

**Steps to test the before vs. after and expectations:**
- Scroll down on a template page
![SC 2024-09-12 at 3 45 36 PM](https://github.com/user-attachments/assets/e12fdc5c-54a9-474c-9067-9d02e89e6a3d)
- In the branch link, it should be sticky and reserve space for the Nav. In stage or prod, it will be covered and no longer visible.

**Pages to check for regression and performance:**
- https://template-sticky-fix--express--adobecom.hlx.page/express/?martech=off

2024-09-12 23:10 UTC, echen-adobe requested changes
There is a bit of a gap between the nav and the toolbar on desktop

<img width="1783" alt="Screenshot 2024-09-12 at 4 09 27 PM" src="https://github.com/user-attachments/assets/b2439ded-121d-43ba-80c7-ca16726863ab">

2024-09-12 23:13 UTC, JingleH commented
> There is a bit of a gap between the nav and the toolbar on desktop
> 
> <img alt="Screenshot 2024-09-12 at 4 09 27 PM" width="1783" src="https://private-user-images.githubusercontent.com/159481679/367090684-b2439ded-121d-43ba-80c7-ca16726863ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxODI5NTUsIm5iZiI6MTcyNjE4MjY1NSwicGF0aCI6Ii8xNTk0ODE2NzkvMzY3MDkwNjg0LWIyNDM5ZGVkLTEyMWQtNDNiYS04MGM3LWNhMTY3MjY4NjNhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQyMzEwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjVjNzM1YzYyNzM2MDg3YzI2ZTQ0MTJlYTJjMWFiMmM0NmI5NjkwOGJlMDk0M2ViMDhmMGUyNTY3MTExNDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ic6XfbS_-Q9JKelYieMRpzJa9R_-A1ap-Xzl3BmxxLo">

good catch! Looks like our new Nav is no longer 65 px by 64px. We'll need to update the global value in styles.css after all locales get the new Nav. @echen-adobe updated the css

2024-09-12 23:19 UTC, echen-adobe approved these changes
Looks good to me on .page

2024-09-12 23:20 UTC, echen-adobe requested changes
Think there is an issue with scrolling on mobile as well.

<img width="846" alt="Screenshot 2024-09-12 at 4 19 30 PM" src="https://github.com/user-attachments/assets/7563c827-ed4b-4811-8f6f-0711511c07ae">

2024-09-13 20:46 UTC, echen-adobe approved these changes

2024-09-16 16:15 UTC, qiyundai commented on express/blocks/search-marquee/search-marquee.js
> +      trendLink.addEventListener('click', () => {
Should we quickly add this too? Since it's tabbable

trendLink.addEventListener('keydown', async (e) => {
  if (e.key === 'Enter' || e.keyCode === 13) {
    updateImpressionCache({
      keyword_filter: key,
      content_category: 'templates',
    });
    trackSearch('search-inspire', new URLSearchParams(new URL(trendLink.href).search).get('searchId'));
  }
});

2024-09-16 16:16 UTC, qiyundai approved these changes
LGTM! Added one non-blocking comment.

2024-09-16 20:36 UTC, JingleH commented on express/blocks/search-marquee/search-marquee.js
> +      trendLink.addEventListener('click', () => {
found some resources so we're good!

2024-09-16 20:36 UTC, merged