[MWPW-133254] Pricing Summary Test
adobecom/express pull request #114
Opened 2023-07-25 01:09 UTC by redvelvet511

**Description**
- Add integration test
- Add missing "/" in the web-config file
-

2023-07-25 14:41 UTC, apganapa approved these changes

2023-07-25 15:48 UTC, qiyundai requested changes

2023-07-25 15:48 UTC, qiyundai commented on test/blocks/pricing-summary/pricing-summary.test.js
> +  it('Columns have correct elements', () =>{
Among all the undef errors, this =>{ thingy is probably still worth fixing

2023-07-31 15:31 UTC, qiyundai approved these changes

2023-07-31 20:11 UTC, vhargrave approved these changes
looks good!

2023-07-31 20:11 UTC, merged