Simplified pricing cards
adobecom/express pull request #1141
Opened 2024-09-17 21:03 UTC by echen-adobe

**Fixes following issues|Adds following features:**
- Issue/Feature 1

**Resolves:** [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

**Steps to test the before vs. after and expectations:**
- Steps for feature 1

**Pages to check for regression and performance:**
- https://<branch>--express--adobecom.hlx.page/express/?martech=off

2024-09-24 15:56 UTC, kennethlum commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +}
may want to throttle the resize handler?

2024-09-24 16:19 UTC, JingleH requested changes

2024-09-24 16:19 UTC, JingleH commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.css
> +@media (max-width: 1024px) {
we'll need to build the new blocks mobile first rather than desktop first

2024-09-24 21:42 UTC, echen-adobe commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.css
> +@media (max-width: 1024px) {
Reformatted for mobile first CSS just now

2024-09-24 21:47 UTC, echen-adobe commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +}
Its throttled by 100 seconds now.

The goal is not to make the cards the same height, but to make each section within the card the same height as all sibling sections.

2024-09-24 22:04 UTC, fullcolorcoder requested changes
Pretty solid. A few small nits for Milo. 

One other thing I notice, under 600 there is an accordion behavior suggested in the UI but no expand/contract action happens. In the screenshot you can see one is open and the other closed but both are open.

![image](https://github.com/user-attachments/assets/e3f35087-827d-4027-a271-8ee4040d5c5f)

2024-09-24 22:04 UTC, fullcolorcoder commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.css
> +  padding-bottom: 48px;
Please import the relevant vars from Milo into our styles.css 

https://github.com/adobecom/milo/blob/stage/libs/styles/styles.css

This for example would be   --spacing-xl: 48px;

2024-09-24 22:04 UTC, fullcolorcoder commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.css
> +  background-color: white;
This would be --color-white: #FFF; after importing the var from Milo.

2024-09-24 22:12 UTC, JingleH requested changes
i know we've already demoed to authors, but regarding card header, i think as a mobile-first practice, the default one should be for mobile, with desktop one following.

2024-09-24 22:12 UTC, JingleH commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +  document.querySelectorAll('.card').forEach((column) => {
this will affect other blocks where their elements also have .card classes right?

2024-09-24 22:12 UTC, JingleH commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +  window.addEventListener('load', () => equalizeHeights(el), 100);
i feel like this load event might not be needed. Can you confirm once?

2024-09-24 22:12 UTC, JingleH commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +  window.addEventListener('resize', () => equalizeHeights(el), 100);
if we go with the resize route, it would be better to throttle it

2024-09-24 22:12 UTC, JingleH commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +    await createPricingSection(placeholders, rows[3].children[0],
nit: unless each card depends on other cards, can we parallelize this?

2024-09-24 22:21 UTC, kennethlum commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +}
oh you mean 100ms?  Can you add `100` as the 3rd argument for addEventLister() and it will work, coz I checked the MDN docs and it didn't have that.  Would it require like the `throttle()` in `express/scripts/hofs.js` ?

2024-09-24 22:28 UTC, echen-adobe commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +    await createPricingSection(placeholders, rows[3].children[0],
There are some weird interactions with the height syncing if it happens too quickly, so I am not inclined to pursue this optimization right now.

2024-09-24 22:39 UTC, echen-adobe commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +  window.addEventListener('load', () => equalizeHeights(el), 100);
yea, wasnt needed. removed

2024-09-24 22:41 UTC, echen-adobe commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +  window.addEventListener('resize', () => equalizeHeights(el), 100);
I don't think that is necessary since the end user is not going to be dragging the inspector everywhere. They will at most switch the tablet / mobile device layout

2024-09-24 22:50 UTC, echen-adobe commented
> Pretty solid. A few small nits for Milo.
> 
> One other thing I notice, under 600 there is an accordion behavior suggested in the UI but no expand/contract action happens. In the screenshot you can see one is open and the other closed but both are open.
> 
> ![image](https://private-user-images.githubusercontent.com/7562106/370483606-e3f35087-827d-4027-a271-8ee4040d5c5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMTY1NzcsIm5iZiI6MTcyNzIxNjI3NywicGF0aCI6Ii83NTYyMTA2LzM3MDQ4MzYwNi1lM2YzNTA4Ny04MjdkLTQwMjctYTI3MS04ZWU0MDQwZDVjNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMjIxNzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Y5YjczMzc0NDg2MWI1NDgxYzRiZGVlOTA4ZTUxODc4N2ZiNzA1ZTQyNTdmNmUyM2IyOWU1OTI5NDg5MTkyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OMXyrZYQGgV5muE3U6tTS8HalJXvc9PHsagx-vNPG6I)

Hey Brad, I think I discovered that issue a few minutes after re-requesting the review. I've fixed it just now and imported the milo variables

2024-09-24 22:50 UTC, echen-adobe commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +  document.querySelectorAll('.card').forEach((column) => {
yup, made it more specific just now

2024-09-24 22:51 UTC, echen-adobe commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.css
> +  padding-bottom: 48px;
Added this and many other variables just now

2024-09-24 22:51 UTC, echen-adobe commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +  window.addEventListener('load', () => equalizeHeights(el), 100);
removed

2024-09-24 22:53 UTC, echen-adobe commented on express/blocks/simplified-pricing-cards/simplified-pricing-cards.js
> +}
Added it just now

2024-09-25 14:27 UTC, fullcolorcoder approved these changes
Nice!

2024-09-25 20:47 UTC, merged