cards homepage redesign
adobecom/express pull request #1153
Opened 2024-09-23 21:23 UTC by jsandland

**Fixes following issues|Adds following features:**
- Adds new cards for homepage redesign

**Resolves:** [MWPW-158234](https://jira.corp.adobe.com/browse/MWPW-158234)

**Pages to check for regression and performance:**
- https://cards-homepage-redesign--express--adobecom.hlx.page/express/?martech=off

2024-09-23 23:45 UTC, echen-adobe requested changes

2024-09-23 23:45 UTC, echen-adobe commented on express/blocks/discover-cards/discover-cards.js
> +  } else if (subHeader) {
Can these be done via assigning a CSS class instead?

2024-09-23 23:45 UTC, echen-adobe commented on express/blocks/discover-cards/discover-cards.js
> +      parentElement.appendChild(circleContainer);
Is this approach shared by Kenneth and Jingle? Additionally, wouldn't uploading an image be more future proof?

2024-09-23 23:45 UTC, echen-adobe commented on express/blocks/discover-cards/discover-cards.css
> +.card div {
Why are these CSS classes not scoped to discover-cards?

2024-09-24 19:21 UTC, fullcolorcoder requested changes

2024-09-24 19:21 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    url(/express/img/cards-bg-large.png);
This is having an impact on performance I think, and isn't changeable by authors. Alternatively, we could wait for DOM content to load before setting this so that it's not required to be loaded up front.

2024-09-24 19:21 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    border: 1px solid black;
Please check out this file: https://github.com/adobecom/milo/blob/stage/libs/styles/styles.css

- Look for variables that cover the values you have in CSS in this file
- Pull the variables that do from Milo into our styles.css 
- Use them 

This will make things so much cleaner in the future, as we're already piling on when building new blocks this way.

2024-09-24 19:26 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.js
> +        textBody.classList.add('small-text-content');
You added a class `small-text-content` why not have font-weight,  size, alignment, etc in that class?

2024-09-24 19:30 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    max-width: none;
Does this need to be here? If not remove.

2024-09-24 19:30 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    max-width: none;
Same for this.

2024-09-24 19:32 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    min-width: 399px;
This is problematic and cuts off on smaller screen sizes. 
![image](https://github.com/user-attachments/assets/68a6307f-12c3-416d-b514-ac3cd07d3ce8)

2024-09-24 19:33 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    margin-top: 10px;
Condense to one line for margin, especially in new blocks where there is no potential regressions.

2024-09-24 19:34 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    margin-left: auto;
One liner

2024-09-24 19:34 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    margin-top: 0px;
One liner

2024-09-24 19:34 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    margin-top: 5px;
One liner

2024-09-24 19:34 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    margin-left: auto;
One liner

2024-09-24 19:35 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    margin-top: 12px;
One liner, and odd to break them up between other definitions.

2024-09-24 20:28 UTC, jsandland commented on express/blocks/discover-cards/discover-cards.css
> +    min-width: 399px;
I should have added a "do not merge" label - I've been progressively making changes.

2024-09-24 20:30 UTC, jsandland commented on express/blocks/discover-cards/discover-cards.css
> +    url(/express/img/cards-bg-large.png);
The way this linear gradient is lightweight and not computationally heavy. It's just a transition between two colors (transparent to white).

2024-09-24 20:57 UTC, jsandland commented on express/blocks/discover-cards/discover-cards.js
> +    class: 'cards-container',
This pattern is already being used. Why should a container not be used? It appears to be how the gallery is constructed: https://github.com/adobecom/express/blob/stage/express/blocks/how-to-cards/how-to-cards.js#L58

2024-09-24 21:33 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.js
> +    class: 'cards-container',
This creates mounting tech debt and will be undone in the future.

2024-09-24 21:36 UTC, JingleH commented on express/blocks/discover-cards/discover-cards.js
> +    class: 'cards-container',
i think it's the block container (wrapper) class will be deprecated, but individual containers we created inside blocks shouldn't be affected by Milo right? We can name the "container" differently too

2024-09-24 21:36 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.css
> +    url(/express/img/cards-bg-large.png);
The image. This slows down LCP, and isn't changeable to the author. I was saying, you could add it when the dom is loaded instead of blocking LCP with the image as a forced load requirement.

2024-09-24 21:39 UTC, fullcolorcoder commented on express/blocks/discover-cards/discover-cards.js
> +    class: 'cards-container',
@JingleH this is what I'm referring to. 
![image](https://github.com/user-attachments/assets/c8d65b95-0f88-428f-8ef9-a0fad8109dd9)

2024-09-24 21:40 UTC, JingleH commented
if the hardcoded images (non-authorable) are specific to this block, let's maybe move it inside the block's own folder rather than the global img folder

2024-09-24 21:45 UTC, jsandland commented on express/blocks/discover-cards/discover-cards.js
> +    class: 'cards-container',
ty

2024-09-24 22:00 UTC, JingleH requested changes

2024-09-24 22:00 UTC, JingleH commented on express/blocks/discover-cards/discover-cards.js
> +  await buildGallery(cards, cardsWrapper);
Hi @jsandland , i think i've figured out why your gallery doesn't work properly. In your example there are 6 cards in total, but if you breakpoint here, you'll see that your cards contain 7 elements, with the first one never "observable"

2024-09-25 16:10 UTC, JingleH requested changes

2024-09-25 20:39 UTC, echen-adobe approved these changes

2024-09-25 20:39 UTC, merged