[New Homepage] Banner cool variant
adobecom/express pull request #1155
Opened 2024-09-24 11:00 UTC by kennethlum

**Fixes following issues|Adds following features:**
- New Homepage, Banner new variant

**Resolves:** [MWPW-158237](https://jira.corp.adobe.com/browse/MWPW-158237)

**Steps to test the before vs. after and expectations:**
- https://banner-variant-cool-before--express--adobecom.hlx.page/drafts/kennethlum/try-banner-cool?martech=off&lighthouse=on
- 
**Pages to check for regression and performance:**
- https://banner-variant-cool-after--express--adobecom.hlx.page/drafts/kennethlum/try-banner-cool?martech=off&lighthouse=on

2024-09-24 19:49 UTC, fullcolorcoder requested changes

2024-09-24 19:49 UTC, fullcolorcoder commented on express/blocks/banner/banner.css
> +main div:has(> .banner.cool) {
:has is not supported in IE, and this is an expensive query performance wise in CSS. Move these styles to `banner cool block` - which is the div just under what you want to be styling. It can remain empty and with no padding/margin to achieve the same thing.

2024-09-24 19:49 UTC, fullcolorcoder commented on express/blocks/banner/banner.js
> +    addIntermediateContainer(block, 'cool-container');
No `cool-container` please.

2024-09-24 21:01 UTC, kennethlum commented on express/blocks/banner/banner.js
> +    addIntermediateContainer(block, 'cool-container');
this one is not the one from Franklin but rather, an additional container added for the variant in the code

2024-09-24 21:06 UTC, kennethlum commented on express/blocks/banner/banner.css
> +main div:has(> .banner.cool) {
this one we may have to check how to target it. It is to target `banner-cool-container`, and as Victor mentioned, don't use
1. *-container which is the outside container
2. `.block`
so in one PR, he was mentioning to target the container such as `banner-cool-container`, use the `:has()` so that it is like, target this element, which is the direct parent of such and such element with the class of _____

2024-09-24 21:35 UTC, fullcolorcoder commented on express/blocks/banner/banner.css
> +main div:has(> .banner.cool) {
@kennethlum you have `banner cool block` on that div, and that could be used to both select and style this instead of the container issue. 

![image](https://github.com/user-attachments/assets/265f7cdb-4a9e-41cf-a61f-7c54082a5df3)

2024-09-25 19:19 UTC, fullcolorcoder approved these changes
@kennethlum given where we are timing wise I think we can ship as is and revisit the container topic in the next one.

2024-09-25 21:36 UTC, echen-adobe approved these changes

2024-09-25 21:38 UTC, merged