[MWPW-159048] Light Colored Primary CTA For Marquee
adobecom/express pull request #1166
Opened 2024-09-26 18:04 UTC by echen-adobe

**Fixes following issues|Adds following features:**
- Issue/Feature 1
- Adds light colored primary CTA to the marquee block for visual accessibility request.

**Resolves:** https://jira.corp.adobe.com/browse/MWPW-159048

**Steps to test the before vs. after and expectations:**
- Steps for feature 1
   View the preview page and verify that the desktop version of the page has no visible graphical errors. 

<img width="1299" alt="Screenshot 2024-09-26 at 11 00 12 AM" src="https://github.com/user-attachments/assets/53babbf0-4222-49a8-8cd5-5edb58039417">

**Pages to check for regression and performance:**
https://marquee-light-buttons--express--adobecom.hlx.page/drafts/echen/index-copy-1

2024-09-26 18:20 UTC, JingleH requested changes

2024-09-26 18:20 UTC, JingleH commented on express/blocks/marquee/marquee.css
> +  background: var(--color-white);
for absolute color values maybe it's easier to just use them as black and white

2024-09-26 18:20 UTC, JingleH commented on express/blocks/marquee/marquee.css
> +.marquee.light-primary-cta a.button.primaryCTA {
you probably would want to target the entitled variant

2024-09-26 20:12 UTC, echen-adobe commented on express/blocks/marquee/marquee.css
> +.marquee.light-primary-cta a.button.primaryCTA {
Not sure why, since the ticket requested the _ability_ to change the CTA color, targeting the entitled variant would remove that flexibility.

2024-09-27 14:35 UTC, fullcolorcoder requested changes

2024-09-27 14:35 UTC, fullcolorcoder commented on express/blocks/marquee/marquee.css
> +  --color-white: #FFF;
The intention of my ask with use of Milo vars here, is to include them into the styles.css and make them available to the entire project.

https://github.com/adobecom/milo/blob/stage/libs/styles/styles.css

Here you see them being added to :root {} so they're everywhere 

This belongs in style.css if it's not there already.

2024-09-30 16:01 UTC, JingleH approved these changes

2024-09-30 18:09 UTC, echen-adobe commented on express/blocks/marquee/marquee.css
> +  --color-white: #FFF;
Hey Brad, looks like the color variables are already on styles.css, so we are good here. I've removed the vars from the block stylesheet.

2024-09-30 18:11 UTC, fullcolorcoder approved these changes

2024-09-30 20:28 UTC, merged