mothers-day desktop initial commit
adobecom/express pull request #1186
Opened 2024-10-01 18:49 UTC by jsandland

**Fixes following issues|Adds following features:**
- Implements a new Mother's Day Discover Page

**Resolves:** [MWPW-157312](https://jira.corp.adobe.com/browse/MWPW-157312)

**Pages to check for regression and performance:**
- https://m-day--express--adobecom.hlx.page/drafts/jsandlan/mothers-day

2024-11-04 20:36 UTC, JingleH requested changes
For a test, I feel like a lot of the changes seem to be too disruptive, especially the ones that involve updating the current carousel. If we want to do things this way, we need to QA thoroughly on almost every page for regression. Otherwise, I recommend cloning the modified blocks and their dependencies, keep them in a test/experiment folder, and update those. Ideally test code should be well contained, and should be able to get rolled out and reverted without modifying and risking regression on the trunk of the repo.

2024-11-04 20:36 UTC, JingleH commented on express/blocks/shared/carousel.js
> +    const isMobileCenteredCarousel = document.querySelectorAll('.template-x.four-templates');
wouldn't this always be truthy since it can return an empty array?

2024-11-04 20:36 UTC, JingleH commented on express/styles/styles.css
> +main .section.content-group {
is this content-group a new pattern we will use?

2024-11-12 23:54 UTC, JingleH commented on express/blocks/link-list/link-list.css
> +  margin-top: 0px;
just a nit that we can use 0 here, but non-blocking

2024-11-12 23:54 UTC, JingleH approved these changes

2024-11-12 23:56 UTC, JingleH commented on express/blocks/how-to-steps/how-to-steps.js
> +      const number = createTag('div', { class: 'tip-number' }, `<span>${numberStepStart ? i + numberStepStart : i + 1}</span>`);
can simplify as i + (numberStepStart || 1)

2024-11-13 17:54 UTC, echen-adobe approved these changes

2024-11-13 18:04 UTC, merged