[MWPW 133847] Pricing Page Follow-Up Items
adobecom/express pull request #120
Opened 2023-07-27 15:34 UTC by toka1300

Made several visual updates that you will notice between the two when switching between different size viewports. Also fixed unclickable CTA on the left card.

Fix: https://jira.corp.adobe.com/browse/MWPW-133847
[XD](https://xd.adobe.com/view/7a3503ec-976b-461f-be7a-3169a456bde1-2f66/screen/8594b075-70db-466a-907c-3bf2b57611f3/)

Test URLs:
- Before: https://www.stage.adobe.com/express/pricing
- After: https://mwpw-133847-3--express--adobecom.hlx.page/express/pricing?lighthouse=on

2023-07-27 16:29 UTC, apganapa approved these changes

2023-07-27 17:30 UTC, qiyundai requested changes

2023-07-27 17:30 UTC, qiyundai commented on express/blocks/puf/puf.css
> +  margin-top: 100vh;
Reconsider this change? I'm seeing the carousel being way off to the bottom here now.
![Screen Shot 2023-07-27 at 12 27 57 PM](https://github.com/adobecom/express/assets/57737624/445da902-e422-405d-ba0f-5f65248a78c3)

2023-07-27 17:30 UTC, qiyundai commented on express/blocks/puf/puf.css
> +
I might consolidate the next 2 line with these.

2023-07-27 17:30 UTC, qiyundai commented on express/blocks/puf/puf.js
> +    if (!$leftCard || !$rightCard || !Object.keys(window.pricingPlans).length) {
It'll work technically because the 3rd condition always happens before the first 2 but logically I think this should be && for all.

2023-07-27 18:57 UTC, toka1300 commented on express/blocks/puf/puf.css
> +  margin-top: 100vh;
Whoops, meant to just change it to 50vh... Fixed

2023-07-27 19:00 UTC, toka1300 commented on express/blocks/puf/puf.css
> +
Done

2023-07-27 20:40 UTC, toka1300 commented on express/blocks/puf/puf.js
> +    if (!$leftCard || !$rightCard || !Object.keys(window.pricingPlans).length) {
Fixed and reversed for clarity

2023-07-27 21:29 UTC, qiyundai requested changes
Most look good now. Some last remaining small nits

2023-07-27 21:29 UTC, qiyundai commented on express/blocks/puf/puf.js
> +    const priceSet = $block.querySelector('.puf-card-top h2').textContent;
Does it not work when you query for .puf-pricing-header? it's unlikely this gets changes but if an author put some other content inside the card top row that's also h2, this would return truthy when you don't want it to.

2023-07-27 21:29 UTC, qiyundai commented on express/blocks/puf/puf.js
> +    const priceSet = $block.querySelector('.puf-card-top h2').textContent;
You could also move this to line 330 and follow the format like how $leftCard and $rightCard are checked in if and updated in else. Would be in better uniform and easier for future devs on this block to understand.

2023-07-28 13:33 UTC, toka1300 commented on express/blocks/puf/puf.js
> +    const priceSet = $block.querySelector('.puf-card-top h2').textContent;
Oh ya, makes way more sense to select on the class. 

Ya, more uniform, but those variables are also being used elsewhere in the updatePufCarousel, and will have to look for that variable twice instead of once now. But I trust your judgement, I've made the update.

2023-07-29 03:16 UTC, qiyundai approved these changes

2023-07-29 03:17 UTC, merged