Table of Contents SEO Updates
adobecom/express pull request #1209
Opened 2024-10-14 22:34 UTC by jsandland

**Fixes following issues|Adds following features:**
- Resolve bug where how to steps starts at 2 instead of 1
- Add chevron / toggle chevron up and down to mobile toc
- Make Table Of Contents sticky on mobile and positioned just below the nav
- Allow Authors to use short hand titles for the table of contents
- Allow Authors to control whether numbers are shown for each header corresponding to each table of contents link

**Resolves:** [MWPW-160248](https://jira.corp.adobe.com/browse/MWPW-160248)

**Steps to test the before vs. after and expectations:**
- Resolve bug where how to steps starts at 2 instead of 1
**Before**
<img width="1171" alt="how-to-steps-before" src="https://github.com/user-attachments/assets/7c76041b-f105-45a5-835f-6c469b742d1b">
**After**
<img width="1297" alt="how-to-steps-after" src="https://github.com/user-attachments/assets/3bad4164-c7aa-4c0f-945a-04f90ac267bb">
- Add chevron / toggle chevron up and down to mobile toc
**Before**
<img width="933" alt="chevron - before" src="https://github.com/user-attachments/assets/935d2cab-5aa5-4fb2-8bf5-0150a0a91329">
**After**
<img width="940" alt="chevron - after" src="https://github.com/user-attachments/assets/a5fbcbb9-7582-4bc8-837b-7b354d95b7ad">
- Make Table Of Contents sticky on mobile and positioned just below the nav
**Before**
Not sticky
**After**
<img width="984" alt="sticky" src="https://github.com/user-attachments/assets/31904188-cb44-41d5-96ce-869693a0d4a0">
- Allow Authors to use short hand titles for the table of contents
**Before**
Entries in the authoring doc were the only option for text to appear in the table of contents (text must match the corresponding header)
**After**
<img width="663" alt="short content" src="https://github.com/user-attachments/assets/608c7cde-0279-4db1-aa89-f5509e4a8350">
<img width="907" alt="shortened toc entry" src="https://github.com/user-attachments/assets/1ff858ab-f6fe-455d-963e-c09628b1064d">
<img width="910" alt="shortened toc entry" src="https://github.com/user-attachments/assets/3c23f67c-a8e3-4a78-8d88-cc3b8168c786">
- Allow Authors to control whether numbers are shown for each header corresponding to each table of contents link
**Before**
<img width="940" alt="numbers missing" src="https://github.com/user-attachments/assets/b851f11c-0ae0-4d05-a90c-79d04e660393">
<img width="947" alt="numbers exist" src="https://github.com/user-attachments/assets/b8edac15-6904-446c-98bd-37462e9c0b5f">

**Pages to check for regression and performance:**
- https://jp-long-form-shorthand-toc-seo--express--adobecom.hlx.page/drafts/jsandlan/long-form-flyer

2024-10-16 19:25 UTC, JingleH commented
We are loading toc postLCP, but I'm thinking maybe it also makes sense to load in delayed phase?

2024-10-16 22:02 UTC, fullcolorcoder requested changes
Few tweaks I noticed. Also, LCP is an h1 at 2+ seconds, I think Jingle's comment is worth looking into.

2024-10-16 22:02 UTC, fullcolorcoder commented on express/features/table-of-contents-seo/table-of-contents-seo.css
> +  position: fixed;
On mobile, when you scroll down and the sticky toggles, the page jumps down the distance of the TOC bar. This should be a smooth experience, with the bar simply locking in place as you scroll down.

2024-10-23 18:29 UTC, fullcolorcoder approved these changes

2024-10-23 22:41 UTC, JingleH approved these changes

2024-10-23 22:42 UTC, JingleH commented
Our next release should contain only the new homepage, so this should go out in the one after the next one. Approving but adding the "Do not merge" label

2024-10-28 21:35 UTC, merged