add ability to add videos into how-to-steps from sharepoint
adobecom/express pull request #1241
Opened 2024-10-28 22:06 UTC by jsandland

**Fixes following issues|Adds following features:**
- Adds the ability for authors to add sharepoint videos into the How To Steps block

**Resolves:** [MWPW-161141](https://jira.corp.adobe.com/browse/MWPW-161141)

**Steps to test the before vs. after and expectations:**
- Steps for feature 1

**Pages to check for regression and performance:**
- https://<branch>--express--adobecom.hlx.page/express/?martech=off

2024-10-29 16:06 UTC, JingleH requested changes

2024-10-29 16:06 UTC, JingleH commented on express/blocks/how-to-steps/how-to-steps.js
> +        const sourceMp4 = createTag('source', { src: p.innerHTML, type: 'video/mp4' });
it might be safer to also trim p's innerHTML

2024-10-29 16:06 UTC, JingleH commented on express/blocks/how-to-steps/how-to-steps.js
> +        video.appendChild(document.createTextNode('Your browser does not support the video tag.'));
what is this one for? Do we also want to localize it?

2024-11-11 18:58 UTC, JingleH approved these changes

2024-11-11 19:25 UTC, kennethlum approved these changes

2024-11-11 20:14 UTC, merged