Dual floating cta
adobecom/express pull request #1244
Opened 2024-10-29 21:46 UTC by echen-adobe

**Fixes following issues|Adds following features:**
- Issue/Feature 1

**Resolves:** [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

**Steps to test the before vs. after and expectations:**
- Steps for feature 1

**Pages to check for regression and performance:**
- https://<branch>--express--adobecom.hlx.page/express/?martech=off

2024-10-31 22:03 UTC, JingleH commented on express/blocks/mobile-gating-button/mobile-gating-button.js
> +  a.classList.add('mobile-gating-link');
both classList.add() and node.append() can take multiple arguments so we can trim some bytes here

2024-10-31 22:05 UTC, JingleH commented on express/blocks/mobile-gating-button/mobile-gating-button.js
> +      return true;
pages authored with this block without this metadata should still return true right?

2024-11-04 20:13 UTC, JingleH commented on express/blocks/mobile-gating-button/mobile-gating-button.css
> +main .floating-button-wrapper.mobile-gating-button .floating-button .mobile-gating-link {
are these .floating-button-wrapper necessary? If not, we should remove them. It can be ambiguous in whether they are created by the block or by our lifecycle functions, so it's better to avoid as much as possible

2024-11-04 20:18 UTC, JingleH requested changes

2024-11-04 20:18 UTC, JingleH commented on express/blocks/mobile-gating-button/mobile-gating-button.js
> +    if (navigator.deviceMemory <= 4 && isAndroid) {
shouldn't this be reversed? it should return true for an Android with big RAM right?

2024-11-04 20:18 UTC, JingleH commented on express/blocks/mobile-gating-button/mobile-gating-button.js
> +function deviceCheck() {
i recommend renaming this function name to make things more explicit

2024-11-05 16:49 UTC, echen-adobe commented on express/blocks/mobile-gating-button/mobile-gating-button.css
> +main .floating-button-wrapper.mobile-gating-button .floating-button .mobile-gating-link {
removed

2024-11-05 16:50 UTC, echen-adobe commented on express/blocks/mobile-gating-button/mobile-gating-button.js
> +function deviceCheck() {
renamed

2024-11-05 17:07 UTC, JingleH approved these changes

2024-11-12 20:19 UTC, fullcolorcoder submitted a review, later dismissed
- Few var usages need refinement 
- Curious about an unresolved comment regarding authoring metadata missing

2024-11-12 20:19 UTC, fullcolorcoder commented on express/blocks/mobile-gating-button/mobile-gating-button.css
> +    font-size: 16px;
var

2024-11-12 20:19 UTC, fullcolorcoder commented on express/blocks/mobile-gating-button/mobile-gating-button.css
> +    font-size: 14px;
var

2024-11-12 20:19 UTC, fullcolorcoder commented on express/blocks/mobile-gating-button/mobile-gating-button.css
> +    background-color: white;
var

2024-11-12 20:19 UTC, fullcolorcoder commented on express/blocks/mobile-gating-button/mobile-gating-button.css
> +    background-color: #f8f8f8;
gray-100

2024-11-12 20:19 UTC, fullcolorcoder commented on express/blocks/mobile-gating-button/mobile-gating-button.css
> +    font-size: 16px;;
var

2024-11-12 20:19 UTC, fullcolorcoder commented on express/blocks/mobile-gating-button/mobile-gating-button.css
> +    border: 2px solid var(--Border-Extra-subdued-default, #E1E1E1);
gray-200

2024-11-12 20:19 UTC, fullcolorcoder commented on express/blocks/mobile-gating-button/mobile-gating-button.css
> +    color: black;
var

2024-11-12 20:20 UTC, fullcolorcoder commented on express/blocks/mobile-gating-button/mobile-gating-button.js
> +      return true;
@echen-adobe can you confirm in the comments here? I notice you marked resolve, but I am curious about this as well.

2024-11-14 20:56 UTC, jsandland approved these changes

2024-11-14 21:11 UTC, merged