adds additional paths to allow georouter
adobecom/express pull request #1247
Opened 2024-10-30 19:03 UTC by jsandland

**Fixes following issues|Adds following features:**
- Allow georouter on additional pages beyond /express

**Resolves:** [MWPW-154379](https://jira.corp.adobe.com/browse/MWPW-154379)

**Steps to test the before vs. after and expectations:**
- Steps for feature 1

**Before**
**Georouter will not appear on these pages**
-  https://www.adobe.com/id_id/express/
-  https://www.adobe.com/express/
-  https://www.adobe.com/express/entitled
-  https://www.adobe.com/express/business
-  https://www.adobe.com/express/business/teams
-  https://www.adobe.com/express/nonprofits
-  https://www.adobe.com/express/learn/students
-  https://www.adobe.com/express//education/express
-  https://www.adobe.com/express/pricing

**Pages to check for regression and performance:**
**After**
**Georouter will now appear on these pages**
-  https://allow-georouter-on-additional-pages--express--adobecom.hlx.page/id_id/express/
-  https://allow-georouter-on-additional-pages--express--adobecom.hlx.page/express/
-  https://allow-georouter-on-additional-pages--express--adobecom.hlx.page/express/entitled
-  https://allow-georouter-on-additional-pages--express--adobecom.hlx.page/express/business
-  https://allow-georouter-on-additional-pages--express--adobecom.hlx.page/express/business/teams
-  https://allow-georouter-on-additional-pages--express--adobecom.hlx.page/express/nonprofits
-  https://allow-georouter-on-additional-pages--express--adobecom.hlx.page/express/learn/students
-  https://allow-georouter-on-additional-pages--express--adobecom.hlx.page/education/express
-  https://allow-georouter-on-additional-pages--express--adobecom.hlx.page/express/pricing

2024-10-30 19:18 UTC, JingleH requested changes

2024-10-30 19:18 UTC, JingleH commented on express/scripts/utils.js
> +  const permittedPaths = ['/express/', '/entitled',
at this point, I would say maintaining this list in code would not be a good solution, so we should move to the metadata toggle approach like we do for jarvis, floating-cta, PEP, etc.

2024-10-30 21:25 UTC, jsandland commented on express/scripts/utils.js
> +  const permittedPaths = ['/express/', '/entitled',
Won't that mean that every document for a given path and the locale would need to have metadata added? I think that could get very  cumbersome. What about going by path but via spreadsheet like the existing locales? that way there is one place to make changes. What do you think?

2024-10-30 21:36 UTC, JingleH commented on express/scripts/utils.js
> +  const permittedPaths = ['/express/', '/entitled',
not really. I think I meant the same way as you said, using the spreadsheet bulk metadata approach. Our authors should already be very comfortable and familiar doing this. @vhargrave QQ: does Milo already have similar metadata authoring? If so then we can grab the key name directly

2024-10-31 09:38 UTC, vhargrave commented on express/scripts/scripts.js
> -  cn: { ietf: 'zh-Hans-CN', tk: 'puu3xkp' },
why are you removing this?

2024-10-31 09:38 UTC, vhargrave commented on express/scripts/scripts.js
> -  tr: { ietf: 'tr-TR', tk: 'ley8vds.css' },
and this?

2024-10-31 09:38 UTC, vhargrave commented on express/scripts/utils.js
> +  const permittedPaths = ['/express/', '/entitled',
yes, milo allows for that. We can turn off georouting over the config and just allow for `getMetadata('georouting')` to be set for the pages that want it. 

and yes, we probably would want this managed in the metadata spreadsheet, but @jsandland it looks like this should only be permitted for 8 pages or so? If it's only for 8 pages then authors should just do this in the word doc.

2024-10-31 09:38 UTC, vhargrave requested changes
These locales should not be removed, especially cn. 
I'd like to understand why you wanted to do it though?

2024-11-04 17:13 UTC, jsandland commented on express/scripts/scripts.js
> -  cn: { ietf: 'zh-Hans-CN', tk: 'puu3xkp' },
Orla asked me to remove cn, tr and said that we do not have express sites in those locales.

2024-11-04 17:13 UTC, jsandland commented on express/scripts/scripts.js
> -  tr: { ietf: 'tr-TR', tk: 'ley8vds.css' },
Orla asked me to remove cn, tr and said that we do not have express sites in those locales.

2024-11-05 18:20 UTC, JingleH commented on express/scripts/scripts.js
> -  tr: { ietf: 'tr-TR', tk: 'ley8vds.css' },
@jsandland I think we do though... https://www.adobe.com/cn/express/ are we looking to deprecate those locales? Then we might want a bigger discussion and lots of confirmation

2024-11-13 08:02 UTC, vhargrave requested changes
Hey Jackson! 
in general , I'd really suggest making as few changes to the scripts.js and especially the utils.js file. These files are already quite aligned with milo, so every change you do is breaking us away from our migration path.
Instead of a allowed-georouter-paths.json, authors should set the georouting metadata properly. If they need help with an easy way to do that, then we should provide support there, but not introduce new patterns which will not work with milo and make the page slower.

2024-11-13 17:52 UTC, closed without merging