Ipad home page cards style
adobecom/express pull request #1265
Opened 2024-11-11 21:54 UTC by jsandland

Fixes following issues|Adds following features:

- Reduce right margin between cards on discover-cards above 1280px.
- Increase width of gen-ai cards above 1280px.
- Decrease text-wrapper margin for gen-ai cards above 1280px.
- Remove margin-left on gen-ai cards above 1280px.
- Reduce text margin for gen-ai cards under 1280px.
- Apply iPad style on discover-cards and gen-ai cards until 1279px.
- Set discover-cards tablet header font size to 22px until 1280px, where it changes to 36px.
- Ensure gen-ai card width and height match Figma specifications.
- Set tablet gen-ai header font size to 22px and desktop gen-ai header font size to 36px.
- Delete small discover-cards bg and only use large image

Resolves: [MWPW-160965](https://jira.corp.adobe.com/browse/MWPW-160965)

Pages to check for regression and performance:

https://ipad-home-page-cards-style--express--adobecom.hlx.page/express/?martech=off

2024-11-11 22:07 UTC, JingleH approved these changes

2024-11-11 22:22 UTC, fullcolorcoder requested changes

2024-11-11 22:22 UTC, fullcolorcoder commented on express/blocks/gen-ai-cards/gen-ai-cards.css
> +  font-size: 17px;
17px is an odd px that seems off to me when we have `--body-font-size-l: 1.125rem;` (18px)
It'd be worth checking to see if this is a new standard, and if it is, then we should update our vars for consistency.

2024-11-11 22:22 UTC, fullcolorcoder commented on express/blocks/gen-ai-cards/gen-ai-cards.css
> +    font-size: 36px;
Use var

2024-11-11 22:34 UTC, jsandland commented on express/blocks/gen-ai-cards/gen-ai-cards.css
> +  font-size: 17px;
17px is pixel perfect to the design. I checked with Mariah and she's fine with 18px. The var(--body-font-size-m variable appears to be 18px. I've updated to use the variable.

2024-11-11 22:40 UTC, kennethlum commented on express/blocks/discover-cards/discover-cards.css
> +@media (min-width: 1280px) {
a question here, that supposedly the breakpoint 600px would jump to 768px, but here it is made to not let it happen until 1280px. So this is what the design calls for? It does look fine on https://ipad-home-page-cards-style--express--adobecom.hlx.page/express/

2024-11-11 22:43 UTC, jsandland commented on express/blocks/discover-cards/discover-cards.css
> +@media (min-width: 1280px) {
I'm just using Mariah's breakpoints. 
XL: 1680px+
L: 1280px+
M: 768px+
S : 360px+

2024-11-11 22:47 UTC, kennethlum commented on express/blocks/discover-cards/discover-cards.css
> +@media (min-width: 1280px) {
hm, because 
what we used to have for 600px, it jumps to 768px.  (the 375px really just means anything before the 768px, that is, a small mobile device that is "before" the 768px iPad Mini kind of portrait width).
900px jumps to 1280px
1200 jumpts to 1680px

2024-11-11 22:57 UTC, fullcolorcoder approved these changes

2024-11-11 23:26 UTC, kennethlum commented on express/blocks/discover-cards/discover-cards.css
> +@media (min-width: 1280px) {
@jsandland to add some context, I think it is like:

In the old days: min-width of 600px means, hey, the following is for us to go away from the small mobile phone onto the iPad Mini and iPad Air mode, which are 768px and 820px portrait pixel width.

So now, this number has become 768px, which is the exact starting point of iPad Mini portrait width.

In the old days: 
900px means, hey, we are moving away from tablet and onto the desktop phase, for not so wide window

So now the 900px becomes 1280px, I think considering iPad Pro actually has a 1032px portrait width.

In the old days: 
1200px is moving to the extra wide window on desktop, and now it has become 1680px

So I think in the old days, the 600px to. 899px range is for the tablets, and now it has become 768px to 1279px

2024-11-11 23:59 UTC, jsandland commented on express/blocks/discover-cards/discover-cards.css
> +@media (min-width: 1280px) {
These are the constraints I've used.

2024-11-11 23:59 UTC, jsandland commented on express/blocks/discover-cards/discover-cards.css
> +@media (min-width: 1280px) {
I've cross referenced the changes with the Figma too so I think we're good.

2024-11-11 23:59 UTC, merged

2024-11-12 00:07 UTC, kennethlum commented on express/blocks/discover-cards/discover-cards.css
> +@media (min-width: 1280px) {
sure, if you are sure and Mariah also is fine with the design, then sure