initial
adobecom/express pull request #1271
Opened 2024-11-13 00:16 UTC by echen-adobe

**Fixes following issues|Adds following features:**
- Issue/Feature 1
- Implements a template x variant called "seasonal" that has a new layout.

**Resolves:**  https://jira.corp.adobe.com/projects/MWPW/issues/MWPW-160969

**Steps to test the before vs. after and expectations:**
- Steps for feature 1
-  https://www.figma.com/design/tOhTZKVpTw3I1bXXy4D6VQ/Seasonal-banners-%26-blades?node-id=1043-22046&node-type=section&t=ZbhGOilL1yk8Plat-0

**Pages to check for regression and performance:**

- Page with variant
https://seasonal-blade-v2--express--adobecom.hlx.page/drafts/echen/simplified-homepage-copy?martech=off&gnav=off

- Page with original 
https://stage--express--adobecom.hlx.page/drafts/echen/template-x-seasonal-blade-default

https://seasonal-blade-v2--express--adobecom.hlx.page/express/?martech=off

<img width="1779" alt="Screenshot 2024-11-07 at 2 34 59 PM" src="https://github.com/user-attachments/assets/fbedbc3a-528a-4789-ae89-880777dbaeff">

<img width="1722" alt="Screenshot 2024-11-07 at 2 35 02 PM" src="https://github.com/user-attachments/assets/82207314-8e2c-47ac-a6e7-9b9964e90f90">

<img width="532" alt="Screenshot 2024-11-08 at 1 54 38 PM" src="https://github.com/user-attachments/assets/d8e3cb8c-879e-4aae-a4ec-a1fa2abef642">

https://pagespeed.web.dev/analysis/https-seasonal-blade-v2--express--adobecom-hlx-live-drafts-echen-simplified-homepage-copy/5fprqk7bwo?form_factor=mobile
 
<img width="1186" alt="Screenshot 2024-11-12 at 1 29 28 PM" src="https://github.com/user-attachments/assets/4f635394-f71d-4350-8394-837ffd9ac53f">

2024-11-13 18:05 UTC, jsandland approved these changes

2024-11-13 18:37 UTC, JingleH requested changes

2024-11-13 18:37 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.js
> +import renderTemplate from '../template-x/template-rendering.js';
same as above

2024-11-13 18:37 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.js
> +} from '../../scripts/template-search-api-v3.js';
these should be dynamic import done lazily so it won't block LCP

2024-11-13 19:04 UTC, JingleH requested changes

2024-11-13 19:04 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.css
> +    display: flex;
it's dangerous to modify section and blocks display order here. Let's still put the blade block as the first block, and like mentioned below, find ways to work around the loading order and see if we can still achieve a good LCP

2024-11-13 22:32 UTC, echen-adobe commented on express/blocks/holiday-blade/holiday-blade.css
> +    display: flex;
removed this an reverted to conventional layout

2024-11-13 22:32 UTC, echen-adobe commented on express/blocks/holiday-blade/holiday-blade.js
> +} from '../../scripts/template-search-api-v3.js';
lazy loading added

2024-11-14 18:24 UTC, JingleH requested changes

2024-11-14 18:24 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.js
> +    p.push(loadTemplatesPromise(props, innerWrapper.querySelector('.carousel-platform'), placeholders, getTemplates, i * 5, fetchTemplates, createOptimizedPicture));
if (total_limit / 5) * 5 != total_limit, you'll get the wrong number of templates returned

2024-11-14 18:24 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.js
> +  for (let i = 1; i < props.total_limit / 5; i += 1) {
since you await Promise.all of these at the end, it's equally performant if you just use 1 network request load the remaining `limit-5`.

2024-11-14 18:31 UTC, JingleH requested changes

2024-11-14 18:31 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.js
> +  const { createTag, fetchPlaceholders, createOptimizedPicture } = await import('../../scripts/utils.js');
utils.js will always have been loaded already so they can stay at the top level

2024-11-14 18:31 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.js
> +  const { isValidTemplate } = await import('../../scripts/template-search-api-v3.js');
a lot of these can be parallelized

2024-11-15 23:24 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.css
> +        --toggle-bar-height: 100px;
this is probably not needed right? since you already declared on top

2024-11-15 23:24 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.css
> +    height: 100px;
maybe use var(--toggle-bar-height) here

2024-11-15 23:24 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.css
> +    top: auto;
is this doing anything?

2024-11-15 23:24 UTC, JingleH commented on express/blocks/holiday-blade/holiday-blade.css
> +    max-width: 100%;
unless there's some overriding happening, this is probably not needed as you have specified width already

2024-11-15 23:42 UTC, JingleH approved these changes
approving and merging as we are too close to the freeze. We can do future enhancements once freeze is over

2024-11-15 23:43 UTC, merged