INTL JDI | Mobile | IN & UK | Template Carousel - Updates
adobecom/express pull request #1303
Opened 2024-12-04 20:47 UTC by jsandland

Fixes following issues|Adds following features:
- swipe on mobile maintains the same behavior seen when using the left and right chevron navigation
- the number of cards scrolled through is relevant to number of displayed cards
- scroll from left to right snaps
- resizing browser maintains mobile / desktop behavior without refresh
- CSS loads for every carousel that gets loaded on the page
- every instance of a carousel on the page maintains it's own currentIndex
- every instance of a carousel on mobile starts at the second card 
- top and bottom of template-x template expands on hover
Resolves: [MWPW-155657](https://jira.corp.adobe.com/browse/MWPW-155657)

**Pages to check for regression and performance:**
-https://basic-carousel-updates--express--adobecom.hlx.page/drafts/jsandlan/mothers-day

2024-12-04 21:11 UTC, JingleH approved these changes

2024-12-04 21:16 UTC, echen-adobe approved these changes

2024-12-05 15:34 UTC, JingleH reviewed
the mobile interactions seem to be a little off

2024-12-10 20:58 UTC, fullcolorcoder requested changes
Looking pretty good. I have a few CSS asks and a few interaction/accessibility asks as well.

On mobile:
- Clicking on the next greyed out box doesn’t advance, which is inconsistent with other carousel implementations  

Accessibility: 
- Using the right arrow advances the carousel, not the selected card
- Lacking aria labels for nav elements

2024-12-10 20:58 UTC, fullcolorcoder commented on express/blocks/shared/basic-carousel.css
> +  padding-bottom: 6px;
This is difficult to read and maintain. Please group these together by something like:
- Display / flex / grid 
- Box model properties 
- Position/layout
- Typography
- Other styles like opacity and what not 

I don't have a major nit on what order things are in, as long as they're together. In other sections I'll mention to organize, meaning this.

2024-12-10 20:58 UTC, fullcolorcoder commented on express/blocks/shared/basic-carousel.css
> +  z-index: 1;
Organize

2024-12-10 20:58 UTC, fullcolorcoder commented on express/blocks/shared/basic-carousel.css
> +  z-index: 1;
Organize

2024-12-12 01:29 UTC, fullcolorcoder approved these changes

2024-12-12 15:03 UTC, merged