FAQ Block Creation - Updates
adobecom/express pull request #1309
Opened 2024-12-06 22:14 UTC by jsandland

**Fixes following issues|Adds following features:**
- center header
- add margin-bottom to collapsible rows

**Resolves:** [MWPW-160176](https://jira.corp.adobe.com/browse/MWPW-160176)

**Before**
<img width="1143" alt="center-before" src="https://github.com/user-attachments/assets/3a53daee-8a3e-4e7e-a7bc-cd292ae2a036">
<img width="553" alt="mobile-margin-before" src="https://github.com/user-attachments/assets/ffb69b98-ad7b-4000-ad3e-8b638e4fd364">

**After**
<img width="1122" alt="center" src="https://github.com/user-attachments/assets/0ef7e409-3a70-4d9f-9a9b-16c805eac31b">
<img width="687" alt="mobile-margin" src="https://github.com/user-attachments/assets/127b03b9-b425-4101-9579-3d671ec38920">

**Pages to check for regression and performance:**
- https://faq-block-updates--express--adobecom.hlx.page/drafts/jsandlan/mothers-day

2024-12-06 22:18 UTC, echen-adobe approved these changes

2024-12-09 21:15 UTC, fullcolorcoder requested changes
A few nits. But something else a bit more major is there isn't any accessibility in this accordion. I helped build the initial accordion in Milo for some reference here. https://github.com/adobecom/milo/tree/stage/libs/blocks/accordion

At minimum this needs to be in the tab index, be open/closed via spacebar, and have aria tagging.

2024-12-09 21:15 UTC, fullcolorcoder commented on express/blocks/collapsible-rows/collapsible-rows.css
> +    margin-bottom: 10px;
Could the margin definitions all be on one line, or at least in the same place?

2024-12-09 21:15 UTC, fullcolorcoder commented on express/blocks/collapsible-rows/collapsible-rows.css
> +    background: #ffffff;
Var

2024-12-09 21:15 UTC, fullcolorcoder commented on express/blocks/collapsible-rows/collapsible-rows.js
> +    const rowWrapper = createTag('div', { class: 'collapsible-row-wrapper' }); // New wrapper
Looking at the markup I wonder why there's a wrapper inside another div that seems to wrap?
<img width="384" alt="image" src="https://github.com/user-attachments/assets/87da64b3-365c-417e-ba0e-819747a759e8">

2024-12-10 18:16 UTC, jsandland commented on express/blocks/collapsible-rows/collapsible-rows.js
> +    const rowWrapper = createTag('div', { class: 'collapsible-row-wrapper' }); // New wrapper
That wrapper allows each child, that has a parent (FAQ) and child (answer) to have its own margin-bottom. Prior to the wrapper being there - margin could only be added to one or the other not both and this created a space between the header and the text that followed, which is not in line with the design requirements.

2024-12-10 20:34 UTC, merged