[MWPW-134396] Feature Grid Bug Fix
adobecom/express pull request #131
Opened 2023-07-31 17:33 UTC by toka1300

Refactored to deal with an issue when too many cells passed in or linear gradient not passed in. You will see the 'Before' does not render the 12 cell format.

Test URLs:

Before: https://main--express--adobecom.hlx.page/drafts/casey/feature-grid-desktop-v3-x/feature-grid
After: https://feature-grid-images-2--express--adobecom.hlx.page/drafts/casey/feature-grid-desktop-v3-x/feature-grid?lighthosue=on

2023-07-31 19:38 UTC, JingleH commented
I am seeing both are showing the same 4 grid format. Are we using different links?

2023-07-31 19:49 UTC, qiyundai requested changes

2023-07-31 19:49 UTC, qiyundai commented on express/blocks/feature-grid-desktop/feature-grid-desktop.css
> +  background: none !important;
Why are we setting an !important? To overpower the inline styling?

2023-07-31 19:49 UTC, qiyundai commented on express/blocks/feature-grid-desktop/feature-grid-desktop.js
> +  children.pop();
I think pop() returns the item popped. Have you tried combining these 2 lines above into `const gradientText = children.pop().textContent;`?

2023-07-31 19:49 UTC, qiyundai commented on express/blocks/feature-grid-desktop/feature-grid-desktop.js
> +  const gradientColorRow = children.findIndex((row) => row.textContent.match(regex));
Would `children.find()` and later just check with `if (gradientColorRow)` serve you even better, with fewer bytes?

2023-07-31 20:06 UTC, toka1300 commented on express/blocks/feature-grid-desktop/feature-grid-desktop.css
> +  background: none !important;
Exactly

2023-07-31 20:08 UTC, toka1300 commented on express/blocks/feature-grid-desktop/feature-grid-desktop.js
> +  children.pop();
Good call

2023-07-31 20:11 UTC, qiyundai requested changes

2023-07-31 20:11 UTC, qiyundai commented on express/blocks/feature-grid-desktop/feature-grid-desktop.css
> +  background: none !important;
I think it's not exactly the best reason for it. Unless you have no control over the inline styling (cases where an element is rendered in an iframe from an imported script), let's try to avoid resorting to !important. 😄

2023-07-31 20:16 UTC, toka1300 commented on express/blocks/feature-grid-desktop/feature-grid-desktop.js
> +  const gradientColorRow = children.findIndex((row) => row.textContent.match(regex));
It's because I need to remove that child once I extract the info.

2023-07-31 20:17 UTC, toka1300 commented
> I am seeing both are showing the same 4 grid format. Are we using different links?

Links pulling through updated code now @JingleH

2023-08-01 18:20 UTC, qiyundai requested changes

2023-08-01 18:20 UTC, qiyundai commented on express/blocks/feature-grid-desktop/feature-grid-desktop.css
> -  font-weight: bold;
Do we need to add font-weight: bold; to .load-more-button as well?

2023-08-02 13:00 UTC, toka1300 commented on express/blocks/feature-grid-desktop/feature-grid-desktop.css
> -  font-weight: bold;
Added

2023-08-02 15:14 UTC, qiyundai approved these changes

2023-08-02 16:39 UTC, merged