[MWPW-134231] - PUF Block Integration Test
adobecom/express pull request #160
Opened 2023-08-04 20:19 UTC by redvelvet511

Added Integration test for PUF block

2023-08-09 14:05 UTC, vhargrave requested changes
Looking really good! The timeout thing should really be fixed, but asides from that it's just nit picking from me. 
Few additional notes: 
a change to real code to make things easier to test is usually not good practice (the change to instrument.js)
It seems like you've gained a little experience with the puf block. Would you feel comfortable spending an hour documenting it? https://main--express--adobecom.hlx.live/docs/authoring/ 
I have no idea what it is.

2023-08-09 14:05 UTC, vhargrave commented on test/blocks/puf/puf.test.js
> +      setTimeout(() => {
the problem with using timeouts in tests is that it makes the whole test execution a lot longer. 
It's much better to use fake timers - https://sinonjs.org/releases/latest/fake-timers/
If you want to see this in use, clone the milo project and just search for "clock"

2023-08-09 14:05 UTC, vhargrave commented on test/blocks/puf/puf.test.js
> + * Copyright 2020 Adobe. All rights reserved.
nit: 2023

2023-08-29 13:46 UTC, redvelvet511 commented
Hi Victor! There are still some enhancements or changes being made in the PUF block so I'm going to re visit this when when it's done and also to refactor it including the fake timers.

2023-09-18 13:30 UTC, vhargrave commented
@redvelvet511 can we close this PR and reopen when it's ready ? Just want to clean up the list of PRs needing a review :)

2023-09-18 13:44 UTC, redvelvet511 commented
> PR

Hi @vhargrave ! Yes, thank you. Will work on this when I'm back.

2023-09-25 16:13 UTC, closed without merging