[MWPW-134813] Template X & Template List Different From Scratch Link
adobecom/express pull request #165
Opened 2023-08-08 20:02 UTC by qiyundai

**Description:**
Template X will now have the option to use `create-link-x` column to insert a different link to template-x from scratch template.

Resolves: [MWPW-134813](https://jira.corp.adobe.com/browse/MWPW-134813)

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/kr/express/templates/?lighthouse=on
- After: https://mwpw-134813--express--adobecom.hlx.page/kr/express/templates/?lighthouse=on

2023-08-08 21:37 UTC, JingleH approved these changes

2023-08-09 13:02 UTC, vhargrave requested changes
found a few things. Let me know what you think

2023-08-09 18:18 UTC, qiyundai commented on express/scripts/all-templates-metadata.js
>        }
`templateX.innerHTML = templateX.innerHTML.replaceAll('https://www.adobe.com/express/templates/default-create-link', getMetadata('create-link-x') || getMetadata('create-link') || '/');` in content-replace.js is the actual code to split the CTA for the 2 viewports. What's happening here is just legacy code removal. These actually hasn't been functioning since we migrated to the new sharepoint, especially after we started removing sections in mismatched audience.

2023-08-09 18:18 UTC, qiyundai commented on express/scripts/content-replace.js
> +    templateList.innerHTML = templateList.innerHTML.replaceAll('https://www.adobe.com/express/templates/default-create-link', getMetadata('create-link') || '/');
I also don't like how we are handling these links. However, I want to suggest that we solidify a link placeholder format (since {{}} can't be used in links last time I tried) with the authors and incorporate it into the autoUpdatePage() in content-replace.js.

That said, I didn't actually catch what you mean by "selecting on the placeholder text and then changing the url". Did you mean we should querySelector the a tags first and then replace the link inside?

2023-08-09 22:01 UTC, apganapa approved these changes

2023-08-10 11:43 UTC, vhargrave commented on express/scripts/content-replace.js
> +    templateList.innerHTML = templateList.innerHTML.replaceAll('https://www.adobe.com/express/templates/default-create-link', getMetadata('create-link') || '/');
Yeah exactly. I think that would be better than just selecting on the link tbh.

2023-08-10 11:43 UTC, vhargrave commented on express/scripts/content-replace.js
> +    templateX.innerHTML = templateX.innerHTML.replaceAll('https://www.adobe.com/express/templates/default-create-link', getMetadata('create-link-x') || getMetadata('create-link') || '/');
I'd create a method but be passing in the placeholders as params 🙈

2023-08-10 17:54 UTC, qiyundai commented on express/scripts/content-replace.js
> +    templateList.innerHTML = templateList.innerHTML.replaceAll('https://www.adobe.com/express/templates/default-create-link', getMetadata('create-link') || '/');
Got it. I was thinking about this yesterday. I think I have an idea how to make this part of autoPageUpdate() post GA very easily. I'll log a debt ticket for this!

2023-08-14 15:39 UTC, vhargrave approved these changes
nice!

2023-08-14 16:23 UTC, JingleH approved these changes

2023-08-14 19:26 UTC, merged