[MWPW-135353] Breadcrumbs Missing. from Nav
adobecom/express pull request #200
Opened 2023-08-21 16:37 UTC by toka1300

The breadcrumbs were not displaying in the navbar.

Resolves: [MWPW-135353](https://jira.corp.adobe.com/browse/MWPW-135353)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/feature/image/remove-background
- After: https://mwpw-135353--express--adobecom.hlx.page/express/feature/image/remove-background

2023-08-22 16:47 UTC, JingleH requested changes

2023-08-22 16:47 UTC, JingleH commented on express/scripts/gnav.js
> +    const replacedCategory = placeholders[`breadcrumbs-${secondPathSegment}`].toLowerCase();
we might want to handle the case when the field is missing from placeholders sheets, and use some fallback. This can happen too easily when we do dynamic placeholders and for all those localized placeholder sheets. 🥲

2023-08-23 14:44 UTC, toka1300 commented on express/scripts/gnav.js
> +    const replacedCategory = placeholders[`breadcrumbs-${secondPathSegment}`].toLowerCase();
If it is missing 'replaced category' will be null and the next conditional will exit the function early and breadcrumbs will not render.

2023-08-23 16:23 UTC, JingleH commented on express/scripts/gnav.js
> +    const replacedCategory = placeholders[`breadcrumbs-${secondPathSegment}`].toLowerCase();
Hi @toka1300, thanks for the explanation. I'm just worrying that toLowerCase() when called on undefined will crash the program. We can add a question mark and make it ?.toLowerCase() so it will short-circuit to null/undefined

2023-08-25 17:24 UTC, JingleH approved these changes

2023-08-25 17:24 UTC, merged