Rum search tracking
adobecom/express pull request #218
Opened 2023-08-29 16:05 UTC by qiyundai

Description:
test sampleRUM for search terms tracking

Resolves: No Ticket

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/?lighthouse=on
- After: https://rum-search-tracking--express--adobecom.hlx.page/express/?lighthouse=on

2023-08-30 22:58 UTC, JingleH requested changes

2023-08-30 22:58 UTC, JingleH commented on express/blocks/search-marquee/search-marquee.js
> +    sampleRUM('search', {
Qiyun and I talked about this offline and I am thinking that since we probably want ALL the search queries, we either need to sample at 100%, or we use something that's more reliable (new API to receive logs / asking the Search API team to collect data for us). Any ideas @vhargrave @apganapa?

2023-08-31 03:55 UTC, apganapa commented on express/blocks/search-marquee/search-marquee.js
> +    sampleRUM('search', {
If the search API team have done any integration with Splunk then we should be able to gather the information from Splunk API to fetch report from the logs captured in it

2023-08-31 08:14 UTC, vhargrave commented on express/blocks/search-marquee/search-marquee.js
> +    sampleRUM('search', {
@JingleH I didn't even know that you can change the sample rate. Don't you just want to ask in the slack thread? https://adobe-mwp.slack.com/archives/C9KD0TT6G/p1693246120422709
I'm sure they'll know if it's necessary to change the sample rate or not.

2023-08-31 08:15 UTC, vhargrave commented
@qiyundai in general, there should always be a ticket for the coding work we do. I actually already created one a few days ago, so you can use that - https://jira.corp.adobe.com/browse/MWPW-135636

2023-08-31 15:13 UTC, qiyundai commented on express/blocks/search-marquee/search-marquee.js
> +    sampleRUM('search', {
Added forceSampleRate!

2023-08-31 19:10 UTC, qiyundai commented
We might want to hold out on this since the content API team is gonna setup a backend API endpoint for us to dump the data. cc: @JingleH @vhargrave

2023-09-01 10:49 UTC, vhargrave commented
> We might want to hold out on this since the content API team is gonna setup a backend API endpoint for us to dump the data. cc: @JingleH @vhargrave

@qiyundai I wouldn't wait. This is high priority for the franklin folks. Could you ask whoever wants these logs if we can either start rerouting or pause logging altogether?

2023-09-07 14:37 UTC, qiyundai commented
> > We might want to hold out on this since the content API team is gonna setup a backend API endpoint for us to dump the data. cc: @JingleH @vhargrave
> 
> @qiyundai I wouldn't wait. This is high priority for the franklin folks. Could you ask whoever wants these logs if we can either start rerouting or pause logging altogether?

In that case let's get this merged first and then take a quick look at what RUM has to offer for search tracking. Later when content API team has that backend API setup for us we can pivot again. Thoughts? @JingleH @vhargrave

2023-09-08 20:12 UTC, JingleH approved these changes

2023-09-12 12:47 UTC, vhargrave approved these changes
looks good!

2023-09-12 12:47 UTC, vhargrave commented on express/blocks/search-marquee/search-marquee.js
> +// FIXME: as soon as we verify the rum approach works, this should be retired
this is more of a TODO right? :P 
Or is something broken unless we change this ?

2023-09-12 12:48 UTC, merged