Mwpw 135640 performance load order
adobecom/express pull request #230
Opened 2023-09-05 08:32 UTC by vhargrave

changes the order that content is loaded in to give us a better chance of loading LCP faster. 

To test this PR, please do lighthouse tests and normal testing on the **.live** versions of both main and this branch
Good pages to compare are the pricing pages, the main page, the template pages, the blog pages etc. 
These pages should also still be working normally. This was a change to core functionality, so I'd appreciate a good test. 

Resolves: [MWPW-135640](https://jira.corp.adobe.com/browse/MWPW-135640)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://MWPW-135640--express--adobecom.hlx.page/express/

2023-09-05 17:12 UTC, qiyundai approved these changes

2023-09-06 16:58 UTC, qiyundai submitted a review, later dismissed

2023-09-06 17:31 UTC, JingleH requested changes

2023-09-06 17:31 UTC, JingleH commented on express/scripts/scripts.js
>      document.querySelector('body').classList.add('appear');
we can maybe also remove this line as we don't do body display:none anymore

2023-09-06 17:31 UTC, JingleH commented on express/blocks/shared/carousel.js
> +export async function buildCarousel(selector = ':scope > *', $parent, infinityScrollEnabled = false) {
one little concern from me is that we have in our code base many places using buildCarousel as a sync func, and making it async might cause some unexpected things. So we can either add await to every references of buildCarousel(), or we can take an even bigger crack on this carousel.js

2023-09-06 17:31 UTC, JingleH commented on express/blocks/how-to-steps-carousel/how-to-steps-carousel.js
> +    loadImage(backgroundPicImg).then(async () => {
I am thinking that maybe we don't need the async here

2023-09-06 17:41 UTC, vhargrave commented on express/scripts/scripts.js
>      document.querySelector('body').classList.add('appear');
good idea!

2023-09-06 17:47 UTC, vhargrave commented on express/blocks/shared/carousel.js
> +export async function buildCarousel(selector = ':scope > *', $parent, infinityScrollEnabled = false) {
Completely get your concern. Got some good news for you though. It shouldn't matter. The await only blocks the main thread if the blocks calling it also decide to await the carousel call. You should also notice I've strategically placed the await in the carousel at the end of the buildCarousel method, so that everything which was executed synchronously before still can. That's precisely why you're not seeing any strange behaviour on the templates page for example.

2023-09-06 17:48 UTC, vhargrave commented on express/blocks/how-to-steps-carousel/how-to-steps-carousel.js
> +    loadImage(backgroundPicImg).then(async () => {
awesome catch!

2023-09-06 18:03 UTC, JingleH commented on express/blocks/shared/carousel.js
> +export async function buildCarousel(selector = ':scope > *', $parent, infinityScrollEnabled = false) {
Got it! Very nice!

2023-09-06 20:13 UTC, JingleH approved these changes
LGTM! Great job! @vhargrave when you have time I think what you did to some of the blocks can also be done to our full-screen-marquee and it can greatly help with Create pages' LCP and CLS

2023-09-06 20:22 UTC, apganapa approved these changes

2023-09-06 21:59 UTC, merged