MWPW-135859 | Update XML sitemap path to align with a.com and add UK locale setting
adobecom/express pull request #232
Opened 2023-09-05 17:53 UTC by apganapa

Update XML sitemap path to align with a.com and add UK locale setting

Resolves: https://jira.corp.adobe.com/browse/MWPW-135859 and 
https://jira.corp.adobe.com/browse/MWPW-135682

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/?lighthouse=on
- After: https://MWPW-135859--express--adobecom.hlx.page/express/?lighthouse=on

2023-09-05 18:04 UTC, qiyundai submitted a review, later dismissed

2023-09-05 23:54 UTC, JingleH approved these changes

2023-09-06 08:08 UTC, vhargrave requested changes

2023-09-06 08:08 UTC, vhargrave commented on express/sitemap.xml
> -    <loc>https://www.adobe.com/express/sitemap-us.xml</loc>
is calling the us sitemap .index a requirement? I'd otherwise probably just leave it for simplicity's sake.

2023-09-06 14:57 UTC, apganapa commented on express/sitemap.xml
> +    <loc>https://www.adobe.com/blog.sitemap.xml</loc>
Thanks for catching, you are right! updated the PR.

2023-09-06 14:57 UTC, apganapa commented on express/sitemap.xml
> +    <loc>https://www.adobe.com/templates.sitemap.xml</loc>
Thanks for catching, you are right! updated the PR.

2023-09-06 15:09 UTC, apganapa commented on express/sitemap.xml
> -    <loc>https://www.adobe.com/express/sitemap-us.xml</loc>
yes, SEO team requested it. Have told them to add it in desc of ticket to make it official.

2023-09-06 16:47 UTC, vhargrave approved these changes
looks good!

2023-09-06 17:02 UTC, JingleH approved these changes

2023-09-06 17:03 UTC, qiyundai approved these changes

2023-09-07 14:32 UTC, merged