[DOTCOM-99657] Embed Vimeo and YouTube Videos in Column Block
adobecom/express pull request #242
Opened 2023-09-08 13:20 UTC by toka1300

Video links are converted to social link thumbnails by default. I have an added an exception to this, which is when the link is authored with #embed-video in the link.

Resolves: [DOTCOM-99657R](https://jira.corp.adobe.com/browse/DOTCOM-99657)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/drafts/casey/embedded-youtube
- After: https://DOTCOM-99657--express--adobecom.hlx.page/drafts/casey/embedded-youtube

2023-09-08 19:08 UTC, qiyundai requested changes
I think we are missing the commit for refactoring embed-videos.js?

2023-09-08 19:08 UTC, qiyundai commented on express/blocks/columns/columns.js
> +import { embedYoutube, embedVimeo } from '../embed/embed.js';
Is this import from the right place?

2023-09-20 08:51 UTC, vhargrave commented
Wow, what a jump in performance. Nice work! 👏 
Do we need something for youtube videos too or just for vimeo videos?

2023-09-20 13:15 UTC, qiyundai commented
> Wow, what a jump in performance. Nice work! 👏 Do we need something for youtube videos too or just for vimeo videos?

I think we can treat that as a fast follow. Or, if you think your POC branch code is ready for review we can just raise a PR from there! 💪

2023-09-20 14:05 UTC, vhargrave commented
> > Wow, what a jump in performance. Nice work! 👏 Do we need something for youtube videos too or just for vimeo videos?
> 
> I think we can treat that as a fast follow. Or, if you think your POC branch code is ready for review we can just raise a PR from there! 💪

Ok, I see the confusion. I never intended on merging my POC branch. It's sole purpose was just to quickly show a better way to add these iframes. Happy to have it worked on in a separate task though, but let's have this separate story created and linked here so that it's not forgotten.

2023-09-20 21:55 UTC, apganapa approved these changes

2023-09-20 22:15 UTC, JingleH approved these changes

2023-09-20 22:16 UTC, merged