Sync up from adobe/express-website to adobecom/express
adobecom/express pull request #34
Opened 2023-05-25 04:18 UTC by apganapa

2023-06-08 18:01 UTC, JingleH submitted a review, later dismissed

2023-06-08 18:04 UTC, JingleH commented
I really wanna get the main synched, so then we can get the stage synched, and then we can port template-list and templates.js performance improvements again back from adobe/express-website to adobecom/express 😢 this is kindda blocking my and @qiyundai 's work at the moment

2023-06-12 08:04 UTC, vhargrave requested changes
I'm almost wondering if it would make sense to create a branch off `adobecom:main`, where you test the merge from `adobe:main`. Once everything's working and tested, then you merge from that branch to `adobe:main`. 

@JingleH @qiyundai @apganapa thoughts?

2023-06-12 08:04 UTC, vhargrave commented on tools/sidekick/config.json
> +  "outerHost": "express-website--adobe.hlx.live",
I don't think these changes are wanted either - maybe just the feds-header

2023-06-12 08:04 UTC, vhargrave commented on .github/pull_request_template.md
>  Test URLs:
we don't want these changes either

2023-06-12 15:12 UTC, apganapa commented
https://github.com/adobecom/express/tree/MWPW-132431-from-main is created from https://github.com/adobecom/express
Post merging, individual files fstab.yaml file and config.json will be modified.

2023-06-12 15:14 UTC, merged