[MWPW-137709] Author Control Over Link Target Location
adobecom/express pull request #361
Opened 2023-10-16 19:52 UTC by toka1300

It has been requested that authors have the ability to override the default behaviour of opening internal links in the same tab and external links in a new tab.

**Testing:** In the marquee section, each of the CTAs should act as expected, with the hashes overriding the default behaviour.

This is achieved by using '#target

Resolves: [MWPW-137709](https://jira.corp.adobe.com/browse/MWPW-137709)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/drafts/casey/link-handling
- After: https://mwpw-137709--express--adobecom.hlx.page/drafts/casey/link-handling

2023-10-17 19:30 UTC, apganapa approved these changes

2023-10-30 10:57 UTC, vhargrave requested changes

2023-10-30 10:57 UTC, vhargrave commented on express/scripts/utils.js
> +        if ((!relative && !isAdobeOwnedLinks && !a.href.includes('#_self')) || (a.href.includes('#_blank'))) {
instead of doing self, let's align this with how things are done in milo
external links open in the same window by default unless specified otherwise in the links.xslx file.

2023-11-01 20:14 UTC, toka1300 commented
Closing this PR out, in favour of this [one](https://github.com/adobecom/express/pull/406)

2023-11-01 20:15 UTC, closed without merging