Stage to Main Release 10/24/2023
adobecom/express pull request #382
Opened 2023-10-24 18:52 UTC by JingleH

Merge stage to main

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://stage--express--adobecom.hlx.page/express/?martech=off

2023-10-24 19:35 UTC, qiyundai requested changes

2023-10-24 19:35 UTC, qiyundai commented on express/scripts/utils.js
> -export function getMeta(name) {
Now I look at this, I realize the getMetadata is more flawed than this. It decides whether the querySelector should look at property or name attribute based on ":", but we have things like twitter:card that are in name rather than property attribute.

So what I would suggest is to consolidate these 2 function, use the function name getMetadata everywhere but have the function defined with the code body of getMeta, with the difference that the return value should be a comma separated list, like in getMetadata.

Hope this makes sense...

2023-10-24 20:18 UTC, qiyundai commented on express/scripts/utils.js
> -export function getMeta(name) {
That said, this should cause no harm. We can fix the functions as a follow. Resolving the conversation.

2023-10-24 20:19 UTC, qiyundai approved these changes

2023-10-25 16:01 UTC, apganapa submitted a review, later dismissed

2023-10-25 19:04 UTC, qiyundai approved these changes

2023-10-26 12:12 UTC, vhargrave approved these changes

2023-10-26 12:12 UTC, merged