Logged in user auto redirect to product
adobecom/express pull request #388
Opened 2023-10-26 20:28 UTC by qiyundai

- The logged in user will now get redirected into the product after 5s with 2s response time.
- If the user cancels the redirect sequence, the modal is suppressed for the next 3 visits
- The modal will try to get primacyCTA link from the BlockMediator, but will resort to using the querySelector to find a link that either matches the floating CTA on the page or the button with 'primacyCTA' class.
- There's some refactor done to the existing delay load product code.
- Utils proactively export helper functions and placeholders in a delayUtils package to delayed.js

Resolves: [Desktop] RTP CCX0137- Direct Path to Product. I can't see the ticket link.

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/express/?martech=off
- After: https://login-auto-redirect--express--adobecom.hlx.page/express/?martech=off

2023-10-26 21:41 UTC, JingleH requested changes

2023-10-26 21:41 UTC, JingleH commented on express/scripts/delayed.js
> +import BlockMediator from './block-mediator.js';
this is a bit confusing but let's use the minified BlockMediator

2023-10-27 21:44 UTC, qiyundai commented on express/scripts/delayed.js
> +import BlockMediator from './block-mediator.js';
Ah yes. Nice catch.

2023-10-30 13:17 UTC, vhargrave requested changes
Nice job! It's working pretty well.
There are a few code changes that I think need to be done to get this finished up and additionally, I'm not sure the redirect modal should stay open when I'm redirected, and navigate back in the browser: 
![Screenshot 2023-10-30 at 13 56 59](https://github.com/adobecom/express/assets/115231412/9ff0ef97-89fc-4be2-a378-932810d04645)

2023-10-31 02:11 UTC, qiyundai commented on express/scripts/delayed.js
> +async function loadLoginUserAutoRedirect() {
Sure! Gonna call it `direct-path-to-product.js` if you don't mind. I feel like `auto-redirect.js` might be a little generic for what this feature is doing.

2023-10-31 02:11 UTC, qiyundai commented on express/scripts/delayed.js
> +    const primaryCtaUrl = BlockMediator.get('primaryCtaUrl')
I'm not sure we need to subscribe as this is the only & last moment we'd need the `primaryCtaUrl` and we don't need to listen for any change. But please let me know if I'm missing something...

2023-10-31 02:11 UTC, qiyundai commented on express/scripts/delayed.js
> +    const container = await buildRedirectAlert(profile);
Sounds good! I'll use .then syntax!

2023-10-31 02:11 UTC, qiyundai commented on express/scripts/delayed.js
> +    localStorage.setItem('no-bmtp', (counterNumber - 1).toString());
Sure!

2023-10-31 02:12 UTC, qiyundai commented on express/scripts/delayed.js
> +    loadExpressProduct();
Yes. I think it is already outside the setTimeout(() => {}, DELAY) 😉

2023-10-31 02:12 UTC, qiyundai commented on express/scripts/utils.js
> +  if (userProfile && autoRedirectLanguageFound && autoRedirect) {
Sure thing!

2023-11-02 20:06 UTC, qiyundai commented
Currently waiting for Abhinav to confirm on delay second number

2023-12-11 21:32 UTC, JingleH approved these changes

2023-12-12 17:01 UTC, vhargrave approved these changes

2023-12-12 17:02 UTC, merged