[MWPW 128657] Template X: Holiday Block
adobecom/express pull request #39
Opened 2023-05-26 13:53 UTC by toka1300

Fix: https://jira.corp.adobe.com/browse/MWPW-128657

Test URLs:

Before: https://main--express--adobecom.hlx.page/drafts/casey/template-x/holiday-collab
After: https://mwpw-128657--express--adobecom.hlx.page/drafts/casey/template-x/holiday-collab?lighthouse=on
--> Animated: switch filename to "holiday-animated"
--> Custom Background: Switch filename to "holiday-custom-color"
Updated holiday block, with enhancements and to be compatible with Template-X

2023-05-30 18:04 UTC, apganapa approved these changes

2023-06-06 13:42 UTC, vhargrave requested changes
Found a few things. Additionally, there's no hover effect when hovering over the picture part of a template. That should probably be fixed

I've also seen that a request for the image is being sent every time i hover over an image. That seems quite wrong to me.

2023-06-07 15:51 UTC, toka1300 commented
> Found a few things. Additionally, there's no hover effect when hovering over the picture part of a template. That should probably be fixed

2023-06-07 17:24 UTC, toka1300 commented on express/blocks/template-x/template-x.js
> +  const parent = block.closest('.template-x-wrapper.fullwidth.holiday');
Updated

2023-06-07 17:31 UTC, toka1300 commented on express/blocks/template-x/template-x.js
> +        const contrastingTextColor = isDarkOverlayReadable(backgroundColor) ? '#242424' : '#fff';
This code is only called when it is authored to be a holiday block, so it is only affecting the text within the holiday variant, which should all be the contrasting colour.

2023-06-08 12:58 UTC, toka1300 commented on express/blocks/template-x/template-x.js
> +  aTag.addEventListener('click', (e) => {
This is to stop the propagation of the collapsing/expanding of the block and allow for the redirect

2023-06-08 13:02 UTC, vhargrave commented on express/blocks/template-x/template-x.css
> +    main .template-x.horizontal.holiday .toggle-bar p {
yes please!

2023-06-08 13:03 UTC, vhargrave commented on express/blocks/template-x/template-x.js
> +        const contrastingTextColor = isDarkOverlayReadable(backgroundColor) ? '#242424' : '#fff';
ok, you should probably steer all that by setting an appropriate class though.

2023-06-08 18:53 UTC, toka1300 commented on express/blocks/template-x/template-x.js
> +  heading.style.color = props.textColor;
Done!

2023-06-08 18:53 UTC, toka1300 commented on express/blocks/template-x/template-x.js
> +  const mobileToggle = toggle.cloneNode(true);
Refactored to have one toggle element

2023-06-08 20:45 UTC, qiyundai commented
@toka1300 Found a small regression:
https://mwpw-128657-2--express--adobecom.hlx.page/drafts/docs/blocks-how-to/template-x 
The normal horizontal fullwidth one seems to no longer be fullwidth anymore

2023-06-15 19:29 UTC, toka1300 commented
Was not intentionally closed, I think the force push automatically closed it.

2023-06-16 13:36 UTC, toka1300 commented
Opening again

2023-06-26 18:23 UTC, closed without merging

2023-06-26 18:24 UTC, toka1300 commented
Have moved over to this [PR](https://github.com/adobecom/express/pull/66)