Opt 17338
adobecom/express pull request #399
Opened 2023-10-27 21:13 UTC by markpadbe

Adds mobile-drawer and related drawer-item
Adds tracking with data-ll and data-lh
Adds see experiment with param
Adds hide experiment button with param

Resolves: [OPT-17338](https://jira.corp.adobe.com/browse/OPT-17338)

Test URLs:
before:
https://stage--express--adobecom.hlx.page/express/experiments/ccx0098/control/flyer?experiment=ccx0098%2Fchallenger-control
https://stage--express--adobecom.hlx.page/express/experiments/ccx0098/control/flyer?experiment=ccx0098%2Fchallenger-1
https://stage--express--adobecom.hlx.page/express/experiments/ccx0098/control/flyer?experiment=ccx0098%2Fchallenger-2
After:
https://opt-17338--express--adobecom.hlx.page/express/experiments/ccx0098/control/flyer?experiment=ccx0098%2Fchallenger-2&button=off
https://opt-17338--express--adobecom.hlx.page/express/experiments/ccx0098/control/flyer?experiment=ccx0098%2Fchallenger-1&button=off
https://opt-17338--express--adobecom.hlx.page/express/experiments/ccx0098/control/flyer?experiment=ccx0098%2Fchallenger-control&button=off

2023-10-27 21:25 UTC, apganapa commented
do we need icons.old?

2023-10-27 21:56 UTC, JingleH requested changes

2023-10-27 21:56 UTC, JingleH commented on express/scripts/instrument.js
> +    let trackingHeader = a.closest('[data-lh]');
We are in the progress to moving to using daa-lh and daa-ll (we will want to follow https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=marketingtech&title=Analytics+in+Milo and https://wiki.corp.adobe.com/pages/viewpage.action?pageId=2667172745). Is this data-lh and data-ll the same idea?

2023-10-27 21:56 UTC, JingleH commented on express/scripts/utils.js
> +  const experimentParams = url.get('experiment');
feel free to move this new flag into our utils.js loadArea() and attach experiment to window.hlx. It might be easier to use that centralized place to manage the new added experiment params

2023-10-27 21:56 UTC, JingleH commented on express/scripts/utils.js
> +  const buttonOff = new URLSearchParams(window.location.search).get('button') === 'off';
is this button param only for this test? We then need to think of a way to avoid modifying utils.js every time we are doing a new test. Maybe we can move this import preview.js logic to somewhere, so we won't have frequent changes to this relatively stable file. It should generally be a good pattern to separate what changes frequently from what changes rarely.

2023-10-27 21:56 UTC, JingleH commented on express/scripts/instrument.js
> +    if (trackingHeader || a.dataset.lh) {
This is a headsup and not request for change: according to https://github.com/adobecom/milo/blob/main/libs/martech/analytics.md, we should avoid adding lh tags inside blocks, and let some global logic handle adding lh to each section. We haven't got to add lh at the moment, so I think you'll need to add lh yourself in your block for now. In the future when we finish adding lh to all sections, we shall remember to come back and remove these custom-lhs to avoid duplications.

2023-10-27 22:05 UTC, markpadbe commented
> do we need icons.old? @markpadbe

This is now deleted. Thank you.

2023-10-27 22:27 UTC, markpadbe commented on express/scripts/utils.js
> +  const buttonOff = new URLSearchParams(window.location.search).get('button') === 'off';
The intention is that this would be for all experiments, not just this test, and that it wouldn't necessarily need to be updated again(unless another solution like making the buttons draggable is preferred). Currently the experiments "Testing On" and "Experiments: [Experiment ID]" buttons in mobile sit at the bottom-center of the screen, blocking content a developer might be working on. This fix allows any developer working in experiments to easily hide those buttons by adding a parameter to the url:

![Screen Shot 2023-10-27 at 3 16 54 PM](https://github.com/adobecom/express/assets/124626043/e4d4c883-f818-4828-b6bc-25f9fbfd5987)


![Screen Shot 2023-10-27 at 3 16 33 PM](https://github.com/adobecom/express/assets/124626043/5ca71ec2-072a-452b-ae0a-f5317e7385dc)

2023-10-27 22:31 UTC, markpadbe commented
> do we need icons.old? @markpadbe

This is deleted now. Thanks.

2023-10-27 22:35 UTC, markpadbe commented on express/scripts/instrument.js
> +    let trackingHeader = a.closest('[data-lh]');
Yes, this is a "temp" fix that can be used in roughly the same way until daa-ll and daa-lh are available.

2023-10-29 00:48 UTC, markpadbe commented on express/scripts/utils.js
> +  const experimentParams = url.get('experiment');
I've made this update. Thanks.

2023-10-30 14:16 UTC, vhargrave reviewed
Looks pretty good. Can you document this briefly [here](https://main--express--adobecom.hlx.page/docs/authoring/)?
Our docs are pretty sparse atm, so we need to make extra efforts atm to be building them out.

2023-10-30 21:29 UTC, JingleH approved these changes

2023-10-30 22:48 UTC, apganapa approved these changes

2023-10-30 22:48 UTC, merged