[MWPW-138553][Technical Debt] - Columns block Unit Test
adobecom/express pull request #402
Opened 2023-10-31 19:25 UTC by redvelvet511

Added Integration test for Columns block

Test URLs:

Before: https://stage--express--adobecom.hlx.page/express/learn/blog?martech=off
After: https://columns-ut--express--adobecom.hlx.page/express/learn/blog?martech=off

2023-11-02 19:54 UTC, qiyundai requested changes

2023-11-02 19:54 UTC, qiyundai commented on express/blocks/columns/columns.js
> +                  elementsMinHeight[referrer] || 0,
Could you check again here if the issue is we need a fallback 0 or it's the tag at L291 is presume the wrong element? Could it be that it needs to be IMG instead of PICTURE? Thanks!

2023-11-08 17:29 UTC, JingleH approved these changes

2023-11-08 17:40 UTC, qiyundai approved these changes

2023-11-08 17:40 UTC, merged