feat(hero-color): first ver of the block
adobecom/express pull request #46
Opened 2023-06-01 22:20 UTC by redvelvet511

[MWPW-131948]

**Description**
- Built a new block called called 'hero-color' for the colors page

**Test URLs:**
- Before: https://main--express--adobecom.hlx.page/express/colors/red?lighthouse
- After: https://mwpw-131948--express--adobecom.hlx.page/express/colors/red?lighthouse

2023-06-08 22:07 UTC, qiyundai requested changes
Please take a look and let me know if anything's unclear! I'm happy to get in a call too if needed.

2023-06-08 22:07 UTC, qiyundai commented on express/blocks/hero-color/hero-color.js
> +function changeTextColorAccordingToBg(
In a different approach, the entire function can be as simple as 
`if (isDarkoverlayReadable(primaryColor) block.classList.add('light-bg');`
And the rest can be handled in the css based on that class.

In general, we avoid assigning static RGB or HEX in JS. Color page has it's primary and secondary thing, which is different. In his case we are just juggling between 2 sets of black and white relationships, which should be just in CSS using the predefined `var(--color-black)` and `var(--color-white)`.

2023-06-08 22:07 UTC, qiyundai commented on express/blocks/hero-color/hero-color.js
> +function changeSvgAccordingToMediaQuery(svgId, svgWrapper, secondaryColor) {
Can we just approach it in a way that's not swapping the svg at all and let it be 100% height according to the block? I think from L71 to L99 can be entirely removed if we handle the svg right in the CSS.

2023-06-15 15:59 UTC, qiyundai commented
Last round:

- I've pushed a new sprite sheet to the branch. Use the desktop version of the color-marquee svg with viewBox only and instead of loading a different svg:
- - set the svg height to the content container height
- - update the svg height when matchMedia change triggers

- Also, give the content-container a max-width of 1440px, and move the background color from the content-container to the block level.

2023-06-28 20:01 UTC, qiyundai approved these changes
LGTM for now. This is a brand new block. Let's revisit it post homepage v3x

2023-06-29 22:00 UTC, apganapa approved these changes

2023-06-29 22:02 UTC, merged