Floating CTA scroll arrow disable control
adobecom/express pull request #461
Opened 2023-11-10 21:10 UTC by qiyundai

Floating CTA's scroll arrow can now be disabled in floating-cta.xslx with the use lottie arrow column = 'no'

Resolves: 
Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/business?dev=on
- After: https://floating-cta-arrow-toggle--express--adobecom.hlx.page/express/business?dev=on&martech=off

Dev sheet is here: https://adobe.sharepoint.com/:x:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7BA4C0914C-88CB-4FE1-A5B8-11C6A6EC1621%7D&file=floating-cta-dev.xlsx&action=default&mobileredirect=true if anyone wants to test with more pages. Editing this sheet will not have any effect on production pages

2023-11-13 13:51 UTC, redvelvet511 approved these changes

2023-11-13 22:50 UTC, JingleH requested changes

2023-11-13 22:50 UTC, JingleH commented on express/scripts/utils.js
> +    if (!BlockMediator.get('floatingCtasLoaded')) {
i am thinking that we should probably do optionally import BlockMediator and run following script. Otherwise, we will be always importing BlockMediator and it will be an extra script fetch blocking our LCP even on pages without floating-cta or show-multifunction-button

2023-11-13 23:18 UTC, qiyundai commented on express/scripts/utils.js
> +    if (!BlockMediator.get('floatingCtasLoaded')) {
Oh we definitely should. Coming right up.

2023-11-16 17:00 UTC, JingleH approved these changes

2023-11-16 17:00 UTC, merged