Multifunction Floating CTA initial load CLS fix
adobecom/express pull request #476
Opened 2023-11-17 20:14 UTC by qiyundai

I noticed that sometimes multifunction floating CTA's initial transition would cause a huge CLS penalty. This PR is to make the multifunction button not transition until the initial delay passes or the user has interacted with it. We should get a better CLS score.

Resolves: [MWPW-136879](https://jira.corp.adobe.com/browse/MWPW-136879)

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/express/create/flyer?martech=off
- After: https://multi-cta-fix--express--adobecom.hlx.page/express/create/flyer?martech=off

2023-11-17 21:28 UTC, qiyundai commented
Honestly I'm not so sure anymore if this fixes anything CLS. It does still make the loading of the multifunction button look & feel better for the users and has a refactoring that reduces the CSS loaded for the regular version of the floating button. So it's still worth the PR I think.

2023-12-01 14:28 UTC, vhargrave commented
linters or tests are failing here

2023-12-01 15:33 UTC, vhargrave commented
failing lint & tests here too

2023-12-01 16:02 UTC, vhargrave requested changes
I'm a bit on the fence with this one @qiyundai .
I'm not getting reliable test results when comparing this PR vs main on pagespeed.web.dev . Would you be ok with discussing this on Monday?

2023-12-01 16:02 UTC, vhargrave commented on express/blocks/how-to-steps-carousel/how-to-steps-carousel.js
> +function convertCanvasToBlob(canvas, width, height) {
I love the idea, but did this change actually show a measurable difference?

2023-12-03 00:43 UTC, qiyundai commented on express/blocks/cta-carousel/cta-carousel.js
> +export const windowHelper = {
I absolutely agree.. there are actually 2 changes in this PR that are related to this issue. I fear that we'll have to test less because we can't be triggering the redirect in tests.

Besides this, the added code in carousel.js for isTestEnv, the gen-ai-cards block would also be affected.

2023-12-04 10:21 UTC, vhargrave commented on express/blocks/how-to-steps-carousel/how-to-steps-carousel.js
> +function convertCanvasToBlob(canvas, width, height) {
ok, sounds good!

2023-12-06 20:38 UTC, qiyundai commented
I removed the worker stuff and added a couple intersection observers to not let how to steps blocks init animation on page load. I've noticed that sometimes causing long tasks on CPU throttled tests. Do you think you can give this another look? Thanks! @vhargrave

2023-12-07 14:18 UTC, vhargrave requested changes

2023-12-07 14:18 UTC, vhargrave commented on express/blocks/search-marquee/search-marquee.js
> +async function decorateLinkList(block) {
probably want to await this as well?

2023-12-07 14:18 UTC, vhargrave commented on express/blocks/shared/carousel.js
> +  parent.style.visibility = 'hidden';
why are we making the carousel not visible? 
block sections do not display until they're fully loaded.

2023-12-07 14:18 UTC, vhargrave commented on express/scripts/utils.js
> +  if (!$a) return;
I don't think this guard is necessary. It's less bytes to just use braces

2023-12-07 15:23 UTC, qiyundai commented on express/blocks/color-how-to-carousel/color-how-to-carousel.js
> +  const colorHowToObserver = new IntersectionObserver(onIntersect, { threshold: 0 });
I'm a little worried about making the threshold = 1 as what if the user has a slightly smaller viewport than the full height of the block then the animation will never start?

2023-12-08 12:03 UTC, vhargrave commented on express/blocks/color-how-to-carousel/color-how-to-carousel.js
> +  const colorHowToObserver = new IntersectionObserver(onIntersect, { threshold: 0 });
you're right! I thought threshold worked slightly differently

2023-12-08 12:03 UTC, vhargrave commented on express/blocks/how-to-steps-carousel/how-to-steps-carousel.js
> +  const howToStepsObserver = new IntersectionObserver(onIntersect, { threshold: 0 });
Fair!

2023-12-08 15:39 UTC, vhargrave approved these changes

2023-12-08 15:44 UTC, JingleH approved these changes

2023-12-08 15:47 UTC, merged