[MWPW-139167][Technical Debt] - Floating Button block Unit Test
adobecom/express pull request #483
Opened 2023-11-22 21:02 UTC by redvelvet511

Added Integration test for Banner block
JIRA ticket: https://jira.corp.adobe.com/browse/MWPW-139685

Test URLs:
Before: https://stage--express--adobecom.hlx.page/express/learn/blog?martech=off
After: https://banner-ut--express--adobecom.hlx.page/express/learn/blog?martech=off

2023-11-27 15:50 UTC, qiyundai requested changes

2023-12-04 17:04 UTC, AaronAtkinson commented
The [multi-button.html](https://github.com/adobecom/express/blob/banner-ut/test/unit/blocks/banner/mocks/multi-button.html) appears to only have a single button, and [body.html](https://github.com/adobecom/express/blob/banner-ut/test/unit/blocks/banner/mocks/body.html) includes two.

Maybe add a second button element to the multi-button mock and a move the assertion that multiple buttons exist to the 'Banner multi-button has correct elements' test.

```javascript
    const buttons = banner.querySelectorAll('a.button');
    expect(buttons.length).to.be.at.least(2);
```

2023-12-04 17:20 UTC, AaronAtkinson requested changes
multi-button.html appears to only have a single button, and body.html is being used to test that multiple buttons exist.

Maybe add an additional button element to the multi-button mock and a move the assertion that multiple buttons exist to the 'Banner multi-button has correct elements' test.

2023-12-06 20:30 UTC, qiyundai approved these changes

2023-12-07 14:19 UTC, merged