[MILO MIGRATION] feat: port decorateLinks feature from milo
adobecom/express pull request #484
Opened 2023-11-23 09:25 UTC by catalan-adobe

Port Milo's link decoration into Express.

Resolves: [MWPW-139145](https://jira.corp.adobe.com/browse/MWPW-139145)

Test URLs:
- https://main--milo/--adobecom.hlx.page/drafts/vhargrave/telephone

2023-11-29 14:34 UTC, vhargrave requested changes
We're getting closer! 
found a few small things, and one more bug. Look at the contact-sales button [here](https://decoratelinks-milo--express--adobecom.hlx.page/express/business) . It's a link, but on main you'll see that it's actually supposed to be a button

2023-11-29 14:34 UTC, vhargrave commented on express/blocks/search-marquee/search-marquee.js
>          const splitArr = media.split('.');
We only need half this code now. We already have the image in an image tag. Let's just give it the right class, move it to where it needs to be, make it load eagerly and await that.

2023-11-30 08:26 UTC, catalan-adobe commented on express/scripts/content-replace.js
> +  main.querySelectorAll('a[href*="#"]').forEach((a) => {
Why would you move it to scripts.js?
About `isDoc`, it's defined in utils.js but not scripts.js, what about moving this code in the `if (isDoc) {` block of utils.js? (https://github.com/adobecom/express/blob/decoratelinks-milo/express/scripts/utils.js#L2607, few lines above its current location)

2023-11-30 12:45 UTC, catalan-adobe commented on express/blocks/search-marquee/search-marquee.js
>          const splitArr = media.split('.');
fixed in [d0ae765](https://github.com/adobecom/express/pull/484/commits/d0ae7657ea253ec030fa74875e04487b9dd9cb13)

2023-11-30 12:45 UTC, catalan-adobe commented on express/scripts/content-replace.js
> +      // invalid url
fixed in [649f15b](https://github.com/adobecom/express/pull/484/commits/649f15b594735a406ff40ff15f8fd24e50f3f520)

2023-12-04 07:45 UTC, catalan-adobe commented on express/scripts/utils.js
> +        a.className = `modal link-block ${[...a.classList].join(' ')}`;
this is the "culprit" line for the non rendering secondary button on https://decoratelinks-milo--express--adobecom.hlx.page/express/business.
Removing `link-block` fixes the issue.
@vhargrave, `link-block` usage is limited to `utils.js`. From what I understand, it is used as a way to exclude links from being decorated via `decorateButtons`.
I wonder if we could simply remove `link-block` everywhere.

2023-12-15 08:03 UTC, catalan-adobe commented on express/scripts/utils.js
> +        a.className = `modal link-block ${[...a.classList].join(' ')}`;
@vhargrave, I applied your suggestion in [77ed2ef](https://github.com/adobecom/express/pull/484/commits/77ed2ef26fbd5208744407770f169a2a34a397d8)

2024-01-03 14:36 UTC, vhargrave approved these changes
It's looking good! Awesome stuff and thank you so much for the help on this :-)

2024-01-17 08:44 UTC, catalan-adobe commented on express/blocks/search-marquee/search-marquee.js
> +    mediaRow.remove();
done in [63b8116](https://github.com/adobecom/express/pull/484/commits/63b811647001b4390316a3a981eec00a40b87a8b)

2024-01-17 14:06 UTC, apganapa approved these changes

2024-01-22 12:19 UTC, merged