evaluate if breadcrumbs exist early and adjust the gnav height to red…
adobecom/express pull request #498
Opened 2023-11-30 16:47 UTC by AaronAtkinson

- Added a function "hasBreadcrumbs" to scripts.js to evaluate if a page has breadcrumbs or not. And applies a new class "breadcrumbs-spacing" to the body if breadcrumbs exist.
- In gnav.js the metadata tag for toggling breadcrumbs has been switched to Milos metadata tag in buildBreadCrumbArray function. And a couple lines in that function have been moved below a potential return condition to where they are used.
- A new css variable was added for the breadcrumb height and a rule applying it with the new body class.

Resolves: [MWPW-137051](https://jira.corp.adobe.com/browse/MWPW-137051)

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/express/feature/image/resize?martech=off
- After: https://mwpw-137051--express--wbstry.hlx.page/express/feature/image/resize?martech=off

2023-11-30 16:58 UTC, qiyundai requested changes

2023-11-30 16:58 UTC, qiyundai commented on express/scripts/scripts.js
> +  if (hasBreadcrumbs()) document.querySelector('body').classList.add('breadcrumbs-spacing');
It's better to use document.body rather than querySelect it

2023-11-30 16:58 UTC, qiyundai commented on express/styles/styles.css
> +@media (min-width:900px) {
I think conventionally we have a space after : in media queries.

2023-11-30 16:58 UTC, qiyundai commented on express/scripts/gnav.js
> +    const capitalize = (word) => word.charAt(0).toUpperCase() + word.slice(1);
Still curious why these got moved 😅

2023-11-30 17:12 UTC, AaronAtkinson commented on express/scripts/gnav.js
> +    const capitalize = (word) => word.charAt(0).toUpperCase() + word.slice(1);
I don't see why we would want a conditional exit block between their declaration and their use. If the branch that follows them returns there's no reason to have evaluated and stored them.

2023-11-30 17:16 UTC, AaronAtkinson commented on express/styles/styles.css
> +@media (min-width:900px) {
So picky 😝

2023-12-13 13:24 UTC, vhargrave requested changes

2023-12-13 13:24 UTC, vhargrave commented on express/scripts/scripts.js
> +  if (hasBreadcrumbs()) document.body.classList.add('breadcrumbs-spacing');
have you tested this code will improve performance? 
I can't see where you're using this new breadcrumbs-spacing class at all

2023-12-13 13:24 UTC, vhargrave commented on express/styles/styles.css
> -body > header:not(.feds-header-wrapper){
This worries me a little bit. Why are we removing this style? Does this not have any impact on CLS on normal pages?

2023-12-13 13:24 UTC, vhargrave commented on express/styles/styles.css
> +  body.banner-spacing > .feds-topnav-spacing,
What's your thinking behind doing this? :)

2023-12-13 16:48 UTC, AaronAtkinson commented on express/styles/styles.css
> -body > header:not(.feds-header-wrapper){
@qiyundai assured me he was confident that this was no longer needed/in-use. But I am unfamiliar with the feds logic.

2023-12-13 17:06 UTC, AaronAtkinson commented on express/styles/styles.css
> +  body.banner-spacing > .feds-topnav-spacing,
Accidentally removed the breadcrumbs-spacing class rules instead of the banner-spacing.

2023-12-13 20:05 UTC, AaronAtkinson commented on express/styles/styles.css
> -body > header:not(.feds-header-wrapper){
This has been re-incorporated

2024-01-04 13:38 UTC, vhargrave requested changes
found one more thing, and then I think we're ready to rock n roll 🙌

2024-01-04 13:38 UTC, vhargrave commented on express/scripts/gnav.js
> +    if (isHomepage || getMetadata('breadcrumbs') !== 'on') {
this will break the current breadcrumb experience.
in order for everything to keep working you'll probably need to add an extra bit of logic in our scripts.js which does the following 
```
if (getMetadata('hide-breadcrumbs') !== 'true' && !getMetadata('breadcrumbs') && !window.location.pathname.endsWith('/express/')) {
    const meta = createTag('meta', { name: 'breadcrumbs', content: 'on' });
    document.head.append(meta);
  }
```

2024-01-12 16:25 UTC, AaronAtkinson commented on express/scripts/gnav.js
> +    if (isHomepage || getMetadata('breadcrumbs') !== 'on') {
^ This is a great approach. I thought you were just adding an additional condition to the gnav function you attached this comment to, but generating the new milo friendly breadcrumb metadata from the old tag in scripts is a great fix to let us refer to the new system everywhere else without worrying about breaking old authored docs!

2024-01-15 12:08 UTC, closed without merging