Qa tool assertion
adobecom/express pull request #518
Opened 2023-12-07 23:22 UTC by qiyundai

This PR is based off of the other open QA tool PR https://github.com/adobecom/express/pull/503;

This PR adds the prototype auto assertion feature to the QA tool. The visual and syntax are as followed:

![Screenshot 2023-12-07 at 17 19 21](https://github.com/adobecom/express/assets/57737624/73a6645b-3a51-45fc-a755-014ba36c7fc4)
![Screenshot 2023-12-07 at 17 21 38](https://github.com/adobecom/express/assets/57737624/be2c9b16-12ec-4a70-850f-4081215d994d)

Resolves: [MWPW-139775](https://jira.corp.adobe.com/browse/MWPW-139775)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://qa-tool-assertion--express--adobecom.hlx.page/express/

2023-12-11 17:05 UTC, JingleH approved these changes

2023-12-18 21:36 UTC, AaronAtkinson requested changes
I think the change regarding adding the targetUrl Protocol would be beneficial for running on a local env.

2023-12-18 21:36 UTC, AaronAtkinson commented on express/scripts/features/qa-guide/qa-guide.js
> +  const targetUrl = pageUrl ? window.location.host + (pageUrl.pathname) : pageLink;
After some investigating, I've identified the issue that I was encountering when trying to test this locally. The targetUrl doesn't include the url protocol, which throws the error "...the scheme does not have a registered handler" when trying to redirect to the next qaprogress on localhost.

The following fix may not be necessary for production, but it does simplify testing on local environments:

``const targetUrl = pageUrl ? `${window.location.protocol}//${window.location.host}${pageUrl.pathname}` : pageLink;``

2023-12-18 21:36 UTC, AaronAtkinson commented on express/scripts/features/qa-guide/qa-guide.js
> +        timestamp: Date.now(),
I didn't see a comment about switching from a formatted date to a plain timestamp, but clearly the change was made somewhere along the line. I see pros and cons for both approaches, I thought it would be worth discussing what is preferred as this current approach is not very human readable, and I recall authors wanting to see times associated with versions.

2024-01-02 18:15 UTC, apganapa approved these changes

2024-01-02 19:18 UTC, JingleH commented
there's the other PR that's related: https://github.com/adobecom/express/pull/503. We'll check back later if we miss anything when we have more bandwidth

2024-02-05 17:34 UTC, JingleH approved these changes

2024-02-05 20:13 UTC, merged