Added fadersDisabled option and optimized carousel.js
adobecom/express pull request #524
Opened 2023-12-12 00:13 UTC by AaronAtkinson

Added new options param for buildCarousel function "fadersDisabled" which prevents faders & arrows from being added.
Refactored carousel.js so that:

- Fader elements are not added when the new option is used.
- Trigger elements and intersection observers are only added when needed (not when inifinity scroll is enabled and not if faders are disabled)
- Trigger intersection observer logic toggling faders is in it's own dedicated functions so it can be unit tested.

Resolves: [MWPW-139892](https://jira.corp.adobe.com/browse/MWPW-139892)

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/express/?martech=off
- After: https://refactor-carousel--express--wbstry.hlx.page/express/?martech=off

2023-12-18 17:44 UTC, redvelvet511 approved these changes

2023-12-18 19:03 UTC, redvelvet511 approved these changes

2024-01-04 15:28 UTC, vhargrave commented on express/blocks/shared/carousel.js
> +        if (entry.isIntersecting) hideFader(leftControl);
this code would also look nicer with that toggleMethod.

2024-01-04 15:28 UTC, vhargrave commented on express/blocks/shared/carousel.js
> +  if (!options.fadersDisabled) {
Do you know where this code will be used? 
i'm suddenly a little concerned that we've built something that we don't need 😅

2024-01-04 15:29 UTC, vhargrave commented
Merge conflicts also need to be resolved.

2024-01-12 17:51 UTC, AaronAtkinson commented on express/blocks/shared/carousel.js
> +        if (entry.isIntersecting) hideFader(leftControl);
The toggleFader function definitely improved the readability and simplicity here!

2024-01-12 17:54 UTC, AaronAtkinson commented on express/blocks/shared/carousel.js
> +  if (!options.fadersDisabled) {
This was added for an experiment, but is no longer being used for that, or anywhere else.

2024-01-12 18:06 UTC, AaronAtkinson commented on express/blocks/shared/carousel.js
> +  if (!options.fadersDisabled) {
I removed the option 👍

2024-01-15 16:17 UTC, vhargrave requested changes
linters/tests are failing
when I go to our homepage and change to a different tab such as photo, the carousel doesn't get initialized anymore.  
![Uploading image.png…]()

2024-02-06 10:08 UTC, closed without merging