[MWPW-139115] - Replace "premium" icon
adobecom/express pull request #532
Opened 2023-12-13 18:25 UTC by redvelvet511

Resolves: [MWPW-139115](https://jira.corp.adobe.com/browse/MWPW-139115)

Description:
- Old premium icon needs to be replaced by the gradient new one. Changed premium.svg to a .js file in order to return it as a string.

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/pricing?martech=off
- After: https://premium-icon--express--adobecom.hlx.page/express/pricing?martech=off

2023-12-13 21:27 UTC, JingleH requested changes

2023-12-13 21:27 UTC, JingleH commented on express/scripts/utils.js
> +    return premiumSVG;
Let's do the dynamic import here so pages not requiring the premium svg won't need to load it. Something like import ('../icons/premium.js').then().
Note that this thing will become async though.

2023-12-13 22:03 UTC, AaronAtkinson approved these changes
Confirmed on Browserstack that the icon is showing up on all the major browsers and devices, for mobile and desktop

2024-01-02 19:55 UTC, JingleH commented on express/scripts/utils.js
> +    return premiumSVG;
yes we cannot make getIcon() async 😢, as its consumers expect a string to be embedded right away. We'll need to try 3 workarounds, each comes with pros and cons:
1. we copy the content of premium.svg into utils.js, so this saves a network request, but those bytes will live in utils.js even for pages not needing this icon, as every page loads utils.js. This is very easy to implement and can be done right away.
2. we move the special-handling async logic for premium.svg from getIcon() to fixIcons(). So in fixIcons() when we see premium, we don't use getIcon() and go through the spritesheet but directly load the svg async. This will be ok because fixIcons is already async. But this is also a pretty ugly workaround as it's still requiring us to cater to 1 special icon.
3. We remove "premium" from the list of "spritesheet icons" (getIcon() will then fall back to return <img>) and check what blocks are using this premium icon and update the code for those blocks so that they can accept both the spritesheet style <svg><use/></svg> and conventional style <img src='*.svg'/>. For example, the PUF block only accepts the former and thus it fails when seeing an <img>. If PUF block code can adapt to whatever format the icon is in, we can treat all icons equally in our utils.js. This is a bit more work, but if not that many blocks need to be changed, this is the best solution.

Let me know your ideas @vhargrave and @redvelvet511 and @AaronAtkinson. I prefer the 3rd. I will reach out to authors and see how many places we are using <premium> and hopefully it's just PUF.

2024-01-02 20:19 UTC, JingleH commented on express/scripts/utils.js
> +    return premiumSVG;
Authors replied and 3rd it is!

2024-01-02 20:28 UTC, redvelvet511 commented on express/scripts/utils.js
> +    return premiumSVG;
Thanks @JingleH

2024-01-09 17:31 UTC, JingleH requested changes
except the sheet, all looks good! Thanks @redvelvet511 !

2024-01-09 17:31 UTC, JingleH commented on express/icons/ccx-sheet_44.svg
Hi @redvelvet511 I think we can keep this file unchanged (uncomment) or remove the premium44 from it.

2024-01-09 17:43 UTC, redvelvet511 commented on express/icons/ccx-sheet_44.svg
Hi, I removed the premium44 from it instead if that's okay :)

2024-01-09 17:44 UTC, JingleH approved these changes

2024-01-09 17:45 UTC, merged