[MWPW-140190] - Blog Visual Fixes
adobecom/express pull request #533
Opened 2023-12-13 20:50 UTC by redvelvet511

Resolves: [MWPW-140190](https://jira.corp.adobe.com/browse/MWPW-140190)

Description:
**Issue#1**
- Removed the default section paddings in styles.css due to it creating a lot of extra whitespace when a section has only one block (due to it being wrapped). Since the goal is to slowly move into how Milo does section-metadata section spacing, we could potentially start introducing the Milo way when ready, however, temporarily, padding has been added in the utils.js to fix the current pages and not make it break.

<img width="1136" alt="image" src="https://github.com/adobecom/express/assets/113856982/e8e0e5c9-ed97-43ff-a6ee-2f74275629f4">

<br></br>
**Issue#2**
- Added an if condition to check if it's in blogs, as the rest still needs the 'free use forever' widget and it gets added on each first column.

Test URLs:
**Issue#1 (white space padding, particularly on mobile ver)**
- Before: https://main--express--adobecom.hlx.page/express/learn/blog?martech=off
- After: https://mwpw-140190--express--adobecom.hlx.page/express/learn/blog?martech=off

**Issue#2 (remove 'free use forever')**
- Before: https://main--express--adobecom.hlx.page/express/learn/blog/tags/featured?martech=off
- After: https://mwpw-140190--express--adobecom.hlx.page/express/learn/blog/tags/featured?martech=off

2023-12-14 17:08 UTC, AaronAtkinson commented on express/scripts/utils.js
> +
My understanding is that we should avoid making changes to utils.js that deviate from the milo file. Might it be a more compatible approach to the milo migration to specify this spacing through CSS selectors in styles.css, blog-posts.css, etc. ? 
Something like: 

.section:not(.marquee-container):not(.banner-container):not(:has(div.default-content-wrapper)):has(div){
	padding-top:20px;
}

.section.banner-container{
    margin-top:20px;
}

2023-12-14 18:32 UTC, AaronAtkinson reviewed
Wondering what the opinion is on relying on CSS selectors to target sections rather than modify the utils.js file.

2023-12-14 18:32 UTC, AaronAtkinson commented on express/scripts/utils.js
My understanding is that we should avoid making changes to utils.js that deviate from the milo file. Might it be a more compatible approach to the milo migration to specify this spacing through CSS selectors in styles.css, blog-posts.css, etc. ?
Something like:

.section:not(.marquee-container):not(.banner-container):not(:has(div.default-content-wrapper)):has(div){
padding-top:20px;
}

.section.banner-container{
margin-top:20px;
}

2023-12-14 18:40 UTC, vhargrave commented on express/scripts/utils.js
only having a minute to glance over this, but yes. 
no changes to the utils.js file anymore unless we're aligning with milo ! :) 
a css change sounds appropriate.

2023-12-18 18:39 UTC, AaronAtkinson approved these changes
Pretty time consuming to confirm these CSS rules aren't effecting other sections!
But I didn't see any issues 👍

2024-01-04 12:54 UTC, vhargrave commented
why is there a do not merge label? should this not be reviewed and merged?

2024-01-15 16:31 UTC, vhargrave requested changes
As I've understood it this PR should only be adjusting the padding for the blog. 
I shouldn't therefore be seeing changes to the padding in the third section of this page for example - https://mwpw-140190--express--adobecom.hlx.page/express/feature/image/resize?martech=off

2024-01-15 19:22 UTC, redvelvet511 commented
> As I've understood it this PR should only be adjusting the padding for the blog. I shouldn't therefore be seeing changes to the padding in the third section of this page for example - https://mwpw-140190--express--adobecom.hlx.page/express/feature/image/resize?martech=off

Hey Victor! Sorry I didn't see your comment. Yes, it's for the extra space for the blog page (especially on mobile) for example:
https://main--express--adobecom.hlx.page/express/learn/blog?martech=off
However, those extra spaces are from the general styles.css section margin. So it will affect the other pages' sections.
![image](https://github.com/adobecom/express/assets/113856982/c438f233-f142-430c-a6c8-6a818b5089d9)

This also is related to this issue: https://jira.corp.adobe.com/browse/MWPW-139409
![image](https://github.com/adobecom/express/assets/113856982/c7b0a0ff-aee0-4b16-96d3-dd2e67322bbf)
so I thought it would be hitting two birds with one stone.
I added fixed paddings manually to the ones that will be affected by removing the .section margin throughout the whole express site so that it would still look good. Because the white spacing is caused by the blocks' own margin/padding on top of the .section margins. And since we're moving to Milo and adding the section metadata, those would have to be erased anyway to create a new value.

I think this is also the ongoing discussion between the devs and the pms about the white spacing that I've stumbled upon on slack?

2024-01-16 08:38 UTC, vhargrave commented
@redvelvet511 no worries! I only wrote the message yesterday. 
I do really like the initiative. The issue currently is that I've quickly found an example where the paddings do not look good. Please compare the padding of the third section of this page with main - https://main--express--adobecom.hlx.page/express/feature/image/resize?martech=off
Since I found this pretty quickly it wouldn't surprise me if there are other examples where the padding is now off. In my opinion it would therefore be better to simply focus on solving the initial task, since the current solution is not "stable".

2024-02-06 10:08 UTC, closed without merging