[DOTCOM-108489] - Editor Choice icon is broken on sticky footer (design-app page)
adobecom/express pull request #545
Opened 2023-12-19 19:42 UTC by redvelvet511

Resolves: [DOTCOM-108489](https://jira.corp.adobe.com/browse/DOTCOM-108489)

**Description:** 
- The live page is rendering an img instead of an icon. Changed the authoring page to target the right icon. Then added margin to add spacing between the icons.

**Test URLs:**
- Live site with broken img: https://www.adobe.com/in/express/design-app
- Before: https://main--express--adobecom.hlx.page/in/express/design-app?martech=off
- After: https://dotcom-108489--express--adobecom.hlx.page/in/express/design-app?martech=off

2023-12-19 20:11 UTC, williambsm requested changes

2023-12-19 20:11 UTC, williambsm commented on express/blocks/sticky-footer/sticky-footer.css
> +
Can we kill that whiteline?

2023-12-20 17:49 UTC, AaronAtkinson approved these changes
Limited changes required, looks good!

2024-01-04 12:45 UTC, vhargrave approved these changes

2024-01-04 12:46 UTC, merged