[MWPW-140190-1] - Blog Visual Fixes (Issue #2 Remove free widget on blogs)
adobecom/express pull request #550
Opened 2024-01-03 16:39 UTC by redvelvet511

Resolves: [MWPW-140190](https://jira.corp.adobe.com/browse/MWPW-140190)

Description:
**Issue#2**
- Added an if condition to check if it's in blogs, as the rest still needs the 'free use forever' widget and it gets added on each first column.

Test URLs:
**Issue#2 (remove 'free use forever')**
- Before: https://main--express--adobecom.hlx.page/express/learn/blog/tags/featured?martech=off
- After: https://mwpw-140190-1--express--adobecom.hlx.page/express/learn/blog/tags/featured?martech=off

2024-01-03 21:52 UTC, AaronAtkinson approved these changes
I'm not sure that the margin change in blog-post.css is within the scope of this PR, but I don't see it as an issue.

2024-01-03 21:52 UTC, AaronAtkinson commented on express/blocks/blog-posts/blog-posts.css
> +    margin: auto;
Should this change perhaps remain in the PR for issue #1? 
Are .blog-hero-card elements relevant to the .free-plan-widget element?

2024-01-04 11:50 UTC, vhargrave requested changes
Nice find. :) Found one thing and also agree with the comment from Aaron. Once those two things are looked at we should be good.

2024-01-04 11:50 UTC, vhargrave commented on express/blocks/columns/columns.js
> +  if (!window.location.href.includes('/express/learn/blog') && document.querySelector('main .columns') === block
I'm not a big fan of executing code if the user is on a subset of pages, because now the url can't change without things being broken. 
how about checking for the appropriate metadata instead? 
`if((getMetadata('theme') === 'blog' || getMetadata('template') === 'blog') && document.querySelector('main .columns') === block)`

2024-01-04 23:00 UTC, AaronAtkinson commented on express/blocks/columns/columns.js
> +  if (!window.location.href.includes('/express/learn/blog') && document.querySelector('main .columns') === block
I should really take a closer look at what metadata tags are used.

2024-01-05 21:52 UTC, redvelvet511 commented on express/blocks/columns/columns.js
> +  if (!window.location.href.includes('/express/learn/blog') && document.querySelector('main .columns') === block
@vhargrave Right, good idea thanks!

2024-01-08 16:08 UTC, JingleH approved these changes

2024-01-15 08:39 UTC, merged