MWPW-142162 | Adding logic for dynamically pulling save percentage to pricing block
adobecom/express pull request #618
Opened 2024-02-06 13:47 UTC by apganapa

Adding logic for dynamically pulling save percentage to pricing block

Based on requirement if the country is HK or MO then offerText/eyeBrowText should not be seen and if present then it needs to be pulled from offer-new sheet.

Resolves: [MWPW-142162](https://jira.corp.adobe.com/browse/MWPW-142162)

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/drafts/apganapa/index-feb?martech=off
- After: https://MWPW-142162--express--adobecom.hlx.page/express/drafts/apganapa/index-feb?martech=off

- Before: https://stage--express--adobecom.hlx.page/drafts/jingle/one-plans-pricing?martech=off
- After: https://MWPW-142162--express--adobecom.hlx.page/drafts/jingle/one-plans-pricing?martech=off

2024-02-06 14:13 UTC, qiyundai requested changes

2024-02-06 14:13 UTC, qiyundai commented on express/blocks/pricing-summary/pricing-summary.js
> +  const removeOfferBlock = checkOfferExcludeCountry();
I think these new lines need to be after the (!eyeBrowCols) condition.

2024-02-06 16:09 UTC, apganapa commented on express/blocks/pricing-summary/pricing-summary.js
> +  const removeOfferBlock = checkOfferExcludeCountry();
Makes sense, updated the PR

2024-02-08 16:40 UTC, qiyundai commented
@apganapa there's seems to be some linting issues still

2024-02-13 21:07 UTC, JingleH approved these changes

2024-02-13 21:09 UTC, merged