[Due Dilligence][MWPW-142646]  AX Blog Page LHS Improvement
adobecom/express pull request #640
Opened 2024-02-14 19:01 UTC by echen-adobe

Describe your specific features or fixes

Draft PR, not ready for review

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://<branch>--express--adobecom.hlx.page/express/

2024-02-15 17:24 UTC, JingleH commented
@echen-adobe, the improvements in TBT look promising! Good job! I see that our LCP is still not ideal. Could you look into what other resources got loaded before it or after it's loaded, why it didn't get displayed soon enough? I see the potential of pushing it to 95+ so let's go for it!
I think there are still lingering TBT sometimes, can you do some analysis on where that's coming from and see if is possible that we can even continue making it lower?

2024-02-15 20:35 UTC, qiyundai approved these changes
Nice!

2024-02-15 22:48 UTC, apganapa commented on express/blocks/blog-posts/blog-posts.js
> +  $card.innerHTML = `<div class="blog-card-image">
we can remove the "$" prefix since we are updating these sections across wherever we are touching.
It was old convention to use "$" and last year we internally decided to not use it moment we touch some code to refactor and when we write new code. @echen-adobe

2024-02-16 18:17 UTC, echen-adobe commented on express/blocks/blog-posts/blog-posts.js
> +  $card.innerHTML = `<div class="blog-card-image">
Gotcha. Just removed the $ from variable names in the latest commit.

2024-02-20 18:13 UTC, apganapa approved these changes

2024-02-21 15:44 UTC, JingleH requested changes

2024-02-21 15:44 UTC, JingleH commented on express/blocks/marquee/marquee.js
> +  video.setAttribute('preloas', 'auto');
@echen-adobe i think this is a typo?

2024-02-21 15:47 UTC, JingleH requested changes

2024-02-21 15:47 UTC, JingleH commented on express/blocks/marquee/marquee.js
> +async function handleAnimation(div, typeHint, block, animations) {
i think this doesn't need to be async

2024-02-21 15:47 UTC, JingleH commented on express/blocks/marquee/marquee.js
> +async function handleOptions(div, typeHint, block) {
same as above

2024-02-21 15:47 UTC, JingleH commented on express/blocks/marquee/marquee.js
>      } else if (!typeHint || (typeHint && !possibleBreakpoints.includes(typeHint))) {
feel free to remove `typeHint &&` as well: i think by the time the express after || gets evaluated, typeHint is already non-falsey

2024-02-21 16:05 UTC, echen-adobe commented on express/blocks/marquee/marquee.js
> +async function handleOptions(div, typeHint, block) {
removed the async and the typo

2024-02-21 19:06 UTC, JingleH approved these changes

2024-02-21 19:07 UTC, merged