Beta gating enhancement
adobecom/express pull request #680
Opened 2024-02-26 17:34 UTC by qiyundai

Our mobile beta gating experience can now be authored to:
- use different promo bar fragments
- use rushedBetaGating script with "rush-beta-gating" metadata

Resolves: [MWPW-143140](https://jira.corp.adobe.com/browse/MWPW-143140)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/drafts/qiyundai/index-no-frag
- After: https://<branch>--express--adobecom.hlx.page/drafts/qiyundai/index-no-frag

2024-02-27 22:01 UTC, JingleH approved these changes

2024-02-27 22:10 UTC, JingleH requested changes
holding for now

2024-02-28 01:26 UTC, qiyundai commented
> holding for now

Should be good now!

2024-02-28 16:56 UTC, JingleH approved these changes

2024-02-28 16:56 UTC, JingleH commented on express/blocks/firefly-card/firefly-card.js
> +    const awaitGatingResult = new Promise((resolve) => {
just a nit and not important: maybe we can move the promise creation and await inside the if condition, so that eligible device can charge ahead a tiny bit faster. i doubt there'll be any real difference but could still worth changing

2024-02-28 18:43 UTC, qiyundai commented on express/blocks/firefly-card/firefly-card.js
> +    const awaitGatingResult = new Promise((resolve) => {
Sounds good! I did a bit of refactor. Let me know your thoughts?

2024-02-28 20:13 UTC, apganapa-adobe approved these changes

2024-02-28 22:32 UTC, JingleH approved these changes

2024-02-28 23:11 UTC, echen-adobe approved these changes

2024-02-28 23:11 UTC, echen-adobe commented on express/blocks/firefly-card/firefly-card.js
> +  if (['yes', 'on', 'true'].includes(getMetadata('rush-beta-gating')) && ['yes', 'true', 'on'].includes(getMetadata('mobile-benchmark').toLowerCase()) && document.body.dataset.device === 'mobile') {
nit: does ['yes', 'on', 'true] need to be in a particular order?

2024-02-28 23:50 UTC, qiyundai commented on express/blocks/firefly-card/firefly-card.js
> +  if (['yes', 'on', 'true'].includes(getMetadata('rush-beta-gating')) && ['yes', 'true', 'on'].includes(getMetadata('mobile-benchmark').toLowerCase()) && document.body.dataset.device === 'mobile') {
Not really...We sometimes also have a "Y"

2024-02-28 23:58 UTC, merged