MWPW-141916: Replace decoreateMarqueeColumns with style
adobecom/express pull request #704
Opened 2024-03-05 14:17 UTC by rl-adobe

Remove decorateMarqueeColumns function from the utils.js.
Instead complete the stylesheet of the columns element with detailed css selector.

Resolves: [MWPW-191916](https://jira.corp.adobe.com/browse/MWPW-191916)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://MWPW-191916-decorateMarqueeColumns--express--adobecom.hlx.page/express/?martech=off

2024-03-05 14:36 UTC, qiyundai approved these changes

2024-03-05 14:38 UTC, vhargrave requested changes
it seems a bit strange to be setting min height and then unsetting it again. Can you see if we can fully remove?

2024-03-05 14:38 UTC, vhargrave commented on express/styles/styles.css
> +main .section:first-of-type .columns:first-of-type {
and this one :)

2024-03-05 14:38 UTC, vhargrave commented on express/blocks/columns/columns.css
> +main .section:first-of-type .columns:first-of-type {
we can probably get rid of this style

2024-03-05 15:16 UTC, rl-adobe commented on express/blocks/columns/columns.css
> +main .section:first-of-type .columns:first-of-type {
From the stage, I see the style in columns.css overrides the one in styles.css.

Let me remove the style from the styles.css.

2024-04-05 13:22 UTC, vhargrave commented
I just tested this and the experience on the home page is completely broken for example. Can you take a look? 
https://mwpw-191916-decoratemarqueecolumns--express--adobecom.hlx.page/express/?martech=off

2024-04-05 13:22 UTC, vhargrave requested changes
see comment

2024-04-05 17:45 UTC, rl-adobe commented
> see comment

It seems because of the sync problem with the stage banch.
Working now.

2024-04-11 17:34 UTC, vhargrave approved these changes

2024-04-11 17:34 UTC, merged