MWPW-142256: Fefactor split sections
adobecom/express pull request #711
Opened 2024-03-06 01:19 UTC by rl-adobe

- Remove the splitSection feature from the utils.js.
- Moved the logic to individual components (banner, layouts, promotion, template-list)

Resolves: [MWPW-142256](https://jira.corp.adobe.com/browse/MWPW-142256)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://142256--express--adobecom.hlx.page/express/?martech=off

2024-03-06 02:04 UTC, qiyundai commented on express/scripts/decorate.js
> +export function unwrapBlock($block, $blockName) {
might as well remove the dollar signs now 😄

2024-03-06 02:04 UTC, qiyundai commented
This type of changes really bring joy to my heart

2024-03-06 08:35 UTC, vhargrave requested changes

2024-03-06 08:35 UTC, vhargrave commented on express/blocks/layouts/layouts.js
> +  addTempWrapper($block, 'template-list');
wrong wrapper! :)

2024-03-06 16:24 UTC, rl-adobe commented on express/scripts/decorate.js
> +export function unwrapBlock($block, $blockName) {
Should we remove all dollar sign from the variables?

2024-03-06 16:29 UTC, vhargrave commented on express/scripts/decorate.js
> +export function unwrapBlock($block, $blockName) {
yes, they can all go

2024-03-07 20:17 UTC, qiyundai commented
Something's still not working right. Take a look at these two pages:
https://mwpw-142256-refactor-splitsections--express--adobecom.hlx.page/in/express/feature/image/resize
vs
https://www.adobe.com/in/express/feature/image/resize
Notice that on this branch's version:

- We failed to split the block into its own section from the default content above it thus making the content lose its max-width wrapper
- We are leaving an empty section at the next node

2024-03-07 21:19 UTC, rl-adobe commented
> Something's still not working right. Take a look at these two pages: https://mwpw-142256-refactor-splitsections--express--adobecom.hlx.page/in/express/feature/image/resize vs https://www.adobe.com/in/express/feature/image/resize Notice that on this branch's version:
> 
> * We failed to split the block into its own section from the default content above it, thus making the content lose its max-width wrapper
> * We are leaving an empty section at the next node

2024-03-08 17:00 UTC, qiyundai commented
@rl-adobe Another thing I just noticed while I was restructuring our project -- we have a decorate.js in the scripts/utils/ already. Do you think we can consolidate your scripts/decorate.js into it?

2024-03-08 17:18 UTC, rl-adobe commented
> @rl-adobe Another thing I just noticed while I was restructuring our project -- we have a decorate.js in the scripts/utils/ already. Do you think we can consolidate your scripts/decorate.js into it?

That should be fine I think. Would you move this code to utils/decorate.js or may I take on this PR?

2024-03-11 13:57 UTC, qiyundai commented
@rl-adobe Could you please merge stage into you branch again and take the floating-panel related files exactly as-is from stage? It's been rebuilt entirely and isn't involved in these migration compatibility works anymore.

2024-03-13 17:59 UTC, qiyundai commented
This is getting very close! Could you please merge stage in one more time and make sure /express/feature/image/remove-background works properly on mobile? There are some errors in the console and it's probably just simple import path fix related to the split-action.js. Thanks!

2024-04-05 12:03 UTC, vhargrave approved these changes

2024-04-05 13:13 UTC, qiyundai approved these changes

2024-04-05 13:23 UTC, merged