[MWPW-133254] Pricing Summary V3x block
adobecom/express pull request #76
Opened 2023-06-30 20:40 UTC by redvelvet511

https://jira.corp.adobe.com/browse/MWPW-133254

[MWPW-133254]

**Description**
- Option for authors to change CTA color
- Option for authors to add 2 or 3 column
- Option for authors to add a 'details' learn more link

Test **URLs:**
- Before: https://main--express--adobecom.hlx.page/express/drafts/pricing-summary?lighthouse=on
- After: https://mwpw-133254--express--adobecom.hlx.page/express/drafts/pricing-summary?lighthouse=on

2023-07-06 16:11 UTC, qiyundai requested changes
Left a few points. Overall, I think we over-engineered this block. Happy to have a call to go over together! 😄

2023-07-06 16:11 UTC, qiyundai commented on express/blocks/pricing-summary/pricing-summary.js
> +  cleanEmptyParagraphs(column);
Once we reduce the DOM manipulation for this block, we shouldn't need this.

2023-07-18 16:13 UTC, qiyundai approved these changes
Unblocking merge but we should follow with test and possible enhancement

2023-07-19 08:28 UTC, vhargrave commented
@qiyundai & @redvelvet511 does this also need to get merged to stage?

2023-07-19 16:48 UTC, closed without merging