Template x accessibility
adobecom/express pull request #762
Opened 2024-03-18 21:05 UTC by echen-adobe

Describe your specific features or fixes

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://<branch>--express--adobecom.hlx.page/express/

2024-03-19 20:42 UTC, qiyundai requested changes

2024-03-19 20:42 UTC, qiyundai commented on express/blocks/cta-carousel/cta-carousel.css
> +    border: 2px var(--color-info-accent) solid !important
Browser will probably be OK with this but I think we should still have the ; here

2024-03-19 20:42 UTC, qiyundai commented on express/blocks/cta-carousel/cta-carousel.css
> +    border: 2px var(--color-info-accent) solid !important
And if we can do this without !important that would be great but I don't know enough to really pick on it. I wrote 4 !important just this week...

2024-03-19 20:54 UTC, JingleH commented
nice! This also helps me see one issue with the updated billing-toggle. Let me push a fix directly to this branch tomorrow

2024-03-19 21:13 UTC, echen-adobe commented on express/scripts/utils.js
> +    const videos = target.querySelectorAll('video');
resolved in latest round of commits

2024-03-19 21:13 UTC, echen-adobe commented on express/blocks/layouts/layouts.js
> +    $layout.innerHTML = `<a class="layout-inside" href= ${layout.link && layout.link}>
resolved in latest round of commits

2024-03-19 21:13 UTC, echen-adobe commented on express/blocks/cta-carousel/cta-carousel.css
> +    border: 2px var(--color-info-accent) solid !important
I removed the !importants, it was necessary before but somehow was fixed during development.

2024-03-20 16:44 UTC, qiyundai commented
I can't tell which card in the layout block I'm tabbing through on https://template-x-accessibility--express--adobecom.hlx.page/express/feature/image/resize. Is it intended?

2024-03-20 16:46 UTC, qiyundai commented
I still can't perform the copy to clipboard action on the template-x templates. Do we plan to fix that in this PR?
![Screenshot 2024-03-20 at 11 45 30 AM](https://github.com/adobecom/express/assets/57737624/677f64c9-e091-4678-984f-177475b2d970)

2024-03-20 16:49 UTC, JingleH approved these changes

2024-03-20 19:02 UTC, qiyundai commented on express/blocks/template-x/template-x.css
> +    border: 2px var(--color-info-accent) solid;
With your fixes that opens the modal on tabbing, we can probably just remove this to avoid that small 2px shifting!

2024-03-20 19:35 UTC, echen-adobe commented on express/blocks/template-x/template-x.css
> +    border: 2px var(--color-info-accent) solid;
removed just now

2024-03-20 19:37 UTC, qiyundai approved these changes

2024-03-20 19:39 UTC, merged