[MWPW-128656] Template X receive Search Bar from Search Marquee
adobecom/express pull request #80
Opened 2023-07-07 21:57 UTC by qiyundai

Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix [MWPW-128656](https://jira.corp.adobe.com/browse/MWPW-128656)

**Description:**
Some small layout tweaking to avoid masonry col squeezing
Added sticky search bar if both **tool bar** and **search bar** are toggled on for template X block and the search marquee block is present on the page.

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/templates/?lighthouse=on
- After: https://mwpw-128656--express--adobecom.hlx.page/express/templates/?lighthouse=on

2023-07-19 08:58 UTC, vhargrave requested changes
There are merge conflicts here currently

2023-07-19 19:28 UTC, toka1300 commented
Looks like the import reference for the fetchAPI is not pointing to the correct folder (linting error)

2023-07-19 19:40 UTC, toka1300 commented
When I filter on 'Free' or 'Premium', the filter goes back to 'Premium & Free'.
![image](https://github.com/adobecom/express/assets/105597527/9998e89c-4788-4b9e-ae86-3964f12de936)

2023-07-19 20:04 UTC, toka1300 commented
When filtered on 'animated', are all of the templates supposed to animate on hover?

2023-07-19 22:08 UTC, qiyundai commented
> When filtered on 'animated', are all of the templates supposed to animate on hover?

not necessarily. animated isn't really an accurate filter any more. Nonetheless, all of the templates you see with a small play icon on the bottom left cover are the ones with hover play effect.

2023-07-19 22:09 UTC, qiyundai commented
> When I filter on 'Free' or 'Premium', the filter goes back to 'Premium & Free'. Same goes for the 'Static/Animated' filter. ![image](https://user-images.githubusercontent.com/105597527/254693046-675b8696-61a8-4f38-a9e2-b524851ea9c3.png)

This is a new issue that exists before this PR as well. I left a fixme comment in the code and temporarily commented out the line of code causing the issue. This will not be a GA blocker but is worth a fast follow!

2023-07-20 14:32 UTC, toka1300 commented
> > When filtered on 'animated', are all of the templates supposed to animate on hover?
> 
> not necessarily. animated isn't really an accurate filter any more. Nonetheless, all of the templates you see with a small play icon on the bottom left cover are the ones with hover play effect.

The change you made seems to have fixed it, most I was seeing before were not animating, now most are.

2023-07-20 17:39 UTC, qiyundai commented
> One other thing I just noticed and maybe not critical but the hover on the category list goes all the way down the page, making for a bit of a weird effect. Maybe should be sticky to top as you scroll down or make wrapper not go down the whole page. This is one I implemented, so I can take a look if you think it's worth it.
> 
> <img alt="image" width="716" src="https://user-images.githubusercontent.com/105597527/254916527-ee6b4f7d-41f9-46e1-9993-8c5cd372dc0a.png">

This is how it is on production now and Sean hasn't mentioned anything so I think we should leave it be. Thanks for the proactiveness, though!

2023-07-21 09:01 UTC, vhargrave requested changes
Can you provide test links to test this sticky search bar?

2023-07-21 09:01 UTC, vhargrave commented on express/blocks/template-x/template-x.js
> +            searchDropdown.classList.remove('hidden');
setTimeout is usually a sign of code smell. Why are we waiting precisely 500 milliseconds? What's the goal here?

2023-07-21 09:01 UTC, vhargrave requested changes
Additionally - you should probably add a unit test to test the search bar is being sticky right?

2023-07-21 21:29 UTC, qiyundai commented
> Additionally - you should probably add a unit test to test the search bar is being sticky right?

Yes. Thanks for the reminder!

2023-07-21 21:30 UTC, qiyundai commented on express/blocks/template-x/autocomplete-api-v3.js
> +  // 'HzTextLockup', 'Icon', 'Photo', 'DesignAsset', 'Background'
@JingleH Any insight?

2023-07-21 21:32 UTC, qiyundai commented on express/blocks/template-x/template-x.js
> +            searchDropdown.classList.remove('hidden');
the goal was to let the expand animation of the search bar finish before the dropdown can appear.

2023-07-21 21:42 UTC, JingleH commented on express/blocks/template-x/autocomplete-api-v3.js
> +  // 'HzTextLockup', 'Icon', 'Photo', 'DesignAsset', 'Background'
Yes we can remove that comment and reduce more bytes!

2023-07-26 19:21 UTC, JingleH approved these changes

2023-07-27 16:31 UTC, apganapa approved these changes

2023-07-31 12:57 UTC, vhargrave submitted a review, later dismissed
Looks good! Merge conflicts need to be fixed, but then we're good to go.

2023-07-31 12:57 UTC, vhargrave commented on express/blocks/template-x/template-x.js
> +            searchDropdown.classList.remove('hidden');
ok, that is definitely valid :)

2023-07-31 16:32 UTC, JingleH approved these changes

2023-07-31 16:33 UTC, apganapa approved these changes

2023-07-31 19:21 UTC, JingleH approved these changes

2023-07-31 19:23 UTC, merged