[Floating-CTA][Performance] Replace Fetch with Metadata for FloatingCTAs
adobecom/express pull request #813
Opened 2024-04-10 19:58 UTC by JingleH

Use metadata approach for floatingCTA

Resolves: https://jira.corp.adobe.com/browse/MWPW-142261

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/express/drafts/qiyundai/homepage-v3-mobile-ga/business
- After: https://meta-floating-cta--express--adobecom.hlx.page/express/drafts/qiyundai/homepage-v3-mobile-ga/business
- https://meta-floating-cta--express--adobecom.hlx.page/drafts/qiyundai/homepage-v3-mobile-ga/flyer

2024-04-10 20:43 UTC, echen-adobe approved these changes

2024-04-11 20:03 UTC, fullcolorcoder requested changes

2024-04-11 20:03 UTC, fullcolorcoder commented on express/blocks/shared/floating-cta.js
> +      text: getMetadata('main-cta-text'),
Do you have a solid comparison for before? Comparing the current homepage, it seems it still actually comes in faster regarding the CTA (and LH score). I'm wondering if the getMetaData is now cumbersome because of how many times we have to call it, in this case looks like over 20 document.head.querySelector calls are happening. 

Perhaps we could load it sooner, or test out a one off use case (_not_ the entire app) of querySelectorAll? Though it eats more memory and is generally a no... it would only be once, and then you could parse though it without additional DOM calls. 

<img width="970" alt="image" src="https://github.com/adobecom/express/assets/7562106/f7205658-40bf-4f32-88a8-d28ccd8f6efe">

2024-04-11 20:03 UTC, fullcolorcoder commented on express/blocks/shared/floating-cta.js
> +      mobieHref: getMetadata('mobile-floating-cta-link'),
Did you mean `mobileHref` here and just below?

2024-04-11 20:51 UTC, JingleH commented on express/blocks/shared/floating-cta.js
> +      mobieHref: getMetadata('mobile-floating-cta-link'),
Good catch! Updating now

2024-04-11 23:11 UTC, echen-adobe approved these changes

2024-04-11 23:15 UTC, JingleH commented on express/blocks/shared/floating-cta.js
> +      text: getMetadata('main-cta-text'),
Hi @fullcolorcoder, https://meta-floating-cta--express--adobecom.hlx.page/express/feature/image/resize would be a good page where the new metadata sheet for it matches the old sheet. LHS has been pretty flaky (most TBT comes from parsing the HTML and Layout recalculation which turn out to fluctuate a lot) and not showing any meaningful difference stage vs this branch. But the idea is that like in screenshot 1, the floatingCTA would show up ~0.4 second sooner, and more importantly, the CTA that it used to "steal" can now be removed before painting the screen, reducing CLS (LHS somehow does not capturing this but you can see that the purple CTA never shows up anymore). And we are fetching 1 fewer json as seen in screenshot 2 (floating-cta.json) which would hopefully bring less competition for downloading our LCP.

2024-04-11 23:17 UTC, JingleH commented on express/scripts/utils.js
> +    if (!isValAffirmative(getMetadata('floating-cta-live')) && getEnv(getConfig()).name === 'prod') return;
that "live" column is actually not longer meaningful, so it's removed. Good catch!

2024-04-11 23:17 UTC, JingleH commented on express/scripts/utils.js
> +
yeah this function doesn't quite make sense... i've removed it from everywhere

2024-04-11 23:21 UTC, JingleH commented on express/blocks/shared/floating-cta.js
> +      text: getMetadata('main-cta-text'),
regarding that bunch of getMetadata, I never get to reproduce meaningfully whether or not that contributes to TBT (currently TBT ranges from 0ms to 600ms and mostly contributed by other stuff). But I've done as you suggest anyway and it should conceptually help out a bit! Let me know if you see anything else!

2024-04-12 14:32 UTC, fullcolorcoder approved these changes

2024-04-30 18:31 UTC, merged