[Security] Remove Inner HTML Usage From Icon Creation
adobecom/express pull request #859
Opened 2024-04-25 15:43 UTC by echen-adobe

Describe your specific features or fixes

Changes the output of getIcon from a HTML string to a proper HTML tag, preventing devs from using innerHTML to set icons. Updates all usage cases of getIcon to accept this change.

Resolves: https://jira.corp.adobe.com/browse/MWPW-144969

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://create-tag-icon--express--adobecom.hlx.page/express/create/menu#how-to

2024-05-08 23:51 UTC, JingleH requested changes
Went through all the pages quickly and all icons behavior seem to be fine. The only thing I wasn't able to check was the app-banner. Can we also take care of the lint warning BTW? Otherwise all LGTM

2024-05-14 21:19 UTC, echen-adobe commented
> Went through all the pages quickly and all icons behavior seem to be fine. The only thing I wasn't able to check was the app-banner. Can we also take care of the lint warning BTW? Otherwise all LGTM

Lint error should be taken care of now. I updated the app banner link with the correct one.

2024-05-15 01:30 UTC, qiyundai reviewed
just 2 non-blocking comments. LGTM otherwise

2024-05-15 01:30 UTC, qiyundai commented on express/blocks/toc/toc.css
> +
nit: extra line break?

2024-05-21 17:12 UTC, JingleH approved these changes

2024-05-29 15:12 UTC, qiyundai approved these changes

2024-05-29 15:13 UTC, merged