[MWPW-147232] Pricing Cards Border Enhancement
adobecom/express pull request #861
Opened 2024-04-25 20:46 UTC by echen-adobe

Describe your specific features or fixes

For cards with gradient promos only. 
Uses negative margin and element specific CSS to detect card a gradient promo but no text. Adjusts the cards margins so that all cards line up regardless of whether there is text or no text inside the gradient promo. Does not require authoring changes.

Resolves: [MWPW-147232](https://jira.corp.adobe.com/browse/MWPW-147232)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://pricing-cards-eyebrow--express--adobecom.hlx.page/express/pricing
- https://pricing-cards-eyebrow--express--adobecom.hlx.page/express/business
- https://pricing-cards-eyebrow--express--adobecom.hlx.page/drafts/echen/pricing-cards

<img width="1308" alt="Screenshot 2024-04-25 at 1 35 36 PM" src="https://github.com/adobecom/express/assets/159481679/2473821d-b81c-426c-ab72-da6cc02e8396">
<img width="526" alt="Screenshot 2024-04-25 at 1 36 41 PM" src="https://github.com/adobecom/express/assets/159481679/3ce701c9-13a0-4df4-b882-e8c2ba50cdcd">
<img width="615" alt="Screenshot 2024-04-25 at 1 36 52 PM" src="https://github.com/adobecom/express/assets/159481679/506d1a43-1a8b-4b6b-9856-107c853cec71">
<img width="1048" alt="Screenshot 2024-04-25 at 1 37 12 PM" src="https://github.com/adobecom/express/assets/159481679/9dab72bb-469b-4cb9-b010-f1550f21a45d">

2024-04-25 20:50 UTC, JingleH requested changes

2024-04-25 20:50 UTC, JingleH commented on express/blocks/pricing-cards/pricing-cards.js
> +    specialPromo.textContent = specialPromo.textContent.trim();
I wonder if we can condense the 2 lines:
[specialPromo.textContent] = inputString.split(token);
specialPromo.textContent = specialPromo.textContent.trim();
into:
[specialPromo.textContent] = inputString.split(token).trim();

2024-04-25 20:50 UTC, JingleH commented on express/blocks/pricing-cards/pricing-cards.css
> +.pricing-cards .gradient-promo:has(div:empty) {
instead of detecting emptiness and adjusting negative margins, I'm wondering if it is easier to give that div a min-height same as it has text

2024-04-25 22:04 UTC, echen-adobe commented on express/blocks/pricing-cards/pricing-cards.js
> +    specialPromo.textContent = specialPromo.textContent.trim();
Why? inputString.split(token) returns an array, not a string.

2024-04-25 22:07 UTC, echen-adobe commented on express/blocks/pricing-cards/pricing-cards.css
> +.pricing-cards .gradient-promo:has(div:empty) {
How would that work? The cards are all encapsulated inside .cards-container, so you will still have to set margin-top separately for the text and no text versions.

2024-04-26 00:09 UTC, JingleH commented on express/blocks/pricing-cards/pricing-cards.js
> +    specialPromo.textContent = specialPromo.textContent.trim();
oh my bad i mean something like specialPromo.textContent = inputString.split(token)[0].trim();

2024-04-26 00:26 UTC, JingleH commented on express/blocks/pricing-cards/pricing-cards.css
> +.pricing-cards .gradient-promo:has(div:empty) {
Oh i was talking about this requirement, where with/without text the gradient eyebrow have same height
<img width="837" alt="SC 2024-04-25 at 5 25 45 PM" src="https://github.com/adobecom/express/assets/32369333/62ab3286-cafe-460d-9d38-43529c818aa0">

2024-04-26 20:01 UTC, JingleH approved these changes

2024-04-29 16:10 UTC, qiyundai approved these changes

2024-04-29 16:43 UTC, merged