[MWPW-133515] [Template X]: Enhance/replace {{heading_placholder}} logic
adobecom/express pull request #87
Opened 2023-07-13 21:15 UTC by qiyundai

Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix [MWPW-133515](https://jira.corp.adobe.com/browse/MWPW-133515)

**Description:**
authors now have an option to define exactly how they want the sentence after the number of templates to be with an extra column in the metadata sheet called 'toolbar-heading'; If the column is empty for the row, the old placeholder from the placeholder will be used.

**Test URLs:**
- Before: https://main--express--adobecom.hlx.page/express/templates/?lighthouse=on
- After: https://mwpw-133515--express--adobecom.hlx.page/express/templates/?lighthouse=on

2023-07-19 09:00 UTC, vhargrave requested changes
Merge conflicts here as well

2023-07-19 20:36 UTC, apganapa approved these changes

2023-07-21 09:09 UTC, vhargrave requested changes
1. pipeline is failing
2. please provide a test url where toolbar-heading is in metadata. I couldn't see it on the test page.

2023-07-21 21:09 UTC, qiyundai commented
> 1. pipeline is failing
> 2. please provide a test url where toolbar-heading is in metadata. I couldn't see it on the test page.

Done & done!

2023-07-24 10:35 UTC, vhargrave commented on express/blocks/template-x/template-x.js
> +      .replace('{{templates-count}}', props.fallbackMsg ? '0' : templateCount)
why add templates-count as well when quantity is doing the exact same thing?

2023-07-24 10:35 UTC, vhargrave commented
> > 1. pipeline is failing
> > 2. please provide a test url where toolbar-heading is in metadata. I couldn't see it on the test page.
> 
> Done & done!

nice!

2023-07-25 14:43 UTC, apganapa approved these changes

2023-07-25 16:32 UTC, qiyundai commented on express/blocks/template-x/template-x.js
> +      .replace('{{templates-count}}', props.fallbackMsg ? '0' : templateCount)
very true

2023-07-25 17:16 UTC, qiyundai commented on express/blocks/template-x/template-x.js
> +  let toolBarHeading = getMetadata('toolbar-heading') ? props.templateStats : placeholders['template-placeholder'];
The idea was that we split the created SEO templates pages (where the authors have control over how many templates get generated on the page) and search templates page (where things are more dynamically generated by value returned by the API, therefore can be 1 or 0 depending on users' search term).

I know some locales don't use the plural and singular placeholders so this overlap is to prevent live page breakage until further authoring works are done.

2023-07-25 22:54 UTC, JingleH submitted a review, later dismissed

2023-07-26 06:56 UTC, vhargrave approved these changes
looking good!

2023-07-26 06:59 UTC, vhargrave requested changes
I'm finding some weird behaviour now on the branch where I can't click on "edit this template" when I hover over one. The hover effect disappears too fast to click. I don't have this behaviour on stage so can you take a look?

2023-07-26 15:09 UTC, merged