[Floating-CTA] Add Hash to sameCTA Comparisons
adobecom/express pull request #906
Opened 2024-05-16 18:46 UTC by JingleH

As of now we only compare pathname. This PR will also require hash to match to qualify for the floatingCTA's sameCTA hiding mechanism.

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/express/business?lighthouse=on
- After: https://fcta-hash--express--adobecom.hlx.page/express/business?lighthouse=on

2024-05-16 19:38 UTC, echen-adobe commented on express/scripts/utils.js
> +            const sameHash = currURL.hash === linkToTargetURL?.pathname;
Since we are changing utils.js, can you provide a list of pages that will be affected by this?

2024-05-16 19:49 UTC, qiyundai requested changes

2024-05-16 19:49 UTC, qiyundai commented on express/scripts/utils.js
> +            const sameHash = currURL.hash === linkToTargetURL?.pathname;
Is it a typo? Looks like you are comparing hash to pathname.

2024-05-16 19:51 UTC, JingleH commented on express/scripts/utils.js
> +            const sameHash = currURL.hash === linkToTargetURL?.pathname;
good catch @qiyundai!

2024-05-16 19:54 UTC, JingleH commented on express/scripts/utils.js
> +            const sameHash = currURL.hash === linkToTargetURL?.pathname;
Sure @echen-adobe! The only page that will really have impact I think would be the new on business and business/teams pages on Stage. These are the pages that authors starting to use hashes and anchors in their links. But if we talk about the general impacts on floatingCTA, then it would include almost all our pages like /express/create, /express/feature, home page, etc.

2024-05-16 20:00 UTC, echen-adobe commented on express/scripts/utils.js
> +            const sameHash = currURL.hash === linkToTargetURL?.pathname;
Can you get them to share a complete list of pages where they are using the hashes?

2024-05-16 20:37 UTC, qiyundai approved these changes

2024-05-16 21:23 UTC, echen-adobe approved these changes

2024-05-17 00:56 UTC, JingleH commented on express/scripts/utils.js
> +            const sameHash = currURL.hash === linkToTargetURL?.pathname;
Confirmed by author that this is the only page!

2024-05-17 00:56 UTC, merged