[MEP] Utils/Scripts Refactoring and MEP Integration
adobecom/express pull request #930
Opened 2024-06-01 02:42 UTC by JingleH

Onboarding MEP requires major refactoring on our rendering scripts to align more with Milo while maintaining backward compatibility. Things changed and to look out for are:
1. Fragments
2. Links
3. Pictures
4. Icons

There should be no obvious visual changes, while on https://mep--express--adobecom.hlx.page/drafts/jingle/mep/mep-mobile MEP should be functioning properly, by inserting different fragments based on phone/desktop.

Resolves: 

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/?lighthouse=on
- After: - After: https://mep--express--adobecom.hlx.page/express/?lighthouse=on
-https://mep--express--adobecom.hlx.page/drafts/jingle/mep/mep-mobile

2024-06-05 14:28 UTC, vhargrave requested changes
damn, I'm pretty excited to see all this. 
I found a few things and once that's done I think we should both do a proper testing run as well.

2024-06-05 14:28 UTC, vhargrave commented on express/scripts/utils.js
> +      redirect_uri: ahomeMeta === 'on'
the redirect_uri technically needs to be new.express.adobe.com . I'm seeing that this will probably an issue I need to get fixed in milo for us.

2024-06-05 14:28 UTC, vhargrave commented on express/scripts/utils.js
> +  // TODO: different from milo as we have legacy decorateBlock()
you don't need to worry about that :) 
i've got it under control.

2024-06-05 14:28 UTC, vhargrave commented on express/scripts/utils.js
> +export function scrollToHashedElement(hash) {
noice

2024-06-05 14:28 UTC, vhargrave commented on express/blocks/template-list/template-list.js
> +  await loadArea($main);
I don't think you need to call loadArea mate. But since this is getting deprecated it also doesn't matter too much.

2024-06-05 19:15 UTC, vhargrave commented on express/scripts/utils.js
> +      redirect_uri: ahomeMeta === 'on'
I've created a ticket to track this

2024-06-19 00:26 UTC, JingleH commented on express/scripts/utils.js
> +    splitSections(main);
good catch!

2024-06-19 00:32 UTC, JingleH commented on express/scripts/utils.js
> +    if (getMetadata('sheet-powered') === 'Y' || window.location.href.includes('/express/templates/')) {
i think this one is a legacy and dangerous one we do only to templates pages once, and it goes replace all placeholders with metadata. We won't be loading placeholdering template-x with fragments

2024-06-19 00:36 UTC, JingleH commented on express/scripts/utils.js
> +    if (getMetadata('template-search-page') === 'Y') {
buildAutoBlocks need to happen after fragmentBlocksToLinks(), which applies to area but happens after checkForPageMods() which only applies to isDoc, so the we had to break the isDoc into 2 😢

2024-06-19 00:41 UTC, JingleH commented on express/scripts/utils.js
>      decoratePageStyle();
this is one of the weird legacy Express global styling thing... but I think if we had to keep it, it should be done after sections are decorated, because the first section's image might not be ready yet and can affect this function's logic

2024-06-19 00:52 UTC, JingleH commented on express/scripts/utils.js
>      decorateLegalCopy(main);
do you mean decoratePageStyle() or the whole decorateExpressPage()? JP stuff is deferred so I'll need to double check if all of the things can wait until deferred. Maybe we can do this as a followup after MEP as performance enhancement

2024-06-19 00:53 UTC, JingleH commented on express/scripts/utils.js
> +    const [unavMeta, ahomeMeta] = [getMetadata('universal-nav')?.trim(), getMetadata('adobe-home-redirect')];
yep shouldn't hurt if we have them now!

2024-06-19 00:54 UTC, JingleH commented on express/scripts/utils.js
> +      redirect_uri: ahomeMeta === 'on'
yes this is tricky... and I've heard that the entire Express will move from new.express.adobe.com to express.adobe.com. So we would need to plan for it a bit. Right now express.adobe.com auto redirects to new.express.adobe.com, but when that happens we do lose some query parameters that we might want to persist

2024-06-19 00:55 UTC, JingleH commented on express/blocks/template-list/template-list.js
> +  await loadArea($main);
yep! Agree!

2024-06-20 11:34 UTC, vhargrave commented on express/scripts/utils.js
> +    if (getMetadata('sheet-powered') === 'Y' || window.location.href.includes('/express/templates/')) {
makes sense 👍

2024-06-20 12:03 UTC, vhargrave commented on express/scripts/utils.js
> +    if (getMetadata('template-search-page') === 'Y') {
why are you saying that buildAutoBlocks needs to happen after fragmentBlocksToLinks? As I'm seeing it buildAutoBlocks is really just for the floating button now. Everything else is going to be removed or refactored anyway. :D 
Why can't we put the code in the lower isDoc if in the upper one? And while doing that we could up the priority a lot to call redirect() if that condition is true, because there's no point executing any code if we're going to redirect the user. What am I missing?

2024-06-20 12:06 UTC, vhargrave commented on express/scripts/utils.js
>      decoratePageStyle();
decoration yes, but you're calling it now after the sections are loaded/processed, which is a big change to what we have right now.

2024-06-20 12:07 UTC, vhargrave commented on express/scripts/utils.js
>      decorateLegalCopy(main);
I think I was referring to decorateLegalCopy being able to be deferred.

2024-06-20 12:08 UTC, vhargrave commented on express/scripts/utils.js
> +      redirect_uri: ahomeMeta === 'on'
yeah agree 👍

2024-06-21 00:57 UTC, JingleH commented on express/scripts/utils.js
> +    if (getMetadata('template-search-page') === 'Y') {
oh yes, didn't realize that our fragment logic is not in buildAutoBlocks now 😇 updated and let me know if it looks better now

2024-06-21 01:03 UTC, JingleH commented on express/scripts/utils.js
>      decoratePageStyle();
got it. Was trying to group it with other Express unique stuff in decoratePageStyle

2024-06-21 01:10 UTC, JingleH commented on express/scripts/utils.js
>      decorateLegalCopy(main);
I just realized that earlier we were doing decorateLegalCopy quite early and should probably boost it up. It kind of makes sense because it's adding legal-copy class, and if applied on marquee and that class causes layout shift, we want that to happen before the first section is loaded and displayed. Moving it to right after decoratePageStyle and let it apply to fragments too now. Let me know how it looks

2024-06-21 01:16 UTC, JingleH commented on express/scripts/utils.js
>      decorateLegalCopy(main);
ahh... I think I know where the confusion is. In Milo, JP stuff is handled Deferred while we do them very early. I was looking at the Milo version and thinking that you want to defer decorateLegalCopy(). I have updated our JP stuff to happen much earlier like before now, so we are aligned.

2024-06-21 01:26 UTC, JingleH commented
@vhargrave do you think we can resolve everything early next week and we can invite more folks to do a bunch of testing? After that you can sync to express-milo repo and that should hopefully make things there clearer too, especially with fragments, which might have some edge cases we need to go over together, mainly with how they unfold and Express's global legacy section-level styling

2024-06-24 12:26 UTC, vhargrave requested changes
Just gave this another thorough review and holy cow you've done a lot lol. It's hard wrapping my head around it all, but I've found another batch of things. Starting to feel a lot better about merging now though. 

This biggest thing I'm seeing is that the gnav doesn't seem to be loading for some reason on the template pages 
https://mep--express--adobecom.hlx.page/express/templates/photo-collage

2024-06-24 12:26 UTC, vhargrave commented on express/scripts/utils.js
> +    const defaultScope = `AdobeID,openid,gnav${unavMeta && unavMeta !== 'off' ? ',pps.read,firefly_api,additional_info.roles,read_organizations' : ''}`;
I've just added this metadata to the metadata sheet so the scopes are set correctly at least, but it hasn't been published yet so until that happens we'll have incomplete scopes, which we'll need for the unav.

2024-06-24 12:26 UTC, vhargrave commented on express/scripts/utils.js
> +      redirect_uri: ahomeMeta === 'on'
I'm just realizing, will this not cause issues if this is set first? Or if we override later does that work?

2024-06-24 12:26 UTC, vhargrave commented on express/scripts/utils.js
> +    const { martechLoadedCB } = await import('./instrument.js');
don't you want a lot of this tracking to still be happening, even with MEP? It'll probably be a while before the old type of tracking is supposed to disappear. 

The only thing you don't want imo is for the martech script to load. Everything else should still happen.

2024-06-24 12:26 UTC, vhargrave commented
> @vhargrave do you think we can resolve everything early next week and we can invite more folks to do a bunch of testing? After that you can sync to express-milo repo and that should hopefully make things there clearer too, especially with fragments, which might have some edge cases we need to go over together, mainly with how they unfold and Express's global legacy section-level styling

@JingleH sure man, let's try 💪

2024-06-24 12:27 UTC, vhargrave commented on express/scripts/utils.js
> +    if (getMetadata('template-search-page') === 'Y') {
it does!

2024-06-24 15:39 UTC, JingleH commented on express/blocks/fragment/fragment.js
> +  // TODO: backward compatability: unlike milo, old ax fragments unfold themselves
My plan was to only support the old block-fragments current behaviors on existing pages, but whenever authors are authoring new stuff, we ask them to do it using the link-fragments. And when we have our next homepage and pricing page revamp (places I think where we use block-fragments most extensively), we can retire the block-fragments fully and eventually. What makes retiring old block-fragments and the unfolding behaviors challenging is our styles css dependency on the section level, so if we take care of that sooner we can also retire it early.

2024-06-24 20:51 UTC, JingleH commented on express/scripts/utils.js
> +    const { martechLoadedCB } = await import('./instrument.js');
Yep they are still happening! So in martech.js, after the martech script is loaded, we are loading our followup martechLoadedCB(). So whenever we load martech, we'll also load our legacy instrument.js. But you reminded me that we probably don't need to rush legacyMartech(instrument.js) anymore in FEP, since we'll use MEP for XLG scenarios. I will see if I can remove this rushing behavior for FEP totally

2024-06-24 21:54 UTC, JingleH commented on express/scripts/utils.js
> +    const { martechLoadedCB } = await import('./instrument.js');
Actually, to account for the unlikely use case of using FEP+XLG without Target, I'm gonna just rush the real martech.js here. Let me know if it looks ok to you! FEP still works for me at https://mep--express--adobecom.hlx.page/express/experiments/ccx0199/premium-discovery-control

2024-06-24 22:07 UTC, JingleH commented on express/scripts/utils.js
> +      redirect_uri: ahomeMeta === 'on'
you're right the one in gnav.js should be referring to this one in utils.js. It shouldn't cause issues because this is only rushed when we have MEP, and in that case the second call of loadIms() will see that imsLoaded and skip loading it again. But we should probably check with the FEDs team about all the new fields we are adding here that is in Milo but not in our loadIMS before... I'll add a todo item in this PR

2024-06-24 22:12 UTC, JingleH commented on express/scripts/utils.js
> +    const defaultScope = `AdobeID,openid,gnav${unavMeta && unavMeta !== 'off' ? ',pps.read,firefly_api,additional_info.roles,read_organizations' : ''}`;
awesome! I'll add this as another item to do before we hit prod.

2024-06-24 22:23 UTC, JingleH commented on express/scripts/utils.js
> +    a.className = `${key} ${a.classList.contains('ax-old-fragment') && 'ax-old-fragment '}link-block`;
sounds good! It's using attribute now

2024-06-24 22:44 UTC, JingleH commented on express/scripts/utils.js
> +    // block.setAttribute('data-block-name', blockName);
Great catch! Do you mean the fixIcons() function? I've added the fallback to block.classList[0]. If it looks good I will remove the two commented lines

2024-06-25 11:23 UTC, vhargrave commented on express/scripts/utils.js
> +    // block.setAttribute('data-block-name', blockName);
Looks good, you could now remove all cases of data-block-name I think actually. None of them are necessary anymore.

2024-06-25 11:24 UTC, vhargrave commented on express/scripts/utils.js
> +    a.className = `${key} ${a.classList.contains('ax-old-fragment') && 'ax-old-fragment '}link-block`;
nice!

2024-06-25 11:25 UTC, vhargrave commented on express/scripts/utils.js
> +    const defaultScope = `AdobeID,openid,gnav${unavMeta && unavMeta !== 'off' ? ',pps.read,firefly_api,additional_info.roles,read_organizations' : ''}`;
sweet!

2024-06-25 11:25 UTC, vhargrave commented on express/scripts/utils.js
> +      redirect_uri: ahomeMeta === 'on'
perfect,thx!

2024-06-25 11:26 UTC, vhargrave commented on express/scripts/utils.js
> +      redirect_uri: ahomeMeta === 'on'
just to be clear btw, I think the `redirect_uri` really needs to be what we're setting in the gnav.

2024-06-25 12:48 UTC, vhargrave commented on express/scripts/utils.js
> +      redirect_uri: ahomeMeta === 'on'
actually, I think I'm wrong. This probably doesn't matter to us anymore lol

2024-06-25 12:49 UTC, vhargrave requested changes
nice, only found a small thing now.

2024-06-25 19:27 UTC, JingleH commented on express/scripts/utils.js
> +    // block.setAttribute('data-block-name', blockName);
great! Let's do the remove data-block-name thingy as a follow up as that will create more file edits and make things scarier. I'll create a ticket

2024-06-25 19:53 UTC, JingleH commented on express/scripts/utils.js
> +    const { martechLoadedCB } = await import('./instrument.js');
i do have a couple of concerns...
- Would we be downloading the file a bit too soon and it might compete for bandwidth and resources with LCP? And  right now technically there is a possibility of that martechLoadedCB being called too soon and even before martech is loaded right? Maybe it has some dependencies over some of the martech's set/setDeep.
- Earlier when martech=off this file won't be downloaded, but now it will always be downloaded
I love the idea of keeping our martech.js more pure and unmodified too, but given that there isn't an event fired for martech script being loaded, we might need to either keep it modified or modify it slightly by firing an event, which we can listen in scripts.js. What would you think about that as a temporary solution? And ultimately in the remaining months let's push the analytics team and see if we can get rid of the whole file. Then we can happily use the same martech and analytics stack ever after @vhargrave. If that's too greedy we can check with the martech team and see if there's anything we can listen to as a fast followup.

2024-06-26 11:12 UTC, vhargrave commented on express/scripts/utils.js
> +    const { martechLoadedCB } = await import('./instrument.js');
Good point 
Regarding LCP that's true. How about this - We add our own event Post LCP and call this right before loading the martech stuff? And if we notice that we aren't able to convince the analytics team to remove the file, then we get this event added to milo as well (maybe I'll find another reason to get it added anyway, but don't have one yet) 
What do you think? 
That way it's being called at the right time, but we're also making less changes to the martech.js file for me to track

2024-06-26 11:53 UTC, vhargrave commented on express/scripts/utils.js
> +    const { martechLoadedCB } = await import('./instrument.js');
@JingleH I went ahead and just added this change. Take a quick look and if you're happy with it then let's get this merged 🚀

2024-06-28 00:25 UTC, merged