[Analytics] [Modal] Added Daa-ll for Modal Close Button
adobecom/express pull request #948
Opened 2024-06-13 01:21 UTC by JingleH

Closing modals right now is not being tracked. This PR will append daa-ll like in Milo and keep the close action recorded.

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/drafts/jinglhua/susi-light?gnav=off
- After: https://modal-close-analytics--express--adobecom.hlx.page/drafts/jinglhua/susi-light?gnav=off

2024-06-13 16:26 UTC, fullcolorcoder requested changes

2024-06-13 16:26 UTC, fullcolorcoder commented on express/blocks/modal/modal.js
> +  const analyticsEventName = window.location.hash ? window.location.hash.replace('#', '') : localeModal;
This seems a little unreliable in that it opens up another opportunity outside our control to modify the value - an extension, or maybe someone embeds a preact app in a modal that alters/relies on hash values and creates more conflict. 

The hash value is already coming from a value found in the DOM, `(a href="#susi-light-1"` in this example translates to `data-modal-hash="#susi-light-1"`) perhaps we could utilize that instead of relying on that round trip.

Also side note, was there an associated ticket with this?

2024-06-13 19:52 UTC, JingleH commented on express/blocks/modal/modal.js
> +  const analyticsEventName = window.location.hash ? window.location.hash.replace('#', '') : localeModal;
Thanks for the review @fullcolorcoder! I agree that checking for hash again seems weird, but I think Milo (https://github.com/adobecom/milo/pull/1998/files#diff-9f2a098ccaf051f7d34bb130078aa108b37d0fcbaaca6274ffb33cc8f118f696R100) had a reason of doing that and we should probably stay in sync. I'll reach out to Vivian and get confirmation too. Good catch on the ticket as well, I have updated the PR description.

2024-06-14 15:08 UTC, fullcolorcoder approved these changes

2024-06-17 19:29 UTC, echen-adobe approved these changes

2024-06-17 20:44 UTC, merged