Import Milo Section Styles
adobecom/express pull request #988
Opened 2024-06-28 16:36 UTC by echen-adobe

Describe your specific features or fixes

Import the Milo Section Metadata styles to Express

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://import-milo-section-stypes--express--adobecom.hlx.page/express/

2024-07-08 09:56 UTC, vhargrave requested changes
I've just taken a look at stage, and Jingle has already added the section-metadata.css file. 
instead of adding all this stuff to our styles.css, why not just import the section-metadata.css when we really need it? 
Even better would be to start getting the section-metadata to load like it does in milo, but no pressure to do that. :) 

All this would mean that you can heavily simplify this PR so you're only setting the --grid-container-width variables.

2024-07-08 09:56 UTC, vhargrave commented on express/styles/styles.css
> +body>header {
can you revert all these stylistic changes and if you want to add them do it in a separate PR? Just to make it easier to see what was actually added in this PR that's relevant.

2024-07-08 09:57 UTC, vhargrave commented on express/styles/styles.css
> +body>header {
every PR should have a jira task btw.

2024-07-08 15:14 UTC, echen-adobe commented on express/styles/styles.css
> +body>header {
Wasn't aware that the seciton-metadata file included the masonry styles. I've removed the unnecessary changes so that we only have the grid variables

2024-07-08 19:27 UTC, echen-adobe commented on express/styles/styles.css
> +body>header {
@vhargrave There are a bunch of styles in tabs-ax.css that seem to be ported from Milo as well. I ported those over since there seems to be no reason for them to be in the separate file.

2024-07-09 09:46 UTC, vhargrave commented on express/styles/styles.css
> +body>header {
nice! 👍

2024-07-09 09:48 UTC, vhargrave reviewed
Two more things. 
1. we still need to load the styles from the section-metadata.css. I don't think that's happening currently. 
2. If you could have a test page where some of these section-metadata styles are being used and tested that would be great.

2024-07-09 20:22 UTC, echen-adobe commented
>we still need to load the styles from the section-metadata.css. I don't think that's happening currently.

We want to load the styles from section-metadata on a case to case basis because in Franklin the section metadata is always deleted. To use those styles in Franklin would involve selectively enabling the section-metadata block. We already discussed this morning how to do so. However, since this is not a feature specific PR I don't think that belongs here. It should either be in a separate PR that incorporates this one. 

I've incorporated such a change in 

https://github.com/adobecom/express/pull/983

That PR hides section-metadata if one of the keys is "style", otherwise it removes it by default.

That PR contains the example pages as well.

2024-07-10 21:53 UTC, fullcolorcoder approved these changes

2024-07-11 07:44 UTC, vhargrave reviewed
as said I think we can close this PR, because it's now replaced with this one - https://github.com/adobecom/express/pull/983/files#diff-6895527ef9b5a915649d265b70f7bb216f90e2ef5efea0d8cfa6827f64190f41

2024-07-15 22:55 UTC, closed without merging