New Feature Grid With Custom Backgrounds
adobecom/express pull request #993
Opened 2024-07-08 22:46 UTC by echen-adobe

Describe your specific features or fixes

Implements a new version of the feature grid with properties that are more flexible.

Users can now specify new properties within the block as pictured below.

<img width="737" alt="Screenshot 2024-07-08 at 3 44 57 PM" src="https://github.com/adobecom/express/assets/159481679/0c020e8a-f2b3-4230-ac2b-b3952aae67cf">

This allows the user to customize the background of the feature grid cards and the load more button more effectively. This functionality is not available on the older feature grids and will require authoring work.

Resolves: [MWPW-153691](https://jira.corp.adobe.com/browse/MWPW-153691)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After:  https://feature-grid--express--adobecom.hlx.page/drafts/echen/feature-grid-desktop

<img width="859" alt="Screenshot 2024-07-08 at 3 42 44 PM" src="https://github.com/adobecom/express/assets/159481679/be148ab7-ea5d-4387-a3b8-f0c240b8130a">
<img width="1784" alt="Screenshot 2024-07-08 at 3 43 34 PM" src="https://github.com/adobecom/express/assets/159481679/b02c3a83-43a3-4a48-97d4-f7c4f6435cfd">

2024-07-09 16:41 UTC, JingleH approved these changes

2024-07-09 16:48 UTC, kennethlum approved these changes

2024-07-10 21:32 UTC, fullcolorcoder requested changes

2024-07-10 21:32 UTC, fullcolorcoder commented on express/blocks/feature-grid/feature-grid.js
> +    console.log(row);
Stray console

2024-07-10 21:32 UTC, fullcolorcoder commented on express/blocks/feature-grid/feature-grid.js
> +      allProperties[key.toLowerCase()] = value;
No test coverage

2024-07-10 21:32 UTC, fullcolorcoder commented on express/blocks/feature-grid/feature-grid.js
> +  console.log(colorProperties);
Stray console

2024-07-18 16:01 UTC, fullcolorcoder approved these changes
Not standing in the way of merging, but it'd be awesome if you could clean up the linting errors so they don't pile up.

<img width="583" alt="image" src="https://github.com/user-attachments/assets/ee6f1b61-7993-42bf-955e-d3f35ec107b6">

2024-07-18 21:11 UTC, merged